/* Public teaching material only. Never receives an accounting snapshot or identity. */
(function(root){
 const checked='2026-09-14',version='1.0.0',disclaimer='Dit is algemene uitleg en geen persoonlijk fiscaal advies.';
 const bd='https://www.belastingdienst.nl/wps/wcm/connect/';
 const sources={
  administration:['Belastingdienst · Een goede administratie',bd+'bldcontentnl/belastingdienst/zakelijk/ondernemen/onderneming_starten/houd-een-goede-administratie-bij/'],
  invoice:['Belastingdienst · Factuureisen',bd+'bldcontentnl/belastingdienst/zakelijk/btw/administratie_bijhouden/facturen_maken/factuureisen/factuureisen'],
  retention:['Belastingdienst · Facturen bewaren',bd+'bldcontentnl/belastingdienst/zakelijk/btw/administratie_bijhouden/facturen_maken/uw_facturen_bewaren'],
  private:['Belastingdienst · Privéstortingen en privéonttrekkingen',bd+'bldcontentnl/belastingdienst/zakelijk/winst/inkomstenbelasting/inkomstenbelasting_voor_ondernemers/privestortingen_en_priveonttrekkingen'],
  period:['Belastingdienst · Aangiftetijdvak btw',bd+'nl/btw/content/wijziging-aangiftetijdvak-btw'],
  nil:['Belastingdienst · Ook zonder omzet aangifte?',bd+'nl/btw/content/moet-ik-altijd-btw-aangifte-doen'],
  filing:['Belastingdienst · Btw-aangifte invullen',bd+'nl/btw/content/ik-moet-btw-aangifte-doen-hoe-vul-ik-die-in'],
  method:['Belastingdienst · Btw berekenen en stelsels',bd+'bldcontentnl/belastingdienst/zakelijk/btw/btw_aangifte_doen_en_betalen/bereken_het_bedrag/hoe_berekent_u_het_btw_bedrag/'],
  input:['Belastingdienst · Welke btw is aftrekbaar?',bd+'bldcontentnl/belastingdienst/zakelijk/btw/btw_aftrekken/welke_btw_is_aftrekbaar/'],
  income:['Belastingdienst · Inkomstenbelasting voor ondernemers',bd+'bldcontentnl/belastingdienst/zakelijk/winst/inkomstenbelasting/inkomstenbelasting_voor_ondernemers/'],
  asset:['Belastingdienst · Wat is afschrijven?',bd+'bldcontentnl/belastingdienst/zakelijk/winst/inkomstenbelasting/inkomstenbelasting_voor_ondernemers/afschrijving/'],
  costs:['Belastingdienst · Zakelijke kosten',bd+'bldcontentnl/belastingdienst/zakelijk/winst/inkomstenbelasting/inkomstenbelasting_voor_ondernemers/zakelijke_kosten/'],
  ingcsv:['ING · Bestandsformaten (Mijn ING Zakelijk: puntkommagescheiden CSV)','https://www.ing.nl/zakelijk/betalen/betalingen-doen/bestandsformaten'],
  ingdownload:['ING · Afschriften downloaden; algemene route','https://www.ing.nl/zakelijk/financieren/mt940-downloaden'],
  inglink:['ING · Koppeling met een boekhoudpakket','https://www.ing.nl/zakelijk/digitaal-bankieren/eenvoudig-boekhouden/koppeling-boekhoudpakket']
 };
 const headings=['Wat is dit?','Waarom heb je dit nodig?','Waar vind je dit in APPFMZ?','Wanneer gebruik je dit?','Wanneer gebruik je dit juist niet?','Voorbeeld uit FitMetZorge','Doe het nu zelf','Wat hoort het resultaat te zijn?','Veelgemaakte fouten','Korte controle','Volgende stap'];
 const lessons=[];
 function lesson(title,where,what,why,when,avoid,example,doNow,result,mistakes,quiz,refs=[]){lessons.push({id:lessons.length+1,title,sections:[what,why,where,when,avoid,example,doNow,result,mistakes,'Beantwoord beide vragen. Je krijgt uitleg bij ieder antwoord.','Ga verder als je de oefening en de korte controle begrijpt. Je mag ook overslaan; dat telt nog niet als afgerond.'],quiz,refs});}
 const q=(question,options,correct,feedback)=>({question,options,correct,feedback});
 lesson('Wat is boekhouden?','Administratie → Overzicht. De onderliggende gebeurtenissen vind je bij Verkoopfacturen, Uitgaven en bonnen en Bank en Kas.',
  'Je administratie is het controleerbare verhaal van je onderneming: wat je verkoopt, uitgeeft, bezit en verschuldigd bent. Omzet is verkoopopbrengst zonder de btw die je afdraagt. Een ontvangst is geld dat binnenkomt. Kosten verlagen het bedrijfsresultaat; een uitgave is geld dat weggaat. Winst is globaal omzet min zakelijke kosten. Btw is een belasting op leveringen en diensten; inkomstenbelasting gaat over je persoonlijke jaarinkomen.',
  'Je wilt weten wat klanten nog moeten betalen en welke documenten bij iedere boeking horen. Als eenmanszaak heb je een controleerbare administratie nodig. Digitale facturen en basisgegevens bewaar je doorgaans zeven jaar; er bestaan langere termijnen, bijvoorbeeld voor onroerende zaken en bepaalde btw-regelingen. Controleer wat voor jouw gegevens geldt.',
  'Leg zakelijke gebeurtenissen vast wanneer ze plaatsvinden. Bewaar het bewijs en koppel de latere betaling aan de oorspronkelijke factuur.',
  'Boek een ontvangen betaling niet nogmaals als verkoop. Trek uit alleen het banksaldo geen conclusie over winst: daarop staan ook btw, leningen en privégeld.',
  'Een oefenklant krijgt een factuur van €200. Later betaalt die klant €200. Er is één verkoop en één betaling, geen €400 verkoop. Een aparte €0,20 uit privé is geen omzet.',
  'Koppel drie gebeurtenissen aan hun betekenis en controleer dat de verkoop maar één keer meetelt.',
  'Je houdt één verkoop van €200 apart van de betaling en de privéstorting. Bij echte btw-plicht is de omzet het bedrag exclusief btw.',
  'Een factuur verwarren met een bankbetaling. Een privéontvangst als omzet indelen. Documenten wissen zodra ze betaald zijn.',
  [q('Een klant betaalt een bestaande factuur. Wat doe je?',['Nieuwe verkoop boeken','Betaling aan die factuur koppelen'],1,'De verkoop bestaat al. De koppeling verlaagt wat de klant nog moet betalen.'),q('Is het banksaldo automatisch je winst?',['Ja','Nee'],1,'Op de bank kunnen ook btw en privéstortingen staan; winst is een ander overzicht.')],['administration','retention']);
 lesson('Rondleiding door Administratie','De negen onderdelen in het menu van Administratie.',
  'Overzicht vat bedragen en waarschuwingen samen. Verkoopfacturen bevat concepten, definitieve facturen en correcties. Uitgaven en bonnen bevat zakelijke aankopen en bewijs. Bank en Kas bevat geldbewegingen en afstemming. Privéstortingen en privéopnames houdt privégeld apart. Bezittingen en schulden bevat bijvoorbeeld een bedrijfsmiddel of lening. Btw-overzicht bereidt je controle voor. Rapporten en export maakt bestanden. Administratie-instellingen bevat bedrijfsgegevens en bevestigde instellingen.',
  'Je hoeft niet te raden waar iets hoort. De overzichten rekenen uit bestaande boekingen; jij controleert gegevens, bewijs, koppelingen en waarschuwingen.',
  'Begin bij Overzicht en open daarna het onderdeel van de gebeurtenis. Een bankontvangst verwerk je bij Bank en Kas, de oorspronkelijke factuur bij Verkoopfacturen.',
  'Voer een bedrag niet opnieuw in bij ieder overzicht. Dezelfde boeking kan op meerdere plekken zichtbaar zijn zonder meerdere transacties te worden.',
  'Een bon van een oefenwinkel staat bij Uitgaven en bonnen; de betaling staat bij Bank en Kas. Het overzicht verbindt die gegevens.',
  'Open alle negen voorbeeldonderdelen en plaats de drie voorbeeldtaken op de juiste plek.',
  'Je weet waar je een bon, een betaling en een export vindt. Er is niets in de echte administratie geopend of gewijzigd.',
  'Een berekend overzicht behandelen als invoerscherm. Denken dat een automatische berekening ook bewijs of fiscaal akkoord geeft.',
  [q('Waar koppel je een bankbetaling?',['Bank en Kas','Administratie-instellingen'],0,'De ontvangst staat bij de banktransacties.'),q('Wie controleert de brongegevens?',['Ikzelf','Een totaalkaart bewijst alles'],0,'Een berekening kan pas betrouwbaar zijn als de ingevoerde gegevens en koppelingen kloppen.')]);
 lesson('Bedrijfsinstellingen','Administratie → Administratie-instellingen. Niet ieder hieronder uitgelegd begrip heeft een apart veld in de huidige app.',
  'Bedrijfsgegevens vertellen wie de factuur uitgeeft en waar de klant kan betalen. De tabel bij deze les legt per gegeven uit waar je het vindt, wanneer het nodig is en wat ontbrekende informatie betekent. Btw-periode is het tijdvak voor de aangifte; een stelsel bepaalt op welk moment omzet-btw in het overzicht komt.',
  'Onjuiste naam, adres, btw-identificatie of rekeninggegevens kunnen een factuur onvolledig maken of betaling bemoeilijken. Controleer echte gegevens met je eigen registraties en belastingbrieven.',
  'Controleer bij de start en na een werkelijke wijziging. Kijk vóór definitief factureren of de bedrijfsgegevens compleet zijn.',
  'Kies geen btw-tarief, KOR, vrijstelling of kasstelsel omdat een oefenvoorbeeld dat gebruikt. De oefening gebruikt een vooraf gekozen fictieve 21%-situatie met factuurstelsel; dit zegt niets over FitMetZorge.',
  'FitMetZorge Oefenbedrijf, Voorbeeldstraat 10, 1000 AA Voorbeeldstad, oefenbedrijf@example.test. Alle gegevens hier zijn verzonnen. De app heeft geen afzonderlijk instelveld voor handelsnaam, BIC, rekeninghouder, nummerreeks of boekjaar. De echte nummering wordt door de server beheerd; gebruik die uitlegvelden niet als belofte van een instelling.',
  'Vul de fictieve bedrijfskaart in. Controleer de bron en betekenis van alle velden in de uitklapbare veldhulp. Sla uitsluitend de oefeninstellingen op.',
  'Je ziet de fictieve bedrijfskaart en een controle op ontbrekende gegevens. De echte instellingen zijn niet geladen.',
  'Een fictief KVK- of btw-nummer overnemen. IBAN verwarren met bankkoppeling. Zelf een nummerreeks proberen te resetten. Btw-behandeling afleiden uit alleen het pakket.',
  [q('Kiest deze cursus jouw btw-stelsel?',['Nee, dat controleer ik met mijn eigen gegevens','Ja, altijd 21%'],0,'De 21% is alleen een rekensituatie. De bestaande bevestigde instelling blijft leidend.'),q('Maakt een IBAN invullen een bankkoppeling?',['Ja','Nee'],1,'Een bankkoppeling is een afzonderlijke voorziening; hier wordt die niet aangelegd.')],['invoice','method','inglink']);
 lesson('Bank instellen en openingssaldo','Administratie → Bank en Kas → rekening. Daar zie je openingssaldo en berekend saldo.',
  'Bank is de weergave van je zakelijke rekening in de boekhouding. Het openingssaldo is het saldo waarmee je begint. In de huidige APPFMZ-invoer kies je de eerste transactiedag; het openingssaldo hoort bij het einde van de dag ervoor.',
  'Datum en saldo moeten hetzelfde meetmoment beschrijven. Anders lijkt er later geld te ontbreken of dubbel te staan.',
  'Bij het aansluiten van de administratie. Neem daarna alle transacties vanaf de eerste transactiedag op.',
  'Maak geen nieuw openingssaldo voor iedere import. Voer een bedrag dat al in het openingssaldo zit niet nogmaals als transactie in. Een IBAN maakt geen automatische ING-koppeling.',
  'De fictieve rekening eindigt op 31 augustus 2026 met €0,20. Eerste transactiedag: 1 september 2026. Een nieuwe privéstorting van €0,20 op 3 september is een andere gebeurtenis.',
  'Stel Oefenbank in met eerste transactiedag 2026-09-01 en openingssaldo €0,20.',
  'Openingssaldo €0,20, berekend saldo €0,20 zolang er nog geen transacties zijn.',
  'Het saldo van vandaag combineren met de startdatum van vorige maand. Dezelfde storting zowel in het begin als in de import opnemen.',
  [q('Eerste transactiedag is 1 september. Bij welk moment hoort het openingssaldo?',['Einde 31 augustus','Einde 30 september'],0,'De app sluit aan op het einde van de vorige dag.'),q('Moet iedere CSV een nieuw openingssaldo krijgen?',['Nee','Ja'],0,'Import voegt transacties toe aan de bestaande aansluiting.')],['inglink']);
 lesson('Privéstorting van €0,20','Administratie → Bank en Kas voor de transactie; daarna ook zichtbaar bij Privéstortingen en privéopnames en het rekeningoverzicht.',
  'Een privéstorting is geld dat je zelf vanuit privé in je eenmanszaak stopt. Het ondernemingsvermogen, wat van jou in de onderneming zit, neemt toe.',
  'Je wilt voorkomen dat eigen geld als een nieuwe klantverkoop of winst wordt geteld.',
  'Als een aantoonbare overboeking uit jouw privégeld komt. Controleer de herkomst.',
  'Bij een klantbetaling, lening of onbekende herkomst. Twijfel je, laat de transactie beoordelen in plaats van te gokken.',
  'Op 3 september komt €0,20 vanuit privé binnen. De fictieve bank gaat van €0,20 naar €0,40; de omzet blijft gelijk.',
  'Open de ontvangst en kies uit omzet, klantbetaling, privéstorting, lening of onbekend.',
  'Privéstorting €0,20. Bank en ondernemingsvermogen stijgen; geen verkoopfactuur, omzet, winst, zakelijke kosten of automatische btw.',
  'Een privéstorting een factuurnummer geven. Het bedrag nog eens als omzet boeken.',
  [q('Maakt een privéstorting winst?',['Ja','Nee'],1,'Je brengt eigen vermogen in. Je verkoopt geen dienst.'),q('Waar kun je de boeking terugvinden?',['Privémutaties en Bank en Kas','Alleen Verkoopfacturen'],0,'Er wordt juist geen verkoopfactuur gemaakt.')],['private']);
 lesson('Kas begrijpen','Administratie → Bank en Kas. Kas is de rekening voor werkelijk contant geld.',
  'Kas betekent munten en bankbiljetten die zakelijk aanwezig zijn. Geld op ING is bankgeld. Een interne overboeking verplaatst geld tussen je eigen zakelijke rekeningen.',
  'Door kas en bank apart bij te houden kun je het geld daadwerkelijk tellen en vergelijken.',
  'Gebruik Kas als je contante betalingen ontvangt of doet. Zonder contant geld kun je Kas verbergen; geschiedenis hoeft niet te verdwijnen.',
  'Boek een pin- of bankbetaling niet in Kas. Een storting van kas naar bank is geen nieuwe verkoop.',
  'Een klant betaalt een bestaande oefenverkoop van €50 contant. Kas +€50. Bij het storten op de bank: Kas −€50 en Bank +€50. De verkoop telt één keer.',
  'Oefen beide routes: verberg Kas zonder te wissen en verwerk daarna een contante betaling plus interne overboeking.',
  'De eerste route laat Kas veilig verborgen. De tweede eindigt met Kas €0 en Bank €50 hoger, zonder extra omzet.',
  'Verbergen verwarren met verwijderen. Een interne overboeking als klantbetaling kiezen.',
  [q('Waar hoort geld op ING?',['Kas','Bank'],1,'Kas is uitsluitend contant geld.'),q('Is kasgeld op de bank storten opnieuw omzet?',['Nee','Ja'],0,'Hetzelfde geld wisselt alleen van zakelijke plek.')]);
 lesson('Pakketten, prijzen en facturen','Verkoopfacturen → concept. Pakketprijzen komen uit de bestaande pakketdefinities.',
  'Een pakketprijs is het totaal voor de afgesproken maand. Een factuurregel beschrijft wat je levert; aantal × regelprijs vormt de basis. Korting verlaagt die basis. Exclusief btw is zonder belasting, inclusief btw is het te betalen bedrag. Betaaltermijn is het aantal dagen; vervaldatum is de uiterste betaaldag. Factuurperiode beschrijft wanneer je levert; factuurnummer identificeert het document.',
  'De klant moet kunnen zien wat de maand kost en waar een korting vandaan komt.',
  'Bij een nieuwe maandfactuur: Basis 4 trainingen €200; Progressie 8 trainingen €380; Transformatie 12 trainingen €480. Aantal 1 betekent één maandpakket.',
  'Vermenigvuldig een volledig maandbedrag niet nogmaals met het aantal trainingen. Gebruik geen gemiddelde kalenderweken. Duo, online coaching en prijsafspraken hebben geen nieuw oefentarief.',
  'Progressie: één maandpakket €380, korting €30, totaal €350. Met uitsluitend het fictieve 21%-rekentarief is dat €289,26 netto plus €60,74 btw.',
  'Kies elk van de drie pakketten en controleer de maandprijs. Bereken het Progressievoorbeeld.',
  'De maandbedragen zijn €200, €380 en €480. Het bedrag van €350 is inclusief de bestaande btw-behandeling; er komt geen tweede btw bovenop.',
  'Prijs per training als maandprijs gebruiken. Btw bij een inclusief bedrag optellen. De oefen-btw als jouw fiscale keuze behandelen.',
  [q('Wat is Progressie per maand?',['€47,50','€380'],1,'€47,50 is de aanvullende prijs per training; het maandpakket is €380.'),q('€380 min €30 is…',['€350 inclusief de gekozen btw-behandeling','€350 plus altijd nog 21%'],0,'De bestaande inclusief-btw-invoer bepaalt het te betalen bedrag.')],['invoice','method']);
 lesson('Conceptfactuur maken','Administratie → Verkoopfacturen → concept openen. Bewerk eerst, controleer daarna de A4-preview.',
  'Een concept is een bewerkbare voorbereiding. Het is nog geen definitieve of verzonden factuur. In de echte administratie kun je een concept verwijderen zolang het niet definitief is.',
  'Je kunt klant, data, omschrijving en korting controleren voordat je een definitief document uitgeeft.',
  'Maak voor de fictieve klant een septemberfactuur. De factuurdatum is de datum van uitgifte; de periode beschrijft de dienstverlening. De vervaldatum volgt uit de afgesproken betaaltermijn.',
  'Behandel typen of concept opslaan niet als definitief maken of verzenden. Vul geen lege prijs in om een waarschuwing te omzeilen.',
  'Oefenklant Noor Voorbeeld, Progressie september 2026, factuurdatum 1 september, termijn 14 dagen, vervaldatum 15 september. €380 minus €30 welkomstkorting = €350.',
  'Vul de velden in, open de A4-preview, pas desgewenst de omschrijving aan en bewaar het oefenconcept.',
  'De preview en het opgeslagen oefenconcept bevatten dezelfde €350. Er is geen echt factuurnummer.',
  'Een negatieve korting, korting boven het bedrag, ontbrekende datum of lege prijs. Definitief maken terwijl de preview nog niet klopt.',
  [q('Is een opgeslagen concept al verzonden?',['Nee','Ja'],0,'Opslaan, definitief maken en verzenden zijn verschillende handelingen.'),q('Kun je een concept nog aanpassen?',['Ja','Nee'],0,'Juist vóór definitief maken controleer en verbeter je het concept.')],['invoice']);
 lesson('Factuur definitief maken','Verkoopfacturen → gecontroleerd concept → Opslaan en PDF downloaden. Controleer de concrete knoptekst bij de definitieve handeling.',
  'Een definitieve factuur legt de beoordeelde gegevens vast. Normaal krijgt die een uniek, opeenvolgend nummer. De oefenmodus gebruikt uitsluitend OEFEN-2026-001; dat nummer wordt nooit gereserveerd in de echte administratie.',
  'Een bewaard document moet later dezelfde bedragen tonen. Een download opnieuw proberen hoort geen nieuwe factuur te maken.',
  'Pas wanneer klant, uitgiftedatum, periode, regels, korting en totaal kloppen. Bewaar de uiteindelijke PDF.',
  'Maak niet opnieuw een factuur omdat downloaden mislukte. Een definitief document stilzwijgend aanpassen maakt de geschiedenis oncontroleerbaar.',
  'De oefenfactuur van €350 krijgt het vaste oefennummer en op iedere pagina OEFENFACTUUR — NIET GELDIG. Opnieuw downloaden gebruikt dezelfde vastgelegde bytes in deze oefensessie.',
  'Controleer de gegevens, maak de oefenfactuur expliciet definitief en open, zoom, sluit en download de PDF.',
  'Eén definitieve oefenfactuur; opnieuw klikken maakt geen tweede. Geen Storage-upload, e-mail of echt nummer.',
  'Een download verwarren met verzending. Een fout herstellen door het definitieve origineel te overschrijven; gebruik de passende correctieroute.',
  [q('Een download faalt. Wat probeer je opnieuw?',['Dezelfde PDF downloaden','Een tweede factuur uitgeven'],0,'De definitieve gegevens en het nummer blijven gelijk.'),q('Is het oefennummer een echte reservering?',['Nee','Ja'],0,'Het is een vaste synthetische aanduiding in tijdelijk geheugen.')],['invoice','retention']);
 lesson('Openstaand versus betaald','Verkoopfacturen voor de status; Bank en Kas voor de ontvangen betaling en koppeling.',
  'Openstaand is het bedrag dat nog aan de factuur moet worden gekoppeld. Betaald betekent dat de juiste ontvangst volledig is gekoppeld. Een overbetaling kan juist een bedrag opleveren dat je moet terugbetalen.',
  'Je wilt weten of er werkelijk geld ontvangen is en welke klant nog moet betalen.',
  'Controleer na een ontvangen betaling of bedrag, datum, klant en factuur bij elkaar horen.',
  'Markeer een factuur niet betaald omdat je hem hebt gemaakt of gedownload. Een losse bankbijschrijving bewijst zonder controle nog geen juiste factuurkoppeling.',
  'De factuur is €350 openstaand. Bij alleen de bankimport blijft de factuur nog open; pas de gecontroleerde koppeling verlaagt het openstaande bedrag.',
  'Voeg de vaste oefenontvangst toe en vergelijk de status vóór en na koppelen.',
  'Voor koppelen: €350 open. Erna: €0 open en Betaald. Geen extra verkoop.',
  'Status handmatig willen forceren zonder ontvangst. Het banksaldo verwarren met openstaande facturen.',
  [q('Zet een factuur maken geld op de bank?',['Nee','Ja'],0,'Een factuur is een vordering; de ontvangst is een aparte gebeurtenis.'),q('Is een onverklaarde bijschrijving altijd een betaalde factuur?',['Nee','Ja'],0,'Je moet eerst weten bij welke klant en factuur de betaling hoort.')]);
 lesson('Betaling aan factuur koppelen','Administratie → Bank en Kas → transactie verwerken → factuur kiezen.',
  'Koppelen verbindt een bankontvangst aan een bestaande verkoop. De factuur blijft bestaan; het nog te ontvangen bedrag neemt af.',
  'Daarmee voorkom je dubbele omzet en kun je de status van iedere factuur verklaren.',
  'Controleer betaler, datum, bedrag en beschikbare factuur. Een omschrijving kan onjuist zijn; controleer dan extra bewijs voordat je koppelt.',
  'Past de betaling nergens bij, laat hem onbekend of later beoordelen. Een automatisch voorstel is geen verplichting om te bevestigen.',
  'Eerst €100, later €250 voor één factuur van €350. Na de eerste koppeling is €250 open, na de tweede €0. Een dubbele import van dezelfde ontvangst telt niet mee.',
  'Koppel één volledige betaling, oefen daarna twee deelbetalingen, een afwijkende omschrijving, een onbekende ontvangst en een duplicaat.',
  'Alleen gecontroleerde ontvangsten zijn gekoppeld. De bekende factuur is Betaald; de onbekende betaling blijft zichtbaar voor beoordeling.',
  'Iedere deelbetaling opnieuw factureren. Blind een omschrijving volgen. Een dubbele regel als tweede betaling importeren.',
  [q('Na €100 op €350 blijft open…',['€250','€350'],0,'Een deelbetaling verlaagt het openstaande bedrag met precies het gekoppelde bedrag.'),q('Een betaling past bij geen factuur. Wat doe je?',['Later beoordelen','Willekeurige factuur selecteren'],0,'Bewaar het twijfelgeval totdat je de herkomst kunt onderbouwen.')]);
 lesson('Uitgaven en bonnen','Administratie → Uitgaven en bonnen; koppel de betaling in Bank en Kas.',
  'Een uitgave is geld dat je betaalt. Zakelijke kosten horen bij de onderneming; privé-uitgaven niet. Een bon of inkoopfactuur onderbouwt de leverancier, datum, prestatie en belasting. Voorbelasting is inkoop-btw die je volgens de regels mag aftrekken.',
  'Een bankafschrijving vertelt vaak onvoldoende wat je kocht en of kosten of btw aftrekbaar zijn.',
  'Leg leverancier, factuur- of bondatum, omschrijving, categorie, bedrag, btw-behandeling en bewijs vast. De betaaldatum kan anders zijn dan de bondatum. Koppel de banktransactie apart.',
  'Een bon ontbreekt of het zakelijke doel is onduidelijk: vraag bewijs op en laat het punt ter beoordeling staan. Trek niet automatisch alle btw af. Bijzonderheden, vrijstelling, KOR en privégebruik kunnen de aftrek beperken.',
  'Alleen als rekensituatie: Oefenwinkel verkoopt zakelijk materiaal voor €24,20 inclusief 21%: €20,00 kosten en €4,20 toegestane voorbelasting. In dit fictieve geval is het bewijs aanwezig en gebruik volledig zakelijk.',
  'Vul de uitgave in en kies de meegeleverde synthetische bon. Oefen ook de route waarin bewijs ontbreekt.',
  'Eén uitgave van €24,20, één gekoppelde bankafschrijving, het synthetische bewijs en afzonderlijke bedragen €20,00 en €4,20.',
  'De betaling nogmaals als kosten boeken. Een privéaankoop zakelijk noemen. Btw aftrekken alleen omdat het bedrag 21% lijkt te bevatten.',
  [q('Bewijst een bankafschrijving aftrekbare btw?',['Nee','Ja'],0,'Je hebt de juiste onderbouwing én een toegestane btw-behandeling nodig.'),q('Welke datum hoort bij het document?',['Factuur- of bondatum','Altijd de dag van uploaden'],0,'De documentdatum en betaaldatum zijn verschillende gegevens.')],['costs','input']);
 lesson('Privégeld opnemen','Administratie → Bank en Kas → Privéopname. Terug te vinden bij Privéstortingen en privéopnames.',
  'Een privéopname is geld dat je uit je eenmanszaak naar privé haalt. Het vermindert wat van jou in de onderneming zit.',
  'Je wilt privébestedingen gescheiden houden van kosten van je onderneming.',
  'Bij de aantoonbare overboeking van de zakelijke rekening naar jezelf voor privégebruik.',
  'Noem dit geen zakelijke kosten of salaris aan jezelf. Voor een eenmanszaak verlaagt zo een opname niet automatisch de belastbare winst.',
  'De oefenbank betaalt €100 naar privé. Bank en ondernemingsvermogen dalen met €100; de zakelijke winst blijft gelijk.',
  'Open de afschrijving, controleer de herkomst en kies Privéopname.',
  'De privémutatie is herkenbaar en telt niet mee als kosten of automatische btw-aftrek.',
  'Privéopname onder loon of bedrijfskosten zetten. Denken dat een lagere bankstand automatisch minder belasting betekent.',
  [q('Is €100 privé opnemen salaris aan jezelf bij een eenmanszaak?',['Nee','Ja'],0,'Je boekt een onttrekking aan je ondernemingsvermogen.'),q('Verlaagt deze opname automatisch de winst?',['Nee','Ja'],0,'Privéopnames zijn geen zakelijke kosten.')],['private']);
 lesson('Wat is een CSV?','Administratie → Bank en Kas → CSV importeren; controleer eerst het voorbeeld.',
  'CSV is een tekstbestand met regels en kolommen. Een bankregel bevat bijvoorbeeld datum, bedrag, tegenpartij en omschrijving. Bij ING Zakelijk bestaat een puntkommagescheiden CSV-formaat.',
  'Met een bestand hoef je niet iedere transactie over te typen. Toch moet je rekening, periode, kolommen en duplicaten controleren.',
  'Gebruik een CSV-export van je eigen bank in je eigen beveiligde administratie. Bewaar het bronbestand gecontroleerd.',
  'Een PDF-bankafschrift is een leesdocument, geen CSV. Een CSV is geen factuur en bevat geen bankwachtwoord, maar kan wel gevoelige financiële gegevens bevatten. Deze oefenomgeving accepteert alleen het vaste oefenbestand.',
  'De voorbeeldtabel bevat zes regels: vijf verschillende transacties en één opzettelijk herhaalde ontvangst van €350.',
  'Bekijk de kolommen en wijs datum, bedrag en omschrijving aan. Download desgewenst het oefenbestand.',
  'Je herkent regels, kolommen en de dubbele transactie voordat je importeert.',
  'Een PDF hernoemen naar .csv. Een echt bankbestand in een oefening proberen. Aannemen dat ieder tekstbestand veilig is om te delen.',
  [q('Is een CSV een factuur?',['Nee','Ja'],0,'Het is een bestand met transactiegegevens, geen verkoop- of inkoopfactuur.'),q('Kan een bank-CSV gevoelige informatie bevatten?',['Ja','Nee'],0,'Namen, rekeninggegevens en betalingen verdienen dezelfde bescherming als andere financiële gegevens.')],['ingcsv']);
 lesson('ING-CSV downloaden','Eerst bij ING zelf. Daarna Administratie → Bank en Kas → CSV importeren in APPFMZ.',
  'Je downloadt bij de bank transacties over een gekozen periode. ING kan namen en plekken van knoppen wijzigen. De officiële formatenpagina vermeldt CSV voor Mijn ING Zakelijk; een MT940-bestand is een ander formaat.',
  'Een volledige periode maakt het eenvoudiger om te zien of betalingen ontbreken. CSV downloaden is geen automatische bankkoppeling.',
  'Bijvoorbeeld iedere maand vóór je de rekening afstemt. De stappenlijst hieronder is een algemene route, geen inlogscherm.',
  'Vul je ING-wachtwoord nooit in APPFMZ in. Deze cursus opent geen ING-sessie, vraagt geen banktoegang en legt geen betaalde koppeling aan.',
  'Download 1 tot en met 30 september van de juiste zakelijke rekening. Controleer bij ING het aangeboden formaat en kies CSV, niet PDF of MT940.',
  'Zet de route in de juiste volgorde met de keuzestappen. Bekijk de volledige dertien stappen in het voorbeeld.',
  'Je weet waar het bestand vandaan komt en controleert het in APPFMZ vóór de echte import.',
  'In een zoekresultaat of nagebouwd inlogscherm je wachtwoord invullen. Een verkeerde rekening of overlappende periode ongecontroleerd importeren.',
  [q('Waar log je in bij ING?',['Alleen bij ING zelf','In de APPFMZ-oefening'],0,'APPFMZ heeft je ING-wachtwoord niet nodig.'),q('Waar controleer je de import vóór bevestigen?',['In het importvoorbeeld','Dat hoeft niet'],0,'Controleer rekening, data, bedragen en dubbele regels.')],['ingcsv','ingdownload','inglink']);
 lesson('CSV-import oefenen','De aparte oefenbank in deze cursus. In de echte app zit import onder Bank en Kas.',
  'Een importvoorbeeld toont wat het bestand zou toevoegen. Een duplicaat is een regel die dezelfde bankgebeurtenis voorstelt; die mag niet opnieuw meetellen.',
  'Je controleert de gegevens voordat ze in het overzicht komen. Herhaald importeren mag geen extra betaling opleveren.',
  'Kies uitsluitend het meegeleverde ING-achtige bestand, Oefenbank en september 2026. Controleer de kolommen en de dubbele regel.',
  'Upload hier geen echt bankbestand. De bestandscontrole accepteert uitsluitend de exacte vaste oefeninhoud en verstuurt niets. Een bestand kiezen is nog geen import.',
  '+€350 klantbetaling, −€24,20 uitgave, +€0,20 privé, −€100 privé, −€9,99 onbekend en de €350-regel nogmaals. Vijf unieke mutaties samen: +€216,01. Met opening €0,20 wordt de bank €216,21.',
  'Kies het oefenbestand, controleer rekening, kolommen en periode, bekijk de waarschuwing en bevestig lokaal. Probeer daarna dezelfde import nogmaals.',
  'Eerste import: vijf unieke transacties, duplicaat overgeslagen. Herhaling: nul nieuwe transacties. Geen upload.',
  'Alle regels aanvinken inclusief een duplicaat. Een ander rekeningnummer negeren. Al aanwezige betalingen nogmaals meetellen.',
  [q('Hoeveel verschillende transacties staan in het bestand?',['5','6'],0,'De zesde regel herhaalt de eerste transactie.'),q('Wat voegt dezelfde import opnieuw toe?',['Niets','Nog eens €350'],0,'Dezelfde bron-ID wordt maar één keer opgenomen.')],['ingcsv']);
 lesson('Transacties verwerken','Administratie → Bank en Kas → ongekoppelde transacties.',
  'Verwerken vertelt waarom geld binnenkomt of weggaat. Je kiest klantbetaling, zakelijke uitgave, privé in of uit, interne overboeking, onbekend of later beoordelen.',
  'Een bankbedrag op zichzelf vertelt niet welke boeking erbij hoort. Het openstaande werk moet zichtbaar blijven.',
  'Na de import: vergelijk voorstellen met facturen, bonnen en de werkelijke herkomst. Controleer twijfelgevallen zelf.',
  'Dwing een onbekende betaling niet in een willekeurige kostenpost om een waarschuwing kwijt te raken.',
  'De €350 past bij Noor, €24,20 bij de Oefenwinkelbon, €0,20 komt uit privé en €100 gaat naar privé. Voor €9,99 ontbreekt eerst de onderbouwing.',
  'Deel alle vijf regels in. Laat €9,99 Later beoordelen totdat het fictieve bewijs beschikbaar is.',
  'Vier verwerkte regels en één zichtbaar twijfelgeval. Een voorstel heeft niets vanzelf definitief gemaakt.',
  'Een ontvangst zowel aan een factuur koppelen als losse omzet boeken. Een interne verplaatsing tussen eigen rekeningen als nieuwe verkoop indelen.',
  [q('Is een automatisch voorstel bewijs?',['Nee','Ja'],0,'Je controleert het voorstel tegen de onderliggende gebeurtenis.'),q('Wat doe je zonder bewijs voor €9,99?',['Later beoordelen','Verzin een leverancier'],0,'Het openstaande punt blijft zichtbaar tot je voldoende informatie hebt.')]);
 lesson('Afstemmen','Administratie → Bank en Kas → Afstemmen bij de juiste rekening.',
  'Afstemmen is vergelijken: het berekende APPFMZ-banksaldo moet overeenkomen met het werkelijke ING-saldo op precies dezelfde einddatum. Het verandert niet vanzelf je bankgegevens.',
  'Een verschil helpt ontbrekende of dubbele transacties en een verkeerd openingssaldo ontdekken. Een verkeerde koppeling vraagt ook inhoudelijke controle, zelfs wanneer het banksaldo al klopt.',
  'Importeer eerst alle transacties tot de einddatum. Een praktische routine is maandelijks en vóór de kwartaalcontrole, niet na iedere losse transactie.',
  'Pas het saldo niet willekeurig aan om nul verschil te krijgen. Vergelijk niet het saldo van vandaag met een overzicht van vorige maand.',
  'Fictief ING-eindsaldo op 30 september: €216,21. Zonder de afschrijving van €9,99 berekent de app €226,20: een verschil van €9,99.',
  'Vergelijk het eindsaldo, zoek de ontbrekende regel, herstel de ontbrekende oefenmutatie en stem nogmaals af.',
  'Na de gerichte correctie: berekend €216,21, bank €216,21, verschil €0,00. De bronregel blijft controleerbaar.',
  'Een verschil wegboeken zonder oorzaak. De eerste of laatste dag van de periode overslaan. Denken dat nul verschil ook iedere btw-boeking goedkeurt.',
  [q('Moet je na iedere transactie afstemmen?',['Nee','Ja'],0,'Een regelmatige volledige periodecontrole is meestal duidelijker.'),q('Mag je een ontbrekende betaling oplossen met een verzonnen saldo?',['Nee','Ja'],0,'Zoek en herstel de oorzaak met het bankbewijs.')]);
 lesson('Verwijderen, annuleren en crediteren','Verkoopfacturen → concept verwijderen, geschikte factuur annuleren of credit maken. De app controleert de toegestane route.',
  'Een concept verwijderen ruimt een nog niet definitief document op. Annuleren is alleen voor een daarvoor geschikte definitieve, onbetaalde en niet verzonden factuur. Een creditfactuur is een afzonderlijk correctiedocument dat naar het origineel verwijst.',
  'Je bewaart wat er is gebeurd, inclusief reden en oorspronkelijke factuur. Een credit is geen stille wijziging van het origineel.',
  'Gebruik bij een verzonden, betaalde of verwerkte factuur de passende creditroute. Controleer de concrete situatie en fiscale verwerking. Bij twijfel laat je de correctie beoordelen.',
  'Verwijder geen definitieve facturen om een nummergat of fout onzichtbaar te maken. Een credit is niet hetzelfde als een daadwerkelijke terugbetaling.',
  'Een fout concept verdwijnt uit concepten. Een geschikte ongebruikte factuur wordt geannuleerd. Een volledige credit corrigeert de hele verkoop; een credit van €100 op €350 laat €250 verkoop inclusief btw over. Was €350 al betaald, dan kan €100 terug te betalen ontstaan.',
  'Oefen alle vier routes, vul een reden in en zoek het onveranderde origineel terug.',
  'Geannuleerd of volledig gecrediteerd telt niet als actieve openstaande verkoop. De gedeeltelijke correctie en eventuele terugbetaalverplichting blijven zichtbaar.',
  'De oorspronkelijke PDF overschrijven. Een credit als bankterugbetaling behandelen. Een geannuleerde factuur toch als openstaande omzet laten staan.',
  [q('Blijft het origineel bij een credit bewaard?',['Ja','Nee'],0,'Het creditdocument verwijst naar de oorspronkelijke factuur.'),q('Maakt een credit automatisch geld over?',['Nee','Ja'],0,'Een echte terugbetaling is een aparte bankgebeurtenis.')],['invoice','administration']);
 lesson('Bezittingen en schulden','Administratie → Bezittingen en schulden.',
  'Een zakelijk bezit is iets van waarde voor je onderneming. Een schuld is een verplichting aan iemand anders. Een bedrijfsmiddel gebruik je doorgaans langer, zoals apparatuur. Een lening brengt geld binnen én een terugbetaalverplichting mee.',
  'Niet iedere aankoop is onmiddellijk dezelfde soort kostenpost. Het overzicht laat zien wat je hebt en nog moet terugbetalen.',
  'Leg onderbouwde bezittingen en schulden vast en laat de juiste verwerking bepalen. Afschrijven betekent aanschafkosten over gebruiksjaren verdelen; de regels hangen van de situatie af.',
  'Boek een ontvangen lening niet als omzet. Kies niet zelf een afschrijvingstermijn of aftrek alleen omdat de oefening een apparaat noemt.',
  'Een fictief duurzaam trainingsapparaat is een mogelijk bedrijfsmiddel; papier is een gewone gebruiksuitgave. Een zakelijke lening van €1.000 verhoogt zowel bank als schuld.',
  'Deel de drie voorbeelden in en leg de fictieve lening vast zonder omzet te boeken.',
  'Bank +€1.000 en schuld +€1.000; geen €1.000 winst. Het apparaat blijft ter beoordeling van de passende verwerking.',
  'Alle aankopen meteen aftrekken. Aflossing en rente verwarren; die hebben verschillende betekenissen.',
  [q('Is een lening ontvangen omzet?',['Nee','Ja'],0,'Je moet het geleende bedrag terugbetalen.'),q('Bepaalt deze cursus jouw afschrijving?',['Nee','Ja'],0,'De oefening legt begrippen uit en neemt geen persoonlijke fiscale beslissing.')],['asset','costs']);
 lesson('Btw begrijpen','Administratie → Btw-overzicht. De bestaande bevestigde instellingen bepalen de berekening.',
  'Je kunt btw aan klanten berekenen en btw op zakelijke inkopen betalen. Alleen toegestane, aantoonbare inkoop-btw is voorbelasting. Uitgaande btw min aftrekbare voorbelasting geeft een voorlopig saldo: positief te betalen, negatief mogelijk terug te vragen.',
  'Ontvangen btw is niet volledig vrij besteedbaar. Btw is een andere belasting dan inkomstenbelasting en is geen winst.',
  'Controleer per passend tijdvak het gebruikte tarief, de onderbouwing en correcties. Bij factuurstelsel en kasstelsel kan het moment van omzet-btw verschillen; de inkoop-btw volgt de regels voor ontvangen facturen.',
  'Kies geen stelsel of tarief op basis van deze oefening. Een voorbereidend overzicht bewijst niet dat iedere transactie fiscaal juist is.',
  'Uitsluitend fictief factuurstelsel met 21%: €350 inclusief btw bevat €60,74 btw. De onderbouwde inkoop van €24,20 bevat €4,20 aftrekbare btw. Voorlopig saldo: €56,54.',
  'Vul verkoop-btw en toegestane voorbelasting in. Bekijk ook een scenario waarin de voorbelasting hoger is en een negatief saldo ontstaat.',
  'De vergelijking toont afzonderlijk verkoop-btw, inkoop-btw en het voorlopige verschil; geen definitieve persoonlijke belastingberekening.',
  'Omzet inclusief btw als winst gebruiken. Alle uitgaven-btw automatisch aftrekken. Aangiftemoment verwarren met betaaldatum zonder het juiste stelsel te controleren.',
  [q('Wat trek je af van de verkoop-btw?',['Alle bankuitgaven','Alleen toegestane voorbelasting'],1,'Niet ieder betaald bedrag of iedere inkoop-btw is aftrekbaar.'),q('Bewijst het overzicht dat je aangifte juist is?',['Nee','Ja'],0,'Je blijft de instellingen, onderbouwing en uitzonderingen controleren.')],['method','input']);
 lesson('Btw-kwartaal controleren','Administratie → Btw-overzicht; documenten en bankcontrole in de bijbehorende onderdelen.',
  'Een kwartaalcontrole brengt verkoop, correcties, inkopen en geldstromen voor één periode samen. Het is voorbereiding op de aangifte, geen automatische indiening.',
  'Ontbrekende bonnen, ongekoppelde transacties of een verkeerde periode kunnen het overzicht onvolledig maken.',
  'De meeste ondernemers doen per kwartaal aangifte, maar jouw brief en Mijn Belastingdienst Zakelijk bepalen het tijdvak en de deadline. Als een aangifte klaarstaat kan ook zonder omzet aangifte nodig zijn. Controleer bijzondere regelingen zoals KOR afzonderlijk.',
  'Klik een waarschuwing niet weg zonder de oorzaak te behandelen. APPFMZ dient niets in en verricht geen belastingbetaling.',
  'We controleren Q3 2026. Er is een onderbouwde uitgave van €24,20 en later komt een fictieve Webdienstbon van €9,99 binnen voor het onbekende bedrag. Beide zijn hier uitsluitend als toegestane 21%-rekensituatie ingericht. De periodecontrole eindigt zonder open oefenwaarschuwingen.',
  'Controleer verkoop en credits, bonnen, koppelingen, Bank, Kas en de btw-groepen. Los de onbekende transactie met het geleverde bewijs op en download het voorlopige oefenoverzicht.',
  'Je hebt een controleerbaar voorlopig overzicht. In het echt open je zelf de juiste aangifte bij Mijn Belastingdienst Zakelijk, controleer en vul je de bedragen in en dien je daar in. Betalen doe je afzonderlijk met het juiste betalingskenmerk.',
  'De PDF als ingediende aangifte beschouwen. Een willekeurig kwartaal kiezen. Vergeten dat nihil-aangifte of afzonderlijke betaling nodig kan zijn.',
  [q('Dient APPFMZ deze aangifte automatisch in?',['Nee','Ja'],0,'Het overzicht bereidt je eigen controle en indiening voor.'),q('Waar controleer je jouw tijdvak?',['Eigen brief en Mijn Belastingdienst Zakelijk','Altijd het oefenkwartaal gebruiken'],0,'Jouw officiële aangiftegegevens bepalen periode en uiterste datum.')],['period','nil','filing']);
 lesson('Winst en inkomstenbelasting','Administratie → Overzicht en Rapporten en export voor het bedrijfsresultaat. Je eigen inkomstenbelastingaangifte is afzonderlijk.',
  'Globaal is winst omzet zonder af te dragen btw minus zakelijke kosten. Voor een fiscale winstberekening kunnen aanvullende regels en correcties gelden. Privéstortingen zijn geen winst; privéopnames geen zakelijke kosten.',
  'Het bedrag op je bank is niet hetzelfde als inkomen dat je vrij kunt besteden. Je wilt je bedrijfsresultaat en verplichtingen apart begrijpen.',
  'Maak een jaaroverzicht voor je eigen controle en eventuele boekhouder. Ondernemingswinst en, als dat van toepassing is, loon kunnen beide in je jaarlijkse inkomstenbelastingaangifte horen.',
  'Bereken inkomstenbelasting niet per factuur en behandel een app-overzicht niet als een persoonlijke aanslag. Je status voor inkomstenbelasting kan verschillen van die voor btw.',
  'In de simpele oefensituatie is de nettoverkoop €289,26 en zijn kosten €20. Resultaat: €269,26. Een privéstorting of opname verandert deze rekensom niet.',
  'Bereken het administratieve resultaat en houd btw en privébewegingen buiten de omzet-kostenvergelijking.',
  'Een duidelijk administratief resultaat, zonder voorspelling van je persoonlijke belastingaanslag.',
  'Alle ontvangsten omzet noemen. Privéopname als aftrekbare kosten kiezen. Een btw-reservering voor een definitieve inkomstenbelastingberekening aanzien.',
  [q('Verandert een privéstorting de winst?',['Nee','Ja'],0,'Dat is een vermogensbeweging, geen verkoop.'),q('Is dit resultaat jouw definitieve belastingaanslag?',['Nee','Ja'],0,'De persoonlijke aangifte en fiscale regels vragen een afzonderlijke beoordeling.')],['income','private','costs']);
 lesson('Rapporten en export','Administratie → Rapporten en export. Factuur-PDF’s kun je ook bij de factuur opnieuw openen.',
  'Een rapport is een leesbaar overzicht; een export verzamelt gegevens voor bewaren of verdere controle. Een grootboek groepeert boekingen naar soort. Auditgeschiedenis laat zien welke vastgelegde handelingen bij de administratie horen.',
  'Je wilt informatie kunnen terugvinden, onderbouwen en veilig aan een boekhouder geven.',
  'Kies de juiste periode. De huidige app biedt verkoop-, uitgaven-, btw- en volledige overzichten. De volledige ZIP bevat ook bijbehorende gegevens zoals grootboek, openstaande posten, Bank/Kas en documentbestanden; niet ieder deel heeft een eigen losse knop.',
  'Een download is geen belastingaangifte of verzending naar een boekhouder. Deel echte exports uitsluitend gecontroleerd: ze bevatten financiële en klantinformatie.',
  'De oefen-ZIP bevat uitsluitend synthetische PDF’s, bonnen, CSV, grootboek, openstaande facturen, Bank/Kas en een als synthetisch gemarkeerde gebeurtenissenlijst.',
  'Kies de rapporttypen, bekijk het voorbeeld en download PDF en ZIP. Controleer de inhoudslijst en bewaar bronstukken apart waar nodig.',
  'Je weet welk bestand je kunt overhandigen en dat originele bewijsstukken en toegang tot de administratie behouden moeten blijven.',
  'Alleen een totaalscreenshot bewaren. Een ZIP aannemen als volledig zonder de inhoud te bekijken. Echte exports openbaar delen.',
  [q('Wat geef je voor een controle liever mee?',['Overzichten plus onderliggende bewijsstukken','Alleen een banksaldo'],0,'Een bedrag moet herleidbaar zijn tot de boeking en documenten.'),q('Verstuurt deze download een e-mail?',['Nee','Ja'],0,'De oefening maakt uitsluitend een lokaal bestand.')],['administration','retention']);
 lesson('Bewaren en back-up','Rapporten en export; daarna je eigen beveiligde bewaarlocatie buiten deze oefening.',
  'Een back-up is een extra kopie waarmee je gegevens kunt terugvinden als de eerste plek niet beschikbaar is. Digitaal ontvangen en gemaakte facturen bewaar je digitaal in de vereiste vorm.',
  'Je wilt documenten leesbaar en controleerbaar houden, ook na een apparaatwissel of wijziging van software. Algemene bewaartermijnen kennen uitzonderingen; controleer jouw situatie.',
  'Download periodiek een volledige export en controleer of bestanden werkelijk openen. Bewaar een tweede kopie op een beveiligde locatie met beperkte toegang. Bewaar bonnen en bankafschriften ook.',
  'Vertrouw niet op alleen een geopende tab. Deze cursus bewaart uitsluitend lesvoortgang en taakvinkjes; oefenadministratie verdwijnt bij sluiten of opnieuw laden. Er is geen herstelbelofte voor oefeninvoer.',
  'Je downloadt een synthetische ZIP, opent het overzicht en controleert de PDF. In het echt controleer je ook de bewaartermijn en beschikbaarheid van originele digitale documenten.',
  'Download de oefenback-up en vink aan dat je inhoud, leesbaarheid en een tweede beveiligde bewaarlocatie hebt begrepen.',
  'Een herkenbaar oefenbestand zonder echte gegevens. Je kent de afzonderlijke verantwoordelijkheid voor echte bewaring.',
  'Een back-up maken maar nooit openen. Alle kopieën op hetzelfde apparaat bewaren. Denken dat een cursusvinkje al een echte back-up heeft gemaakt.',
  [q('Bewaar je digitale facturen digitaal?',['Ja','Alleen een afdruk is altijd genoeg'],0,'Bewaar digitale facturen in de vereiste digitale vorm en controleer de actuele bewaarplicht.'),q('Blijven oefenbedragen na tabsluiting bewaard?',['Nee, alleen voortgang en taken','Ja, volledige administratie'],0,'De financiële oefenstate is tijdelijk en wordt nooit naar echte administratie gekopieerd.')],['retention','administration']);
 lesson('Vaste werkroutine','De cursusknop Mijn boekhoudtaken; de echte handelingen voer je zelf uit in de bijbehorende administratieonderdelen.',
  'Een routine verdeelt werk over week, maand, kwartaal en jaar. De lokale checklist is een geheugensteun en voert niets uit.',
  'Met kleine vaste controles voorkom je een stapel ontbrekende bonnen of onbekende transacties vlak voor je aangifte.',
  'Werk regelmatig bonnen en betalingen bij. Doe maandelijks een volledige bankcontrole, vóór aangifte een periodecontrole en jaarlijks een totaalcontrole.',
  'Een vinkje is geen bewijs dat een echte aangifte, betaling of back-up is uitgevoerd. Deze lijst controleert jouw echte administratie niet en geeft geen notificaties.',
  'Deze week: bonnen, onbekende posten, openstaande facturen en opslagmeldingen. Deze maand: import, koppelingen, privé, Bank/Kas en back-up. Kwartaal: onderbouwing, correcties, btw, aangifte en betaling. Jaar: volledige export, aansluitingen en gegevens voor inkomstenbelasting.',
  'Open alle vier lijsten, vink een voorbeeldtaak af en zet hem weer open. Kies daarna een routine die je zelf gaat volgen.',
  'Alleen checklistvinkjes worden lokaal onthouden. Je kunt ze afzonderlijk wissen en de lijsten opnieuw gebruiken.',
  'Blind alles afvinken. Dezelfde deadline voor iedereen aannemen. Denken dat APPFMZ de aangifte of betaling achter de schermen uitvoert.',
  [q('Voert een taakvinkje een betaling uit?',['Nee','Ja'],0,'De lijst is uitsluitend een lokale geheugensteun.'),q('Wanneer controleer je Bank/Kas in je routine?',['Regelmatig en vóór de kwartaalcontrole','Nooit als er geen foutmelding is'],0,'Ook zonder foutmelding wil je de aansluiting en onderbouwing zelf controleren.')],['filing','administration']);
 lesson('Afrondingstoets: jouw eerste oefenmaand','Volledig binnen deze afgeschermde oefenadministratie.',
  'Je brengt de losse lessen samen in twaalf handelingen, met dezelfde vaste voorbeeldgegevens. De toets gebruikt fictief factuurstelsel en 21% alleen als rekensituatie.',
  'Je controleert of je de volgorde begrijpt: gebeurtenis, document, betaling, controle en bewaring.',
  'Na de lessen of om te ontdekken welk onderwerp je nog wilt herhalen. De cursus is voltooid als alle 26 lessen én deze toets zijn afgerond.',
  'Gebruik geen echte namen, bankgegevens of documenten. De oefening kiest geen echte fiscale instellingen en verricht geen echte administratiehandelingen.',
  'Opening €0,20, aparte privéstorting €0,20, factuur €380 minus €30, ontvangst €350, uitgaven €24,20 en later €9,99, privéopname €100. Bank eindigt op €216,21. Een latere credit van €100 geeft bij de al betaalde factuur €100 terug te betalen; er is nog geen bankterugbetaling.',
  'Doorloop bank, privé, concept, controle, ontvangst, bon, CSV, onbekende transactie, afstemming, credit, btw en downloads. Verbeter een fout gerust en probeer opnieuw.',
  'Je kunt de gebeurtenissen verklaren. Geen dubbel geïmporteerde betaling, een sluitende oefenbank, bewaard origineel en een gecontroleerd voorlopig btw-overzicht.',
  'Een overgeslagen stap als voltooid zien. Een credit nogmaals als bankafschrijving invoeren terwijl die betaling niet heeft plaatsgevonden.',
  [q('Heeft deze toets iets in je echte administratie gewijzigd?',['Nee','Ja'],0,'Alle voorbeelden blijven in het afgeschermde tijdelijke geheugen.'),q('Wat controleer je vóór echte aangifte?',['Bronstukken, periode, koppelingen en fiscale instellingen','Alleen of de oefentoets groen is'],0,'De toets helpt je leren, maar bewijst niets over de inhoud van je echte administratie.')],['administration','method','input']);
 const glossary={
  omzet:'Opbrengst van verkopen, zonder de btw die je afdraagt. Een betaling van een bestaande factuur is geen tweede omzet.',winst:'Globaal: omzet min zakelijke kosten. De fiscale winst kan aanvullende correcties vragen.',btw:'Belasting op leveringen en diensten. Een andere belasting dan inkomstenbelasting.',voorbelasting:'Inkoop-btw die je volgens de regels mag aftrekken, met passende onderbouwing.',factuur:'Document met de uitgever, afnemer, levering, datum, nummer en bedragen.',creditfactuur:'Afzonderlijk correctiedocument dat naar een oorspronkelijke factuur verwijst.',debiteur:'Klant van wie je nog geld tegoed hebt.',uitgave:'Geld dat je betaalt. Dat is niet automatisch zakelijke kosten.',bon:'Bewijs van een aankoop; controleer of het voldoende informatie bevat voor jouw verwerking.',Bank:'Je zakelijke bankrekening zoals opgenomen in je administratie.',Kas:'Werkelijk zakelijk contant geld: munten en biljetten.',openingssaldo:'Saldo bij de start van je aansluiting. In APPFMZ: einde van de dag vóór de eerste transactiedag.',eindsaldo:'Saldo op het gekozen eindmoment, na alle transacties tot dat moment.',afstemmen:'Berekend saldo en werkelijk banksaldo op dezelfde datum vergelijken.',CSV:'Tekstbestand met regels en kolommen, bijvoorbeeld banktransacties.',privéstorting:'Eigen privégeld dat je in je eenmanszaak brengt; geen omzet.',privéopname:'Geld dat je uit je eenmanszaak naar privé haalt; geen zakelijke kosten.',grootboek:'Overzicht van boekingen gegroepeerd naar soort, bijvoorbeeld bank, omzet en kosten.',bezit:'Iets van waarde dat bij de onderneming hoort.',schuld:'Bedrag of verplichting die de onderneming aan een ander verschuldigd is.',openstaand:'Bedrag dat nog moet worden betaald of gekoppeld.',betaald:'De juiste ontvangst is volledig aan de factuur gekoppeld.',aangiftetijdvak:'De periode waarvoor jouw aangifte geldt, volgens de Belastingdienst.',betalingskenmerk:'De specifieke referentie waarmee een belastingbetaling bij de juiste verplichting hoort.',auditgeschiedenis:'Controleerbare geschiedenis van vastgelegde handelingen en correcties. De oefengeschiedenis is uitsluitend synthetisch.', 'back-up':'Extra beveiligde kopie die je op leesbaarheid en volledigheid controleert.', ontvangst:'Geld dat binnenkomt, bijvoorbeeld betaling, lening of privéstorting.',kosten:'Zakelijke lasten die bij het bedrijfsresultaat horen; niet iedere bankuitgave is kosten.',inkomstenbelasting:'Belasting op je persoonlijke jaarinkomen; geen aparte heffing per factuur.',factuurstelsel:'Btw-stelsel waarbij voor omzet-btw doorgaans de factuurdatum bepalend is; controleer de toepasselijke regels.',kasstelsel:'Btw-stelsel waarbij ontvangsten bepalend zijn voor omzet-btw; niet vrij te kiezen voor iedere situatie.',afschrijving:'Aanschafkosten van een bedrijfsmiddel over gebruiksjaren verdelen volgens de toepasselijke regels.',KOR:'Kleineondernemersregeling: een specifieke btw-regeling met voorwaarden. De cursus kiest deze niet voor jou.', vervaldatum:'Uiterste betaaldatum van de factuur.', 'interne overboeking':'Geld verplaatsen tussen eigen zakelijke rekeningen, bijvoorbeeld Kas naar Bank; geen nieuwe omzet.'
 };
 const tasks={week:['Nieuwe bonnen toevoegen','Onbekende transacties beoordelen','Openstaande facturen controleren','Mislukte opslagmeldingen oplossen'],month:['Banktransacties importeren','Betalingen koppelen','Uitgaven koppelen','Privémutaties controleren','Bank afstemmen','Kas controleren','Openstaande facturen bekijken','Back-up downloaden'],quarter:['Alle maanden controleren','Bank/Kas afstemmen','Ontbrekende bonnen oplossen','Creditfacturen controleren','Btw-overzicht bekijken','Waarschuwingen oplossen','PDF en ZIP bewaren','Eigen aangifte bij Mijn Belastingdienst Zakelijk controleren en indienen','Met het juiste betalingskenmerk betalen indien verschuldigd'],year:['Volledige administratie exporteren','Jaaroverzicht controleren','Begin- en eindsaldi aansluiten','Inkomsten en kosten controleren','Gegevens voor inkomstenbelasting of boekhouder verzamelen','Bewaartermijn en back-up controleren']};
 const ingSteps=['Open Mijn ING Zakelijk in een browser via ING zelf.','Log veilig bij ING in.','Open de juiste zakelijke betaalrekening.','Open Af- en bijschrijvingen of de aangeboden afschriftenroute.','Kies Downloaden of Exporteren.','Kies begin- en einddatum.','Kies het beschikbare CSV-formaat.','Bewaar het bestand op een herkenbare beveiligde plek.','Open APPFMZ.','Ga naar Administratie → Bank en Kas → CSV importeren.','Selecteer je bestand in de echte beveiligde administratie.','Controleer rekening, periode, bedragen, kolommen en duplicaten in het importvoorbeeld.','Bevestig de import pas na die controle.'];
 const fieldHelp=[
  ['Bedrijfsnaam','Eigen KVK-registratie','Identiteit op de factuur; controleer geregistreerde naam. Ontbrekend: niet definitief maken.','Bedrijfsnaam'],
  ['Handelsnaam','Eigen KVK-registratie','Een geregistreerde handelsnaam kan onder voorwaarden worden gebruikt; identiteit en adres moeten correct zijn.','Geen afzonderlijk veld; controleer Bedrijfsnaam'],
  ['Adres','Vestigingsregistratie','Volledig adres van de uitgever op de factuur. Ontbrekend: aanvullen.','Adres'],
  ['Postcode en plaats','Vestigingsregistratie','Onderdeel van het volledige adres; niet alleen een postbus invullen.','Postcode / plaats'],
  ['Land','Vestigingsregistratie','Maakt het adres duidelijk, zeker internationaal.','Land'],
  ['KVK-nummer','Handelsregister','Vermeld indien ingeschreven; bevestig de juiste registratie.','KVK en registratiecontrole'],
  ['Btw-identificatienummer','Eigen Belastingdienstbrief of portaal','Btw-identificatie op toepasselijke facturen; gebruik niet zomaar een ander fiscaal nummer.','Btw-nummer'],
  ['E-mailadres','Eigen zakelijke contactgegevens','Contactinformatie, geen algemene btw-factuureis. Ontbrekend: klant heeft deze contactroute niet.','E-mail'],
  ['Telefoonnummer','Eigen zakelijke contactgegevens','Optionele contactinformatie.','Telefoon'],
  ['Website','Eigen bedrijfswebsite','Optionele contactinformatie.','Website'],
  ['IBAN','Eigen bankomgeving','Betaalinstructie; controleer uiterst zorgvuldig. Geen automatische bankkoppeling.','IBAN'],
  ['BIC','Eigen bank, indien voor betaling nodig','Aanvullende bankidentificatie wanneer vereist; geen algemene btw-factuureis.','Geen afzonderlijk veld'],
  ['Rekeninghouder','Eigen bankgegevens','Naam bij de betaalrekening; controleer betaalinstructies.','Geen apart veld; controleer bedrijfs-/ownernaam en PDF'],
  ['Betaaltermijn','Afspraak met de klant','Afgesproken aantal dagen; bepaalt de vervaldatum. Geen willekeurig belastingtijdvak.','Betaaltermijn in dagen'],
  ['Factuurnummerreeks','Bestaande administratie','Unieke opeenvolgende nummering is nodig; nooit hergebruiken. APPFMZ beheert echte nummers server-side.','Geen instelveld; FMZ-jaar-volgnummer, geen handmatige reset'],
  ['Boekjaar','Eigen administratie en aangiftegegevens','Periode voor jaaroverzichten. Kies het relevante jaar in rapporten.','Geen apart instellingenveld; periodefilters'],
  ['Btw-periode','Eigen aangiftebrief / Mijn Belastingdienst Zakelijk','Controleer jouw tijdvak en deadline. Ontbrekend of onzeker: eerst uitzoeken.','Btw-periode'],
  ['Factuur- of kasstelsel','Eigen toepasselijke regels en fiscale beoordeling','Bepaalt het moment van omzet-btw. Niet kiezen op basis van de oefening.','Btw-stelsel']
 ];
 const help={overview:{title:'Overzicht',lesson:2,text:'Hier zie je berekende totalen en waarschuwingen. Open de bijbehorende boeking om de herkomst te controleren.',example:'Een betaling verlaagt openstaand, zonder een tweede verkoop.',refs:['administration']},sales:{title:'Verkoopfacturen',lesson:8,text:'Bewerk een concept, controleer de preview en maak pas daarna expliciet definitief.',example:'Progressie €380 min €30 korting geeft €350 te betalen.',refs:['invoice']},expenses:{title:'Uitgaven en bonnen',lesson:12,text:'Leg de zakelijke aankoop en het bewijs vast; koppel de betaling afzonderlijk.',example:'€24,20 met fictief toegestane 21% bevat €4,20 voorbelasting.',refs:['input']},bank:{title:'Bank en Kas',lesson:18,text:'Importeer transacties, controleer de koppelingen en vergelijk het saldo op dezelfde einddatum.',example:'€226,20 berekend tegenover €216,21 op de bank: zoek de ontbrekende €9,99.',refs:['ingcsv']},private:{title:'Privéstortingen en privéopnames',lesson:5,text:'Houd privégeld bij een eenmanszaak apart van omzet en zakelijke kosten.',example:'€0,20 uit privé is een privéstorting, geen klantverkoop.',refs:['private']},assets:{title:'Bezittingen en schulden',lesson:20,text:'Leg vast wat de onderneming heeft en nog moet terugbetalen. Laat fiscale verwerking onderbouwen.',example:'Een lening verhoogt bank én schuld, geen omzet.',refs:['asset']},vat:{title:'Btw-overzicht',lesson:21,text:'Controleer een voorlopig overzicht tegen instellingen, bewijs en jouw aangiftetijdvak.',example:'Verkoop-btw min toegestane voorbelasting geeft een voorlopig saldo.',refs:['method','filing']},reports:{title:'Rapporten en export',lesson:24,text:'Download periodeoverzichten en de volledige export; controleer de documenten en bewaar ze veilig.',example:'Een ZIP voor controle bevat gegevens én onderliggende bewijsstukken.',refs:['retention']},settings:{title:'Administratie-instellingen',lesson:3,text:'Controleer bedrijfsgegevens en fiscale instellingen tegen je eigen registraties en brieven.',example:'IBAN invullen maakt nog geen ING-koppeling.',refs:['invoice','inglink']}};
 const content={version,checked,disclaimer,sources,headings,lessons,glossary,tasks,ingSteps,fieldHelp,help};
 if(typeof module!=='undefined')module.exports=content;else root.FMZCourseContent=content;
})(typeof window==='undefined'?globalThis:window);
