/* Opaque-origin course: no credentials, network, persistent practice values or accounting API. */
(()=>{'use strict';
 const C=FMZCourseContent,M=FMZCourseModel,nonce=location.hash.slice(1),main=document.querySelector('#courseMain'),header=document.querySelector('#courseHeader');
 const send=(type,data={})=>parent.postMessage({channel:'fmz-course-v1',nonce,type,...data},'*');
 let progress={version:1,current:1,completed:[],last:0,tasks:[]},route='home',lessonId=1,states={},drafts={},flags={},answers={},quizResults={},initialized=false,progressError=false,mode='learn',viewer=null,renderToken=0,busy=false;
 const pdfCache=new Map(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const button=(label,action,extra='',cls='')=>`<button type="button" data-action="${action}" ${extra} class="${cls}">${esc(label)}</button>`;
 const icon=term=>button('ⓘ','term',`data-term="${esc(term)}" aria-label="Uitleg over ${esc(term)}"`,'info');
 const terms=Object.keys(C.glossary).sort((a,b)=>b.length-a.length),termRegex=new RegExp('\\b('+terms.map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')\\b','gi');
 const prose=text=>esc(text).replace(termRegex,term=>`${term}${icon(terms.find(t=>t.toLowerCase()===term.toLowerCase()))}`);
 const percent=()=>Math.round(progress.completed.length/27*100),current=()=>states[lessonId]||(states[lessonId]=M.state(lessonId));
 const key=()=>`${lessonId}:${current().step}`,getFlags=()=>flags[key()]||(flags[key()]={tour:[],reports:[]});
 function persist(){send('progress',{progress});renderHeader();}
 function renderHeader(){header.innerHTML=`<p class="safety">OEFENMODUS — deze gegevens zijn niet echt en veranderen je administratie niet.</p><div class="topbar"><button type="button" data-action="home" class="brand" aria-label="Naar cursusstart">FMZ <span>Academie</span></button><div class="progress"><label for="courseProgress">${percent()}% afgerond · ${progress.completed.length} van 27</label><progress id="courseProgress" value="${progress.completed.length}" max="27"></progress></div><button type="button" data-action="theme" aria-label="Wissel licht en donker thema">◐ Thema</button></div><nav class="course-nav" aria-label="Cursusonderdelen">${button('Lessen','topics')}${button('Begrippen','glossary')}${button('Mijn boekhoudtaken','tasks')}</nav><p id="progressNotice" role="status" class="progress-notice">${progressError?'Voortgang kon niet lokaal worden bewaard. Je kunt nu verder oefenen; na sluiten kan voortgang ontbreken.':'Alleen lesvoortgang en taakvinkjes blijven op dit apparaat; oefeninvoer verdwijnt bij sluiten.'}</p>`;}
 function go(next,id=lessonId){route=next;lessonId=id;if(route==='lesson'){progress.current=id;persist();}render();main.focus({preventScroll:true});scrollTo(0,0);}
 function sourceList(ids){return ids.length?`<aside class="sources"><strong>Officiële inhoudscontrole · ${C.checked}</strong><p>${C.disclaimer}</p><div class="actions">${ids.map(id=>button(C.sources[id][0],'source',`data-source="${id}"`,'text-button')).join('')}</div></aside>`:'';}
 function render(){renderHeader();if(route==='home')home();else if(route==='topics')topics();else if(route==='glossary')glossary();else if(route==='tasks')tasks();else lesson();}
 function home(){const last=C.lessons.find(l=>l.id===progress.last);main.innerHTML=`<section class="hero"><p class="eyebrow">APPFMZ · leren in je eigen tempo</p><h1>Je eerste boekhouding.<br><em>Stap voor stap.</em></h1><p>Leer wat je invult, waarom en hoe je controleert of het klopt. Oefen met vaste voorbeelden, volledig apart van je echte administratie.</p><p class="small">26 lessen + één afrondingstoets · versie ${C.version} · inhoud gecontroleerd ${C.checked}</p></section><div class="choice-grid"><button data-action="start" class="choice"><span>01 · Leren</span><strong>Beginnerscursus starten</strong><small>Begin bij de basis. Iedere les heeft uitleg, een oefening en twee vragen.</small></button><button data-action="topics" class="choice"><span>02 · Opzoeken</span><strong>Los onderwerp bekijken</strong><small>Ga direct naar facturen, bank, privé, btw of een ander onderwerp.</small></button><button data-action="practice" class="choice"><span>03 · Zelf doen</span><strong>Oefenen met voorbeeldgegevens</strong><small>Probeer de volledige oefenmaand of een losse handeling.</small></button></div><section class="card"><h2>Jouw voortgang</h2><p>${percent()}% afgerond. Laatst afgerond: ${last?`${last.id}. ${esc(last.title)}`:'nog geen les'}.</p><div class="actions">${button('Verder waar ik gebleven was','resume','','primary')}${button('Opnieuw beginnen','restart')}${button('Alle uitleg downloaden als PDF','manual')}${button('Naar mijn echte administratie','close')}</div><p class="small">Je hoeft niet alles in één keer te doen. Bij hervatten begint de oefening van die les opnieuw met de vaste voorbeelden.</p></section><section class="card muted"><h2>Veilig oefenen</h2><p>Er worden geen klanten, bankbestanden of financiële gegevens uit je echte administratie geladen. Er worden geen facturen verstuurd, echte nummers gereserveerd of uploads uitgevoerd. Geef ook zelf alleen de voorbeeldgegevens op.</p>${button('Oefenmodus volledig resetten','reset')}${sourceList(['administration'])}</section>`;}
 function topics(){main.innerHTML=`<p class="eyebrow">${mode==='practice'?'Zelf doen':'Kies je onderwerp'}</p><h1>Alle lessen</h1><p>Een vinkje verschijnt na de oefening én beide controlevragen. Overslaan kan altijd en telt niet als afgerond.</p><div class="lesson-list">${C.lessons.map(l=>`<button data-action="lesson" data-lesson="${l.id}" class="lesson-link"><span class="number">${progress.completed.includes(l.id)?'✓':l.id}</span><span><strong>${esc(l.title)}</strong><small>${l.id===27?'Twaalf handelingen in één oefenmaand':'Uitleg · zelf proberen · korte controle'}</small></span><span aria-hidden="true">→</span></button>`).join('')}</div>`;}
 function glossary(){main.innerHTML=`<h1>Begrippen in gewone taal</h1><label class="search">Zoek een begrip<input id="termSearch" type="search" placeholder="Bijvoorbeeld: privéstorting" autocomplete="off"></label><div id="terms">${glossaryRows('')}</div>${sourceList(['administration','private','method','input','income'])}`;}
 function glossaryRows(query){const entries=Object.entries(C.glossary).filter(([t,d])=>(t+' '+d).toLocaleLowerCase('nl').includes(query.toLocaleLowerCase('nl')));return entries.length?entries.map(([t,d])=>`<section class="definition"><h2>${esc(t)}</h2><p>${esc(d)}</p></section>`).join(''):'<p role="status">Geen begrip gevonden. Probeer een korter woord.</p>';}
 function tasks(){main.innerHTML=`<h1>Mijn boekhoudtaken</h1><p>Alleen een lokale geheugensteun. Een vinkje voert geen boeking, export, aangifte of betaling uit. Er worden geen herinneringen verstuurd.</p>${button('Terug naar mijn les','return-lesson')}<div class="task-grid">${Object.entries(C.tasks).map(([period,items])=>`<section class="card"><h2>${{week:'Iedere week / regelmatig',month:'Iedere maand',quarter:'Ieder kwartaal',year:'Ieder jaar'}[period]}</h2>${items.map((text,i)=>`<label class="check"><input type="checkbox" data-task="${period}-${i}" ${progress.tasks.includes(period+'-'+i)?'checked':''}>${esc(text)}</label>`).join('')}</section>`).join('')}</div>${button('Alle taakvinkjes wissen','clear-tasks')}${sourceList(['filing','retention'])}`;}
 function fieldMarkup(f,index){const value=drafts[key()]?.[f.key]??'',id=`field-${f.key}`;return `<label class="field" for="${id}"><span>${esc(f.label)}${lessonId===3?button('ⓘ','field-help',`data-field="${index}" aria-label="Waar vind ik ${esc(f.label)}?"`,'info'):''}</span>${f.type==='select'?`<select id="${id}" name="${f.key}" aria-describedby="hint-${f.key}"><option value="">Maak een keuze</option>${f.options.map(v=>`<option ${value===v?'selected':''}>${esc(v)}</option>`).join('')}</select>`:f.type==='checkbox'?`<input id="${id}" type="checkbox" name="${f.key}" ${value===true?'checked':''}>`:`<input id="${id}" name="${f.key}" type="${f.type==='date'?'date':'text'}" ${f.type==='money'?'inputmode="decimal"':''} autocomplete="off" maxlength="180" value="${esc(value)}" aria-describedby="hint-${f.key}">`}<small id="hint-${f.key}">${esc(f.hint)}</small></label>`;}
 function lesson(){const l=C.lessons[lessonId-1];main.innerHTML=`<div class="lesson-title"><p class="eyebrow">${lessonId===27?'Afrondingstoets':`Les ${lessonId} van 26`} · ${progress.completed.includes(lessonId)?'Afgerond':'Neem je tijd'}</p><h1>${esc(l.title)}</h1><div class="actions">${button('Naar de oefening','to-exercise','','primary')}${button('Alle uitleg in deze les tonen','explain')}</div></div><div class="reading">${l.sections.map((text,i)=>{if(i===6)return `<section id="exercise" class="exercise-section" tabindex="-1"><h2>7. Doe het nu zelf</h2><p>${prose(text)}</p><div id="practice"></div></section>`;if(i===9)return `<section class="card quiz"><h2>10. Korte controle</h2><form id="quizForm">${l.quiz.map((q,i)=>`<fieldset><legend>${esc(q.question)}</legend>${q.options.map((o,j)=>`<label class="check"><input type="radio" name="q${i}" value="${j}" ${answers[lessonId]?.[i]===j?'checked':''}>${esc(o)}</label>`).join('')}<p data-quiz-feedback="${i}"></p></fieldset>`).join('')}<button class="primary" type="button" data-action="check-quiz">Controleer mijn antwoorden</button><p id="lessonComplete" role="status"></p></form></section>`;return `<details class="explanation" ${i===0?'open':''}><summary>${i+1}. ${C.headings[i]}</summary><p>${prose(text)}</p>${i===5?extraExample():''}</details>`;}).join('')}</div>${sourceList(l.refs)}<footer class="lesson-controls"><div class="actions">${button('Vorige','previous',lessonId===1?'disabled':'')}${button('Volgende','next','','primary')}${button('Opnieuw uitleggen','explain')}${button('Oefening opnieuw doen','retry')}${button('Stap overslaan','skip')}${button('Stoppen en later verdergaan','close')}</div></footer>`;renderPractice();renderQuizFeedback();if(mode==='practice')document.querySelector('#exercise').scrollIntoView();}
 function extraExample(){if(lessonId===3)return `<div class="field-guide">${C.fieldHelp.map(r=>`<details><summary>${esc(r[0])}</summary><p>Bron: ${esc(r[1])}</p><p>${esc(r[2])}</p><p>In APPFMZ: ${esc(r[3])}</p></details>`).join('')}</div>`;if(lessonId===15)return `<ol>${C.ingSteps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`;if([14,16,17,18].includes(lessonId))return transactionTable(true);if(lessonId===26)return Object.entries(C.tasks).map(([k,items])=>`<h3>${{week:'Week',month:'Maand',quarter:'Kwartaal',year:'Jaar'}[k]}</h3><ul>${items.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`).join('');return '';}
 function transactionTable(duplicates=false){return `<div class="transaction-list" aria-label="Vaste synthetische transacties">${[...M.transactions,...(duplicates?[M.transactions[0]]:[])].map((t,i)=>`<div class="transaction"><span><strong>${esc(t.name)}</strong><small>${t.date} · ${t.id}${i===5?' · DUPLICAAT — overslaan':''}</small></span><strong>${M.money(t.cents)}</strong></div>`).join('')}</div>`;}
 function summaryHTML(){const s=current(),v=M.summary(s);if(lessonId===3&&s.settings)return '<h3>Gecontroleerde fictieve bedrijfskaart</h3><dl>'+M.plans[3][0].fields.map(f=>'<dt>'+esc(f.label)+'</dt><dd>'+esc(s.settings[f.key])+'</dd>').join('')+'</dl>';if([1,2,3,7,14,15,26].includes(lessonId))return '<p class="small">Alleen de voorbeeldhandeling van deze les wordt beoordeeld; er worden geen echte totalen geladen.</p>';if([4,5,6,13,16,18,20].includes(lessonId))return `<div class="summary-grid"><div><small>Openingssaldo</small><strong>${M.money(s.opening)}</strong></div><div><small>Berekende oefenbank</small><strong>${M.money(v.bank)}</strong></div><div><small>Kas ${s.cashHidden?'(verborgen)':''}</small><strong>${M.money(v.cash)}</strong></div><div><small>Oefentransacties</small><strong>${s.bank.length}</strong></div></div><p>${s.loan?'Oefenschuld: '+M.money(s.loan)+'. Geen omzet. ':''}${s.difference!==null?'Afstemmingsverschil: '+M.money(s.difference):'Geldbewegingen tellen niet automatisch als winst.'}</p>`;return `<div class="summary-grid"><div><small>Berekende oefenbank ${icon('Bank')}</small><strong>${M.money(v.bank)}</strong></div><div><small>Kas ${s.cashHidden?'(verborgen)':''} ${icon('Kas')}</small><strong>${M.money(v.cash)}</strong></div><div><small>Oefenfactuur · ${v.status}</small><strong>${M.money(s.issued?v.outstanding:v.total)} ${!s.issued?'conceptbedrag':v.outstanding<0?'terug te betalen':'open'}</strong></div><div><small>Nettoverkoop / kosten</small><strong>${M.money(v.net)} / ${M.money(v.cost)}</strong></div></div><div class="vat-equation"><span>Verkoop-btw <b>${M.money(v.vat)}</b></span><span>−</span><span>Toegestane voorbelasting <b>${M.money(v.input)}</b></span><span>=</span><span>Voorlopig ${v.vat-v.input<0?'terug te vragen':'te betalen'} <b>${M.money(v.vat-v.input)}</b></span></div><p class="small">Alleen fictieve 21%-rekensituatie. ${v.unknown} oefentransactie(s) nog onbekend / later beoordelen. ${s.difference!==null?`Laatste afstemmingsverschil: ${M.money(s.difference)}.`:''}</p><details><summary>Bekijk de oefengeschiedenis en koppelingen</summary><ul>${s.bank.map(t=>`<li>${esc(t.id)} · ${M.money(t.cents)} · ${esc(t.category)}</li>`).join('')}${s.allocations.map(a=>`<li>${esc(a.id)} → ${esc(s.issued?.number)} · ${M.money(a.cents)}</li>`).join('')}${s.events.map(e=>`<li>${esc(e.step)}${e.reason?' · '+esc(e.reason):''}</li>`).join('')}</ul></details>${s.credits.length?'<div class="actions">'+button('Oefencredit bekijken','credit-preview')+button('Oefencredit downloaden','credit-download')+'</div>':''}`;}
 function renderPractice(){const s=current(),p=M.plans[lessonId][s.step],el=document.querySelector('#practice');if(!el)return;if(!p){el.innerHTML=`<div class="success" role="status"><h3>Oefening doorlopen</h3><p>${esc(s.notice)}</p><p>Rond ook de korte controle af. Je kunt deze oefening gerust opnieuw doen.</p></div>${summaryHTML()}${button('Oefening opnieuw doen','retry')}`;return;}
  const f=getFlags();el.innerHTML=`<div class="practice-card"><p class="eyebrow">Handeling ${s.step+1} van ${M.plans[lessonId].length}</p><h3 tabindex="-1" id="practiceTitle">${esc(p.title)}</h3><p>${prose(p.guide)}</p>${s.notice?`<p class="success">${esc(s.notice)}</p>`:''}${p.tour?`<div class="tour-grid">${Object.entries(C.help).map(([id,h])=>button(`${f.tour.includes(id)?'✓ ':''}${h.title}`,'tour',`data-help="${id}"`)).join('')}</div>`:''}${p.tasks?button('Mijn boekhoudtaken openen','tasks'):''}${p.table||p.csv?transactionTable(true):''}${p.csv?`<div class="file-choice">${button('Meegeleverd oefenbestand kiezen','choose-csv')}${button('Oefen-CSV downloaden','csv-download')}<label>Of kies uitsluitend datzelfde oefenbestand<input type="file" id="csvFile" accept=".csv,text/csv"></label><p id="csvStatus" role="status">${f.csv?'Vast oefenbestand gekozen. Vijf unieke regels en één duplicaat.':'Nog geen oefenbestand gekozen.'}</p></div>`:''}${p.receipt?button('Synthetisch bewijs bekijken','receipt'):''}${p.reports?`<div class="actions">${['sales','expenses','vat','full'].map(id=>button({sales:'Verkoop',expenses:'Uitgaven',vat:'Btw',full:'Volledig overzicht'}[id]+' bekijken','report',`data-report="${id}"`)).join('')}</div>`:''}<form id="practiceForm" novalidate><div class="fields">${p.fields.map(fieldMarkup).join('')}</div>${p.key==='draft'?'<output id="invoiceCalculation" class="calculation" aria-live="polite">Vul bedrag en korting in om het totaal te zien.</output>':''}<div class="actions">${p.preview?button('A4-preview openen','preview'):''}${p.pdf||p.downloads?button('Oefen-PDF openen','open-pdf'):''}${p.pdf||p.downloads?button('Oefen-PDF downloaden','download-pdf'):''}${p.downloads?button('Volledige oefen-ZIP downloaden','download-zip'):''}</div>${p.downloads?'<p class="small">ZIP: oefenfactuur, synthetische bonnen, btw-/verkoop-/uitgaven-/volledig overzicht, transacties.csv, grootboek.csv, openstaand.csv, bank-kas.csv, synthetische-audit.json en LEESMIJ.txt.</p>':''}<p id="practiceFeedback" role="status" aria-live="polite"></p><button type="button" data-action="check-practice" class="primary">${p.action==='draft'?'Oefenconcept opslaan':p.action==='issue'?'Oefenfactuur definitief maken':p.action==='import'?'Voorbeeld bevestigen en lokaal importeren':'Handeling uitvoeren en controleren'}</button></form></div><div id="practiceSummary">${summaryHTML()}</div>`;updateCalculation();}
 function values(){const form=document.querySelector('#practiceForm');if(!form)return drafts[key()]||{};const out={};for(const e of form.elements)if(e.name)out[e.name]=e.type==='checkbox'?e.checked:e.value;return out;}
 function feedback(text,error=true){const el=document.querySelector('#practiceFeedback');if(el){el.textContent=text;el.className=error?'error':'success';}}
 function updateCalculation(){const el=document.querySelector('#invoiceCalculation');if(!el)return;try{const t=M.totals({...M.invoiceDefault,...values()});el.textContent=`Oorspronkelijk ${M.money(t.gross)} − korting ${M.money(t.discount)} = ${M.money(t.total)}. Fictief 21%: netto ${M.money(t.net)} + btw ${M.money(t.vat)}.`;}catch{el.textContent='Bedrag of korting nog niet volledig. De invoer blijft staan en wordt niet als nul opgeslagen.';}}
 function renderQuizFeedback(){const results=quizResults[lessonId];if(results)C.lessons[lessonId-1].quiz.forEach((q,i)=>{const el=document.querySelector(`[data-quiz-feedback="${i}"]`);el.textContent=(results[i]?'Goed gezien. ':'Bekijk dit nog eens. ')+q.feedback;el.className=results[i]?'success':'error';});const done=results?.every(Boolean)&&current().step===M.plans[lessonId].length;const el=document.querySelector('#lessonComplete');if(!el)return;if(done){if(!progress.completed.includes(lessonId)){progress.completed.push(lessonId);progress.completed.sort((a,b)=>a-b);progress.last=lessonId;persist();}el.textContent=progress.completed.length===27?'Je hebt de APPFMZ-beginnerscursus boekhouden afgerond.':'Les afgerond. Je kunt verder of rustig herhalen.';el.className='success';}else if(results?.every(Boolean))el.textContent='De antwoorden kloppen. Doorloop ook de oefening om de les af te ronden.';}
 function simpleDialog(title,html){const d=document.createElement('dialog');d.className='info-dialog';d.innerHTML=`<h2>${esc(title)}</h2>${html}<button type="button" data-dialog-close>Sluiten</button>`;d.querySelector('[data-dialog-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();return d;}
 async function bytes(report='invoice',liveValues){const s=current();let doc=M.document(s,liveValues);if(report==='credit'){const credit=s.credits[0];if(!credit)throw Error('Nog geen oefencredit beschikbaar.');const net=Math.round(credit.cents*100/121);doc={...doc,invoiceNo:credit.id,creditOf:credit.original,description:credit.reason,lines:[{description:credit.reason,quantity:1,unitCents:-credit.cents,amountCents:-credit.cents}],subtotalCents:-credit.cents,grossCents:-credit.cents,discountCents:0,discountInputCents:0,discountNote:'',totalCents:-credit.cents,netCents:-net,vatCents:-(credit.cents-net)};}const cacheKey=JSON.stringify([report,doc,report==='invoice'?null:M.summary(s)]);if(pdfCache.has(cacheKey))return pdfCache.get(cacheKey);let data;
  if(report==='invoice'||report==='credit')data=await FMZDocuments.pdf(doc);else{const out=await PDFLib.PDFDocument.create(),page=out.addPage([595.28,841.89]),font=await out.embedFont(PDFLib.StandardFonts.Helvetica),bold=await out.embedFont(PDFLib.StandardFonts.HelveticaBold);const text=(s,y,size=12,f=font)=>page.drawText(s,{x:44,y,size,font:f});text('APPFMZ - synthetisch '+({vat:'btw-overzicht',sales:'verkoopoverzicht',expenses:'uitgavenoverzicht',full:'administratieoverzicht',receipt:'bewijs'}[report]||report),775,16,bold);text('Periode: Q3 2026 | uitsluitend onderwijs',747);const v=M.summary(s),lines=report==='receipt'?['OEF-BON-1 | Oefenwinkel | 03-09-2026','Materiaal: EUR 24,20 | netto 20,00 | fictieve btw 4,20','OEF-BON-2 | Webdienst | 05-09-2026','Dienst: EUR 9,99 | netto 8,26 | fictieve btw 1,73','Geen echt aankoopbewijs.']:['Oefenbank: '+M.money(v.bank),'Kas: '+M.money(v.cash),'Nettoverkoop: '+M.money(v.net),'Zakelijke kosten in dit scenario: '+M.money(v.cost),'Openstaand / terug te betalen: '+M.money(v.outstanding),'Btw aan klanten: '+M.money(v.vat),'Toegestane voorbelasting: '+M.money(v.input),'Voorlopig btw-saldo: '+M.money(v.vat-v.input),'Geen aangifte ingediend. Geen betaling uitgevoerd.'];lines.forEach((l,i)=>text(l.replace(/\u00a0/g,' '),700-i*27));text('Fictief factuurstelsel en 21%; geen fiscale keuze voor de owner.',355,10);text('Dit is algemene uitleg en geen persoonlijk fiscaal advies.',332,10);data=await out.save();}
  const out=await PDFLib.PDFDocument.load(data),font=await out.embedFont(PDFLib.StandardFonts.HelveticaBold);for(const p of out.getPages()){p.drawText('OEFENFACTUUR — NIET GELDIG',{x:54,y:390,size:23,font,color:PDFLib.rgb(.62,.15,.13),opacity:.22,rotate:PDFLib.degrees(25)});p.drawText('OEFENFACTUUR — NIET GELDIG',{x:140,y:18,size:12,font,color:PDFLib.rgb(.62,.15,.13)});}const saved=await out.save();pdfCache.set(cacheKey,saved);return saved;
 }
 function download(data,type,name){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
 async function showPDF(data,practiceFlags){viewer?.close();let pdfTask=null,scale=1;const d=document.createElement('dialog');viewer=d;d.className='pdf-dialog';d.innerHTML=`<p class="safety">OEFENMODUS — deze gegevens zijn niet echt en veranderen je administratie niet.</p><header><strong>Oefen-PDF · A4</strong><div>${button('−','zoom-out','aria-label="Uitzoomen"')}${button('+','zoom-in','aria-label="Inzoomen"')}${button('Sluiten','viewer-close')}</div></header><p role="status">PDF laden…</p><div class="pdf-pages"></div>`;document.body.append(d);d.showModal();practiceFlags.open=true;
  async function paint(){const token=++renderToken,container=d.querySelector('.pdf-pages');container.replaceChildren();const pdf=await pdfTask.promise;for(let i=1;i<=pdf.numPages;i++){if(token!==renderToken||!d.open)return;const page=await pdf.getPage(i),base=page.getViewport({scale:1}),fit=Math.min(1.25,(d.clientWidth-30)/base.width),vp=page.getViewport({scale:fit*scale}),canvas=document.createElement('canvas');canvas.setAttribute('aria-label',`Oefen-PDF pagina ${i} van ${pdf.numPages}`);canvas.width=Math.ceil(vp.width*devicePixelRatio);canvas.height=Math.ceil(vp.height*devicePixelRatio);canvas.style.width=vp.width+'px';canvas.style.height=vp.height+'px';container.append(canvas);await page.render({canvasContext:canvas.getContext('2d'),viewport:vp,transform:[devicePixelRatio,0,0,devicePixelRatio,0,0]}).promise;}d.querySelector('[role=status]').textContent=`${pdf.numPages} A4-pagina(’s) · zoom ${Math.round(scale*100)}%. Schuif binnen de viewer bij inzoomen.`;}
  d.addEventListener('close',()=>{practiceFlags.close=true;renderToken++;pdfTask?.destroy();d.remove();viewer=null;});d.addEventListener('click',async e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='viewer-close')d.close();if(a==='zoom-in'||a==='zoom-out'){scale=Math.max(.7,Math.min(3,scale+(a==='zoom-in'?.25:-.25)));practiceFlags.zoom=true;try{await paint();}catch{if(d.open)d.querySelector('[role=status]').textContent='Voorbeeld kon niet worden getekend. Sluit en probeer opnieuw.';}}});
  try{pdfTask=pdfjsLib.getDocument({data:data.slice(),useSystemFonts:true,isEvalSupported:false});await paint();}catch(error){d.querySelector('[role=status]').textContent='PDF openen lukte niet. Sluit en probeer opnieuw; er wordt geen nieuwe factuur gemaakt.';practiceFlags.open=false;throw error;}
 }
 async function zip(){const s=current(),out={};for(const [name,type] of [['oefenfactuur','invoice'],['synthetische-bonnen','receipt'],['btw-overzicht','vat'],['verkoopoverzicht','sales'],['uitgavenoverzicht','expenses'],['volledig-overzicht','full']])out[name+'.pdf']=await bytes(type);if(s.credits.length)out['oefencredit.pdf']=await bytes('credit');const str=fflate.strToU8,v=M.summary(s);out['transacties.csv']=str(M.csv);out['grootboek.csv']=str(`Soort;Centen\nNettoverkoop;${v.net}\nKosten;${v.cost}\nBtw-verkoop;${v.vat}\nVoorbelasting;${v.input}\n`);out['openstaand.csv']=str(`Oefenfactuur;Openstaand centen;Status\n${s.issued?.number||'OEFENCONCEPT'};${v.outstanding};${v.status}\n`);out['bank-kas.csv']=str(`Rekening;Saldo centen\nOefenbank;${v.bank}\nOefenkas;${v.cash}\n`);out['synthetische-audit.json']=str(JSON.stringify({synthetic:true,events:s.events},null,2));out['LEESMIJ.txt']=str('UITSLUITEND SYNTHETISCH OEFENMATERIAAL. Geen echte boekhouding, aangifte, betaling of auditexport. Alle PDF’s zijn ongeldig als factuur. Cursus '+C.version+'.');return fflate.zipSync(out);}
 document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing&&e.target.matches('input:not([type=checkbox]):not([type=radio])')&&e.target.closest('#practiceForm')){e.preventDefault();e.target.closest('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));}});
 document.addEventListener('input',e=>{if(e.target.id==='termSearch'){document.querySelector('#terms').innerHTML=glossaryRows(e.target.value);return;}if(e.target.closest('#practiceForm')){drafts[key()]=values();getFlags().preview=false;updateCalculation();}});
 document.addEventListener('change',async e=>{if(e.target.dataset.task){const id=e.target.dataset.task;progress.tasks=progress.tasks.filter(t=>t!==id);if(e.target.checked)progress.tasks.push(id);const f=getFlags();if(e.target.checked)f.taskOn=true;else if(f.taskOn)f.tasks=true;persist();return;}if(e.target.id==='csvFile'){const file=e.target.files[0],el=document.querySelector('#csvStatus');getFlags().csv=false;try{if(!file||file.size>4096||await file.text()!==M.csv)throw Error();getFlags().csv=true;el.textContent='Exact het vaste oefenbestand herkend; vijf unieke transacties en één duplicaat. Geen upload.';}catch{el.textContent='Dit is niet het vaste oefenbestand. Het bestand is niet geïmporteerd of verstuurd. Kies de meegeleverde voorbeeldgegevens.';}e.target.value='';return;}if(e.target.closest('#practiceForm'))drafts[key()]=values();});
 document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='practiceForm'){if(busy)return;try{const f=getFlags();states[lessonId]=M.apply(current(),values(),{...f,tour:f.tour.length});renderPractice();renderQuizFeedback();document.querySelector('#practiceTitle')?.focus({preventScroll:true});document.querySelector('#practice').scrollIntoView({block:'start'});}catch(error){feedback(error.message);}}if(e.target.id==='quizForm'){answers[lessonId]=C.lessons[lessonId-1].quiz.map((q,i)=>{const val=new FormData(e.target).get('q'+i);return val===null?-1:Number(val);});quizResults[lessonId]=answers[lessonId].map((a,i)=>a===C.lessons[lessonId-1].quiz[i].correct);renderQuizFeedback();}});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.closest('.pdf-dialog'))return;const a=b.dataset.action;if(busy)return;
  if(a==='check-practice'||a==='check-quiz'){b.closest('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));return;}
  if(['home','topics','glossary','tasks'].includes(a)){go(a);return;}if(a==='lesson'){go('lesson',Number(b.dataset.lesson));return;}if(a==='start'){mode='learn';go('lesson',1);return;}if(a==='practice'){mode='practice';go('topics');return;}if(a==='resume'||a==='return-lesson'){go('lesson',progress.current);return;}if(a==='close'){send('close');return;}if(a==='manual'){send('manual');return;}if(a==='source'){send('source',{source:b.dataset.source});return;}if(a==='theme'){document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark';return;}if(a==='term'){simpleDialog(b.dataset.term,`<p>${esc(C.glossary[b.dataset.term])}</p>`);return;}if(a==='field-help'){const r=C.fieldHelp[Number(b.dataset.field)];simpleDialog(r[0],`<p>Waar vinden: ${esc(r[1])}</p><p>${esc(r[2])}</p><p>In APPFMZ: ${esc(r[3])}</p>`);return;}if(a==='tour'){const h=C.help[b.dataset.help],f=getFlags();if(!f.tour.includes(b.dataset.help))f.tour.push(b.dataset.help);simpleDialog(h.title,`<p>${esc(h.text)}</p><p>Voorbeeld: ${esc(h.example)}</p><p>Automatisch: berekeningen uit bestaande boekingen. Zelf controleren: brongegevens, bewijs en passende koppelingen.</p>`);b.textContent='✓ '+h.title;return;}
  if(a==='next'||a==='skip'){go(lessonId===27?'home':'lesson',Math.min(27,lessonId+1));return;}if(a==='previous'){go('lesson',Math.max(1,lessonId-1));return;}if(a==='explain'){document.querySelectorAll('.explanation').forEach(d=>d.open=true);main.focus();scrollTo(0,0);return;}if(a==='to-exercise'){document.querySelector('#exercise').focus();document.querySelector('#exercise').scrollIntoView();return;}
  if(a==='retry'){states[lessonId]=M.state(lessonId);for(const k of Object.keys(flags))if(k.startsWith(lessonId+':'))delete flags[k];for(const k of Object.keys(drafts))if(k.startsWith(lessonId+':'))delete drafts[k];delete quizResults[lessonId];delete answers[lessonId];pdfCache.clear();lesson();return;}
  if(a==='reset'||a==='restart'){simpleDialog(a==='reset'?'Oefenmodus volledig resetten':'Opnieuw beginnen',`<p>Alle tijdelijke voorbeelden, cursusvoortgang en lokale taakvinkjes worden gewist. Je echte administratie wordt niet geraakt.</p>${button('Ja, opnieuw beginnen','confirm-reset')}`);return;}
  if(a==='confirm-reset'){document.querySelectorAll('dialog').forEach(d=>d.close());states={};drafts={};flags={};answers={};quizResults={};pdfCache.clear();progress={version:1,current:1,last:0,completed:[],tasks:[]};persist();go('home',1);return;}
  if(a==='clear-tasks'){progress.tasks=[];persist();tasks();return;}if(a==='choose-csv'){getFlags().csv=true;document.querySelector('#csvStatus').textContent='Vast oefenbestand gekozen: vijf unieke transacties en één duplicaat. Geen upload.';return;}if(a==='csv-download'){download(M.csv,'text/csv;charset=utf-8','APPFMZ-OEFENBANK-september-2026.csv');return;}
  const p=M.plans[lessonId][current().step],f=getFlags();try{busy=true;b.disabled=true;feedback('Bestand wordt lokaal voorbereid…',false);
   if(a==='preview'){const data=await bytes('invoice',p?.key==='draft'?values():undefined);await showPDF(data,f);f.preview=true;}
   else if(a==='credit-preview')await showPDF(await bytes('credit'),f);
   else if(a==='credit-download'){download(await bytes('credit'),'application/pdf','APPFMZ-OEFENCREDIT-NIET-GELDIG.pdf');}
   else if(a==='receipt')await showPDF(await bytes('receipt'),f);
   else if(a==='report')await showPDF(await bytes(b.dataset.report),f);
   else if(a==='open-pdf')await showPDF(await bytes(p?.report||'invoice'),f);
   else if(a==='download-pdf'){download(await bytes(p?.report||'invoice'),'application/pdf','APPFMZ-OEFENFACTUUR-NIET-GELDIG.pdf');f.pdf=true;feedback('Oefen-PDF voor download aangeboden. Controleer het bestand bij je downloads.',false);}
   else if(a==='download-zip'){download(await zip(),'application/zip','APPFMZ-OEFENADMINISTRATIE.zip');f.zip=true;feedback('Oefen-ZIP voor download aangeboden. Er is niets verstuurd.',false);}
  }catch(error){feedback('Dat lukte niet. '+error.message+' Je oefeninvoer blijft in dit venster behouden. Probeer dezelfde handeling opnieuw.');}finally{busy=false;b.disabled=false;}
 });
 addEventListener('message',e=>{if(e.source!==parent||e.data?.channel!=='fmz-course-v1'||e.data.nonce!==nonce)return;if(e.data.type==='init'&&!initialized){initialized=true;progress=e.data.progress;document.body.dataset.theme=e.data.theme==='dark'?'dark':'light';render();if(e.data.lesson)go('lesson',e.data.lesson);}if(e.data.type==='save-error'){progressError=true;renderHeader();}if(e.data.type==='saved'&&progressError){progressError=false;renderHeader();}});
 send('ready');
})();
