/* Deterministic in-memory exercises. No browser, network, storage or real accounting API. */
(function(root){
 const clone=v=>JSON.parse(JSON.stringify(v));
 const money=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(n/100);
 function cents(v){const s=String(v??'').trim().replace(',','.');if(!/^-?\d+(\.\d{1,2})?$/.test(s))throw Error('Vul een bedrag in met maximaal twee decimalen. Een leeg bedrag is geen nul.');const [a,b='']=s.replace('-','').split('.'),n=(Number(a)*100+Number(b.padEnd(2,'0')))*(s.startsWith('-')?-1:1);if(!Number.isSafeInteger(n)||Math.abs(n)>10000000)throw Error('Gebruik het bedrag uit het oefenvoorbeeld.');return n;}
 const transactions=[{id:'OEF-T1',date:'2026-09-02',cents:35000,name:'Noor Voorbeeld',description:'OEFEN-2026-001'},{id:'OEF-T2',date:'2026-09-03',cents:-2420,name:'Oefenwinkel',description:'Oefenmateriaal'},{id:'OEF-T3',date:'2026-09-03',cents:20,name:'Privé voorbeeld',description:'Eigen inbreng'},{id:'OEF-T4',date:'2026-09-04',cents:-10000,name:'Privé voorbeeld',description:'Privéopname'},{id:'OEF-T5',date:'2026-09-05',cents:-999,name:'Onbekend voorbeeld',description:'Nog beoordelen'}];
 const csv='Datum;Naam / Omschrijving;Rekening;Af Bij;Bedrag (EUR);Transactie ID\r\n'+[...transactions,transactions[0]].map(t=>`${t.date};${t.name};OEFENBANK;${t.cents<0?'Af':'Bij'};${(Math.abs(t.cents)/100).toFixed(2).replace('.',',')};${t.id}`).join('\r\n')+'\r\n';
 const invoiceDefault={client:'Noor Voorbeeld',package:'Progressie',date:'2026-09-01',due:'2026-09-15',period:'september 2026',description:'Progressie - 8 trainingen september 2026',amount:'380,00',discount:'30,00',discountNote:'Oefenkorting',status:'draft'};
 function totals(inv=invoiceDefault){const gross=cents(inv.amount),discount=cents(inv.discount);if(gross<=0)throw Error('Het factuurbedrag moet groter zijn dan nul.');if(discount<0||discount>gross)throw Error('Korting moet tussen nul en het factuurbedrag liggen.');const total=gross-discount,net=Math.round(total*100/121);return {gross,discount,total,net,vat:total-net};}
 function state(id){const s={lesson:id,step:0,opening:20,firstDate:'2026-09-01',bank:[],cash:0,cashHidden:false,invoice:clone(invoiceDefault),issued:null,allocations:[],expenses:[],credits:[],cancelled:[],deleted:[],events:[],completedSteps:[],views:[],downloads:[],notice:'',difference:null,loan:0};
  if([10,11,17,18,19,21,22,23,24,25].includes(id))s.issued={...clone(invoiceDefault),number:'OEFEN-2026-001',status:'posted'};
  if([17,22,24,25].includes(id))transactions.forEach(t=>addBank(s,t.id));
  if(id===19){addBank(s,'OEF-T1');s.bank[0].category='klantbetaling';s.allocations.push({id:'OEF-T1',cents:35000});}
  if(id===18)transactions.slice(0,4).forEach(t=>addBank(s,t.id));
  if([21,22,23,24,25].includes(id))s.expenses.push({id:'OEF-E1',gross:2420,net:2000,vat:420,receipt:'OEF-BON-1'});
  return s;
 }
 function addBank(s,id){if(s.bank.some(t=>t.id===id))return false;const t=transactions.find(t=>t.id===id);if(!t)throw Error('Onbekende oefentransactie.');s.bank.push({...t,category:'onbekend'});return true;}
 function allocate(s,id,amount){if(!s.issued)throw Error('Controleer eerst de oefenfactuur.');if(s.allocations.some(a=>a.id===id))return false;const outstanding=totals(s.issued).total-s.allocations.reduce((n,a)=>n+a.cents,0);if(amount>outstanding||amount<=0)throw Error('Deze koppeling is hoger dan het openstaande bedrag.');s.allocations.push({id,cents:amount});return true;}
 function summary(s){const inv=s.issued||s.invoice,t=totals(inv),credit=s.credits.reduce((n,c)=>n+c.cents,0),creditNet=Math.round(credit*100/121),creditVat=credit-creditNet,paid=s.allocations.reduce((n,a)=>n+a.cents,0),cost=s.expenses.reduce((n,e)=>n+e.net,0),input=s.expenses.reduce((n,e)=>n+e.vat,0),active=s.issued&&!s.cancelled.includes(s.issued.number),out=active?t.total-credit-paid:0;return {bank:s.opening+s.bank.reduce((n,b)=>n+b.cents,0),cash:s.cash,total:t.total,net:active?t.net-creditNet:0,vat:active?t.vat-creditVat:0,input,cost,profit:(active?t.net-creditNet:0)-cost,outstanding:out,status:!s.issued?'Concept':!active?'Geannuleerd':credit===t.total?'Gecrediteerd':out<0?'Terug te betalen':out===0?'Betaald':paid?'Gedeeltelijk betaald':'Openstaand',unknown:s.bank.filter(t=>['onbekend','later'].includes(t.category)).length};}
 const select=(key,label,options,answer,hint)=>({key,label,type:'select',options,answer,hint:hint||'Kies wat bij de beschreven gebeurtenis hoort.'});
 const input=(key,label,answer,hint,type='text')=>({key,label,type,answer:String(answer),hint:hint||`Gebruik in deze oefening: ${answer}.`});
 const amount=(key,label,answer,hint)=>input(key,label,answer,hint,'money');
 const check=(key,label)=>({key,label,type:'checkbox',answer:true,hint:'Controleer het genoemde onderdeel voordat je verdergaat.'});
 const options=['klantbetaling','zakelijke uitgave','privéstorting','privéopname','interne overboeking','onbekend','later'];
 const step=(key,title,guide,fields=[],action='none',extra={})=>({key,title,guide,fields,action,...extra});
 const bank=step('bank','Oefenbank instellen','Neem het saldo van het einde van 31 augustus over. De eerste transacties horen bij 1 september.',[select('account','Rekening',['Oefenbank','Oefenkas'],'Oefenbank'),input('date','Eerste transactiedag','2026-09-01',null,'date'),amount('opening','Openingssaldo (€)','0,20')],'bank');
 const privateIn=step('private-in','€0,20 uit privé verwerken','De bank toont een nieuwe ontvangst op 3 september uit eigen privégeld. Kies de juiste boeking.',[select('category','Soort ontvangst',['omzet','klantbetaling','privéstorting','lening','onbekend'],'privéstorting')],'private-in');
 const invoiceFields=[select('client','Klant',['Noor Voorbeeld','Sam Andere Oefenklant'],'Noor Voorbeeld'),select('package','Pakket',['Basis','Progressie','Transformatie'],'Progressie'),input('date','Factuurdatum','2026-09-01',null,'date'),input('due','Vervaldatum','2026-09-15','14 dagen na de factuurdatum.', 'date'),input('period','Factuurperiode','september 2026'),input('description','Omschrijving','Progressie - 8 trainingen september 2026'),amount('amount','Bedrag inclusief btw (€)','380,00'),amount('discount','Korting (€)','30,00'),input('discountNote','Toelichting korting','Oefenkorting')];
 const draft=step('draft','Een concept van €350 maken','Kies Noor en één maand Progressie. Vul de septemberdata en €30 korting in. Open de A4-preview vóór concept opslaan.',invoiceFields,'draft',{preview:true});
 const issue=step('issue','Controleer en maak de oefenfactuur definitief','Bekijk de A4-preview. Alleen deze bevestiging maakt het voorbeeld definitief; typen doet dat nooit.',[check('review','Ik heb klant, data, regels, korting en €350 gecontroleerd')],'issue',{preview:true});
 const payment=step('payment','Ontvangst van €350 koppelen','Transactie OEF-T1: Noor Voorbeeld, 2 september 2026, €350. Controleer de gegevens tegen de factuur.',[select('payer','Betaler',['Noor Voorbeeld','Sam Andere Oefenklant'],'Noor Voorbeeld'),input('date','Betaaldatum','2026-09-02',null,'date'),amount('amount','Ontvangen bedrag (€)','350,00'),select('target','Koppel aan',['OEFEN-2026-001','Nieuwe losse omzet','Later beoordelen'],'OEFEN-2026-001')],'payment');
 const expense=step('expense','Uitgave met synthetische bon','Oefenwinkel: materiaal gekocht op 3 september. Fictief volledig zakelijk, aftrek toegestaan en 21% uitsluitend als rekensituatie.',[input('supplier','Leverancier','Oefenwinkel'),input('date','Bondatum','2026-09-03',null,'date'),input('description','Omschrijving','Oefenmateriaal'),select('category','Categorie',['Materiaal','Privé'],'Materiaal'),amount('amount','Totaal inclusief btw (€)','24,20'),select('vat','Btw-behandeling',['21% - fictief toegestaan','Onbekend','Privé'],'21% - fictief toegestaan'),select('method','Betaalwijze',['Oefenbank','Kas'],'Oefenbank'),select('transaction','Banktransactie',['OEF-T2 - €24,20','OEF-T4 - €100'],'OEF-T2 - €24,20'),select('receipt','Bewijs',['Synthetische bon OEF-BON-1','Bon ontbreekt'],'Synthetische bon OEF-BON-1')],'expense',{receipt:true});
 const csvStep=step('csv','Voorbeeld controleren en importeren','Kies het vaste bestand. De zes regels bevatten vijf unieke transacties. Al eerder verwerkte bron-ID’s worden ook overgeslagen.',[select('account','Rekening',['Oefenbank','Oefenkas'],'Oefenbank'),select('dateColumn','Datumkolom',['Datum','Bedrag (EUR)'],'Datum'),select('amountColumn','Bedragkolom',['Naam / Omschrijving','Bedrag (EUR)'],'Bedrag (EUR)'),input('from','Vanaf','2026-09-01',null,'date'),input('to','Tot en met','2026-09-30',null,'date'),check('duplicate','Ik begrijp dat de herhaalde OEF-T1 niet nogmaals wordt geboekt')],'import',{csv:true});
 const unknown=step('unknown','Onbekende €9,99 onderzoeken','Nieuw bewijs: een fictieve Webdienstbon OEF-BON-2 voor €9,99 op 5 september, volledig zakelijk en in deze rekensituatie 21% aftrekbaar. Controleer bewijs vóór indelen.',[select('category','Verwerking',options,'zakelijke uitgave'),select('proof','Onderbouwing',['OEF-BON-2 - Webdienst €9,99','Geen bewijs'],'OEF-BON-2 - Webdienst €9,99')],'unknown',{receipt:true});
 const reconcile=step('reconcile','Bank op dezelfde einddatum afstemmen','Fictief bankafschrift: 30 september 2026, eindsaldo €216,21. Vergelijk met de berekende bank; de onbekende categorie verandert het bankbedrag niet.',[input('date','Einddatum','2026-09-30',null,'date'),amount('balance','Werkelijk eindsaldo (€)','216,21')],'reconcile');
 const credit=step('credit','Gedeeltelijke credit maken','Corrigeer €100 van de al betaalde oefenfactuur. Bewaar het origineel en de reden. Er vindt geen bankterugbetaling plaats.',[select('original','Oorspronkelijke factuur',['OEFEN-2026-001','Nieuw concept'],'OEFEN-2026-001'),amount('amount','Creditbedrag inclusief btw (€)','100,00'),input('reason','Reden','Een deel van het oefenpakket vervalt')],'credit');
 const vat=step('vat','Btw-periode en waarschuwingen controleren','Controleer het fictieve kwartaal met factuurstelsel en 21%: verkoop, correcties, bonnen, koppelingen en Bank/Kas. De berekende vergelijking staat onder de oefening.',[select('period','Tijdvak',['2026-Q3','2026-Q2'],'2026-Q3'),check('sales','Verkoop, annuleringen en credits gecontroleerd'),check('receipts','Onderbouwing en voorbelasting gecontroleerd'),check('bank','Bank en open transacties gecontroleerd'),check('cash','Kas gecontroleerd of niet in gebruik'),check('rates','Btw per tarief en waarschuwingen gecontroleerd')],'vat');
 const downloads=step('downloads','PDF en volledige ZIP bewaren','Open en zoom de oefen-PDF. Download vervolgens PDF én ZIP met uitsluitend synthetische gegevens. Dit verstuurt niets.',[check('contents','Ik heb de inhoudslijst van PDF’s, bonnen, CSV, grootboek, Bank/Kas en oefengeschiedenis gecontroleerd')],'downloads',{downloads:true});
 const plans={
  1:[step('events','Verkoop en betaling uit elkaar houden','Een factuur van €200 wordt later betaald; daarnaast komt €0,20 uit privé.',[select('invoice','Factuur €200',['Verkoopfactuur','Bankontvangst'],'Verkoopfactuur'),select('payment','Latere ontvangst €200',['Tweede verkoop','Betaling bestaande factuur'],'Betaling bestaande factuur'),select('private','Ontvangst uit privé €0,20',['Omzet','Privéstorting'],'Privéstorting')])],
  2:[step('tour','Verken alle negen onderdelen','Open eerst de negen korte voorbeeldkaarten. Plaats daarna de drie taken.',[select('receipt','Een bon invoeren',['Uitgaven en bonnen','Verkoopfacturen'],'Uitgaven en bonnen'),select('bank','Een betaling koppelen',['Bank en Kas','Btw-overzicht'],'Bank en Kas'),select('export','Een ZIP downloaden',['Rapporten en export','Kas'],'Rapporten en export')],'tour',{tour:true})],
  3:[step('settings','Fictieve bedrijfskaart controleren','Gebruik de hieronder getoonde vaste voorbeelden. Ook begrippen zonder eigen echt instelveld kun je hier veilig oefenen. Bekijk per veld de informatieknop.',[
    input('business','Bedrijfsnaam','FitMetZorge Oefenbedrijf'),input('trade','Handelsnaam (uitlegveld)','FMZ Voorbeeld'),input('address','Adres','Voorbeeldstraat 10'),input('postal','Postcode en plaats','1000 AA Voorbeeldstad'),input('country','Land','Nederland'),input('kvk','KVK-nummer (fictief)','00000000'),input('vatId','Btw-id (fictief)','NL000000000B00'),input('email','E-mail','oefenbedrijf@example.test'),input('phone','Telefoon','000-0000000'),input('website','Website','https://example.test'),input('iban','Rekening (geen echte IBAN)','OEFENBANK'),input('bic','BIC (uitlegveld)','OEFENBIC'),input('holder','Rekeninghouder (uitlegveld)','FitMetZorge Oefenbedrijf'),input('term','Betaaltermijn in dagen','14'),input('sequence','Nummerreeks (alleen oefenuitleg)','OEFEN-2026-001'),input('year','Boekjaar (uitlegveld)','2026'),select('period','Btw-periode fictief',['Kwartaal','Maand'],'Kwartaal'),select('method','Vooraf gekozen oefenstelsel',['Factuurstelsel - alleen voorbeeld','Kies echte instelling'],'Factuurstelsel - alleen voorbeeld')],'settings')],
  4:[bank],5:[privateIn],
  6:[step('hide-cash','Route A — geen contant geld','Verberg Kas zonder bestaande oefengeschiedenis te wissen.',[select('cash','Gebruik',['Ik gebruik geen contant geld','Alles verwijderen'],'Ik gebruik geen contant geld')],'hide-cash'),step('cash-receipt','Route B — klant betaalt €50 contant','Kas wordt voor deze tweede route weer getoond. De ontvangst hoort bij één bestaande verkoop van €50.',[select('type','Boeking',['Contante klantbetaling','Bankbetaling'],'Contante klantbetaling'),amount('amount','Contant ontvangen (€)','50,00')],'cash-receipt'),step('cash-bank','€50 van Kas naar Bank verplaatsen','Je stort het ontvangen geld op de zakelijke rekening.',[select('type','Boeking',['Interne overboeking','Nieuwe omzet'],'Interne overboeking'),amount('amount','Bedrag (€)','50,00')],'cash-bank')],
  7:[step('prices','Controleer alle maandprijzen','Aantal 1 betekent één maand, niet één training.',[amount('basis','Basis · 4 trainingen (€)','200'),amount('progress','Progressie · 8 trainingen (€)','380'),amount('transform','Transformatie · 12 trainingen (€)','480'),amount('discounted','Progressie na €30 korting (€)','350')],'prices')],
  8:[draft],9:[issue,step('pdf','PDF opnieuw bekijken en downloaden','Open de A4, zoom in en uit, sluit de viewer en download dezelfde oefenfactuur.',[],'pdf',{pdf:true})],
  10:[step('unmatched','Ontvangst importeren zonder koppeling','Voeg OEF-T1 toe en controleer dat de factuur nog openstaat.',[select('status','Status zonder koppeling',['Openstaand €350','Betaald'],'Openstaand €350')],'unmatched'),payment],
  11:[payment,step('partial-start','Nieuwe variant — eerste deelbetaling','Deze variant begint opnieuw met dezelfde €350-factuur. Oefenbetaling DEEL-1 is €100.',[amount('amount','Deelbetaling (€)','100'),amount('remaining','Daarna nog open (€)','250')],'partial-start'),step('partial-end','Tweede deelbetaling','DEEL-2: €250 van dezelfde betaler; de omschrijving wijkt af. Controleer de aanvullende oefenbevestiging van Noor.',[check('payer','Aanvullend bewijs bevestigt Noor en dezelfde factuur'),amount('amount','Tweede deelbetaling (€)','250'),amount('remaining','Daarna nog open (€)','0')],'partial-end'),step('no-match','Betaling zonder passende factuur','Een onbekende betaler past bij geen enkele factuur. Houd de ontvangst zichtbaar voor onderzoek.',[select('action','Verwerking',['Nieuwe omzet zonder bewijs','Later beoordelen'],'Later beoordelen')],'no-match'),step('duplicate-payment','Dezelfde ontvangst opnieuw','Probeer OEF-T1 nogmaals toe te voegen. Een herhaling is geen nieuwe betaling.',[select('count','Aantal extra transacties',['0','1'],'0')],'duplicate-payment')],
  12:[expense,step('missing-receipt','Variant — bon ontbreekt','Je hebt voor een andere uitgave nog geen bewijs.',[select('choice','Volgende handeling',['Bon opvragen en ter beoordeling laten','Btw direct aftrekken'],'Bon opvragen en ter beoordeling laten')])],
  13:[step('private-out','€100 naar privé verwerken','OEF-T4: privéoverboeking op 4 september.',[select('category','Soort afschrijving',['privéopname','salaris','zakelijke uitgave'],'privéopname')],'private-out')],
  14:[step('csv-meaning','Lees het voorbeeldbestand','Bekijk eerst de tabel met de zes regels.',[select('date','Datumkolom',['Datum','Af Bij'],'Datum'),select('amount','Bedragkolom',['Bedrag (EUR)','Rekening'],'Bedrag (EUR)'),select('file','Bestandstype',['CSV met transacties','Factuur-PDF'],'CSV met transacties')],'none',{table:true})],
  15:[step('ing-route','Oefen de veilige downloadroute','Zet de vier hoofdhandelingen op volgorde. De volledige dertien stappen staan onder de uitleg.',[select('first','1. Inloggen',['Bij ING zelf','In APPFMZ'],'Bij ING zelf'),select('second','2. Downloadkeuze',['Juiste rekening, periode en CSV','Willekeurige PDF'],'Juiste rekening, periode en CSV'),select('third','3. In APPFMZ',['Bank en Kas → CSV importeren','Nieuwe factuur'],'Bank en Kas → CSV importeren'),select('fourth','4. Vóór bevestiging',['Importvoorbeeld controleren','Bankwachtwoord invullen'],'Importvoorbeeld controleren')])],
  16:[csvStep,step('reimport','Import herhalen','Importeer dezelfde vaste zes regels nogmaals.',[amount('new','Aantal nieuwe transacties','0')],'reimport',{table:true})],
  17:[step('classify','Alle vijf transacties indelen','Kies voor de €9,99 nog Later beoordelen. Het bewijs is in deze stap nog niet bekend.',transactions.map((t,i)=>select(t.id,`${t.name} · ${money(t.cents)}`,options,['klantbetaling','zakelijke uitgave','privéstorting','privéopname','later'][i])),'classify',{table:true})],
  18:[step('difference','Eerst het verschil zichtbaar maken','De bank is €216,21, maar de afschrijving van €9,99 ontbreekt nog in de oefenadministratie.',[input('date','Vergelijkingsdatum','2026-09-30',null,'date'),amount('balance','Werkelijk saldo (€)','216,21')],'difference'),step('repair','Zoek de ontbrekende transactie','Vergelijk het vaste afschrift met de vier aanwezige regels.',[select('missing','Ontbrekende regel',['OEF-T5 - €9,99 af','OEF-T1 - €350 bij'],'OEF-T5 - €9,99 af')],'repair',{table:true}),reconcile],
  19:[step('delete-draft','Concept verwijderen','OEF-CONCEPT is nog niet definitief.',[select('route','Correctie',['Concept verwijderen','Origineel overschrijven'],'Concept verwijderen')],'delete-draft'),step('cancel','Geschikte oefenfactuur annuleren','Variant OEF-ANNUL: onbetaald, niet verzonden en nog niet verder verwerkt. Reden blijft bewaard.',[input('reason','Reden','Dubbel concept per ongeluk definitief gemaakt')],'cancel'),step('full-credit','Volledige credit oefenen','Variant OEF-VOLLEDIG is verzonden. Maak een afzonderlijke credit van €350 met verwijzing; het origineel blijft zichtbaar.',[amount('amount','Creditbedrag (€)','350'),input('reason','Reden','Volledig oefenpakket vervalt')],'full-credit'),credit,step('find-original','Oorspronkelijke factuur terugvinden','De correctie bevat een verwijzing; open het onveranderde oefenorigineel.',[select('original','Origineel',['OEFEN-2026-001','Origineel verwijderd'],'OEFEN-2026-001')],'none',{preview:true})],
  20:[step('assets','Deel bezit, uitgave en lening in','Kies de betekenis; de oefening berekent geen afschrijving.',[select('machine','Duurzaam trainingsapparaat',['Mogelijk bedrijfsmiddel, verwerking beoordelen','Altijd meteen volledig aftrekbaar'],'Mogelijk bedrijfsmiddel, verwerking beoordelen'),select('paper','Verbruikspapier',['Gewone gebruiksuitgave','Ontvangen lening'],'Gewone gebruiksuitgave'),select('loan','€1.000 lening ontvangen',['Bank plus schuld','Omzet'],'Bank plus schuld')],'loan')],
  21:[step('vat-calc','Bereken het voorlopige btw-saldo','Gebruik €60,74 verkoop-btw en €4,20 toegestane voorbelasting.',[amount('output','Verkoop-btw (€)','60,74'),amount('input','Toegestane voorbelasting (€)','4,20'),amount('balance','Voorlopig te betalen (€)','56,54')],'none'),step('vat-refund','Variant — voorbelasting is hoger','Stel verkoop-btw €10 en toegestane voorbelasting €20. Een negatief saldo is mogelijk terug te vragen.',[amount('balance','Voorlopig saldo (€)','-10')])],
  22:[step('quarter-links','Periode en koppelingen nalopen','De voorbeeldbank is geïmporteerd. Verbind de bekende ontvangsten, uitgave en privémutaties; laat €9,99 nog open.',[select('period','Periode',['2026-Q3','2026-Q2'],'2026-Q3'),check('docs','Facturen, annuleringen, credits en bonnen vergeleken')],'quarter-links'),unknown,reconcile,vat,step('vat-pdf','Voorlopig btw-overzicht downloaden','Bewaar het als oefenoverzicht; er wordt geen aangifte ingediend.',[],'pdf',{pdf:true,report:'vat'})],
  23:[step('profit','Bereken het eenvoudige resultaat','Nettoverkoop €289,26 minus €20 zakelijke kosten. Privébewegingen horen niet in deze som.',[amount('profit','Resultaat (€)','269,26'),select('private','Privéopname verlaagt dit resultaat?',['Nee','Ja'],'Nee')])],
  24:[step('reports','Kies het passende overzicht','Bekijk het aanbod aan synthetische rapporten. De volledige ZIP bevat alle hieronder genoemde onderdelen.',[select('sales','Facturen terugvinden',['Verkoopoverzicht / factuur-PDF','Alleen banksaldo'],'Verkoopoverzicht / factuur-PDF'),select('ledger','Grootboek en openstaande posten',['Volledige export','Btw-aangifte automatisch indienen'],'Volledige export')],'none',{reports:true}),downloads],
  25:[downloads,step('backup-check','Back-up controleren','De download bevat alleen oefenmateriaal. Bij echte bestanden controleer je ook bewaring en beveiligde toegang.',[check('read','Ik weet dat ik de bestanden op leesbaarheid moet controleren'),check('second','Ik weet dat een tweede beveiligde locatie nodig is'),check('retention','Ik controleer de toepasselijke bewaartermijn')])],
  26:[step('routine','Vier werklijsten gebruiken','Open Mijn boekhoudtaken, vink een voorbeeldtaak aan en weer uit. Kom daarna terug naar deze les.',[select('weekly','Bonnen en onbekende posten',['Regelmatig bijwerken','Alleen jaarlijks'],'Regelmatig bijwerken'),select('monthly','Bankcontrole',['Maandelijks en vóór kwartaalcontrole','Na iedere toetsaanslag'],'Maandelijks en vóór kwartaalcontrole'),select('filing','Aangifte en betaling',['Zelf apart controleren en uitvoeren','Door een taakvinkje automatisch'],'Zelf apart controleren en uitvoeren')],'routine',{tasks:true})],
  27:[bank,privateIn,draft,issue,payment,expense,csvStep,unknown,reconcile,credit,vat,downloads]
 };
 function validateField(f,value){if(f.type==='checkbox')return value===true;if(f.type==='money'){return cents(value)===cents(f.answer);}if(f.key==='description'||f.key==='discountNote'||f.key==='reason')return typeof value==='string'&&value.trim().length>=4&&value.length<=180;return String(value??'').trim()===String(f.answer);}
 function apply(s,values,flags={}){
  const p=plans[s.lesson]?.[s.step];if(!p)throw Error('Deze oefening is al afgerond.');
  for(const f of p.fields){if(!validateField(f,values[f.key]))throw Error(`${f.label}: bekijk het voorbeeld en probeer opnieuw. ${f.hint}`);}
  if(p.preview&&!flags.preview)throw Error('Open en controleer eerst de A4-preview van deze stap.');
  if(p.csv&&!flags.csv)throw Error('Kies eerst het meegeleverde oefenbestand en bekijk de tabel.');
  if(p.tour&&flags.tour!==9)throw Error('Open eerst alle negen voorbeeldonderdelen.');
  if(p.tasks&&!flags.tasks)throw Error('Open eerst Mijn boekhoudtaken en probeer een vinkje aan en uit.');
  if(p.pdf&&!(flags.open&&flags.zoom&&flags.close&&flags.pdf))throw Error('Open de PDF, probeer zoom, sluit de viewer en download de PDF.');
  if(p.downloads&&!(flags.pdf&&flags.zip))throw Error('Download eerst de oefen-PDF en de volledige oefen-ZIP.');
  const n=clone(s),mark=(id,category)=>{addBank(n,id);n.bank.find(t=>t.id===id).category=category;};
  n.notice='Goed gecontroleerd. Deze handeling is alleen in het tijdelijke oefengeheugen verwerkt.';
  switch(p.action){
   case 'bank':n.opening=cents(values.opening);n.firstDate=values.date;break;
   case 'private-in':mark('OEF-T3','privéstorting');break;
   case 'private-out':mark('OEF-T4','privéopname');break;
   case 'draft':n.invoice={...n.invoice,...values,status:'draft'};totals(n.invoice);n.notice='Oefenconcept bewaard in dit venster. Nog niet definitief; geen nummer gereserveerd.';break;
   case 'issue':if(!n.issued)n.issued={...n.invoice,number:'OEFEN-2026-001',status:'posted'};n.notice='Eén definitieve oefenfactuur. Het originele document blijft in deze sessie beschikbaar.';break;
   case 'unmatched':addBank(n,'OEF-T1');break;
   case 'payment':mark('OEF-T1','klantbetaling');allocate(n,'OEF-T1',35000);break;
   case 'partial-start':n.allocations=[];allocate(n,'DEEL-1',10000);n.notice='Variant: €100 gekoppeld; €250 blijft open. De voorbeeldbank blijft apart van deze deelbetalingsvariant.';break;
   case 'partial-end':allocate(n,'DEEL-2',25000);break;
   case 'no-match':n.notice='Onbekende variantontvangst blijft Later beoordelen. Er is geen willekeurige factuur gekoppeld.';break;
   case 'duplicate-payment':if(addBank(n,'OEF-T1'))throw Error('De oorspronkelijke ontvangst ontbreekt in de oefening.');n.notice='Duplicaat herkend: nul nieuwe banktransacties en nul extra koppelingen.';break;
   case 'expense':mark('OEF-T2','zakelijke uitgave');if(!n.expenses.some(e=>e.id==='OEF-E1'))n.expenses.push({id:'OEF-E1',gross:2420,net:2000,vat:420,receipt:'OEF-BON-1',supplier:values.supplier,date:values.date});break;
   case 'import':case 'reimport':{let count=0;for(const t of [...transactions,transactions[0]])if(addBank(n,t.id))count++;n.notice=`${count} nieuwe oefentransacties. ${6-count} al aanwezige of dubbele regels overgeslagen. Geen upload.`;break;}
   case 'classify':for(const t of n.bank)t.category=values[t.id];allocate(n,'OEF-T1',35000);if(!n.expenses.length)n.expenses.push({id:'OEF-E1',gross:2420,net:2000,vat:420,receipt:'OEF-BON-1'});break;
   case 'unknown':mark('OEF-T5','zakelijke uitgave');if(!n.expenses.some(e=>e.id==='OEF-E2'))n.expenses.push({id:'OEF-E2',gross:999,net:826,vat:173,receipt:'OEF-BON-2'});for(const [id,category] of [['OEF-T3','privéstorting'],['OEF-T4','privéopname']])mark(id,category);break;
   case 'difference':n.difference=summary(n).bank-cents(values.balance);n.notice=`Verschil ${money(n.difference)}. Zoek de ontbrekende afschrijving; verander het echte eindsaldo niet.`;break;
   case 'repair':addBank(n,'OEF-T5');n.notice='Ontbrekende OEF-T5 toegevoegd. Vergelijk nu opnieuw met hetzelfde eindsaldo.';break;
   case 'reconcile':n.difference=summary(n).bank-cents(values.balance);if(n.difference!==0)throw Error(`Er blijft ${money(n.difference)} verschil. Controleer de ontbrekende of dubbele oefentransacties.`);n.reconciledDate=values.date;n.notice='Afgestemd op 30 september: verschil €0,00. Dit bewijst de bankaansluiting, niet automatisch fiscale juistheid.';break;
   case 'credit':if(!n.issued)throw Error('Er is nog geen definitief oefenorigineel.');if(!n.credits.length)n.credits.push({id:'OEF-CREDIT-1',original:n.issued.number,cents:cents(values.amount),reason:values.reason});n.notice='Credit €100 vastgelegd. Het origineel is ongewijzigd. Bij volledige eerdere betaling is €100 terug te betalen; de bank is nog niet veranderd.';break;
   case 'delete-draft':n.deleted.push('OEF-CONCEPT');n.notice='Alleen OEF-CONCEPT verwijderd. Definitieve facturen blijven bewaard.';break;
   case 'cancel':n.cancelled.push('OEF-ANNUL');n.notice='Variant OEF-ANNUL geannuleerd: actief openstaand €0 en actieve verkoop €0. Reden en oorspronkelijke factuur blijven in de oefengeschiedenis.';break;
   case 'full-credit':n.notice='Variant OEF-VOLLEDIG: oorspronkelijke €350 en credit −€350. Actieve verkoop €0, openstaand €0; beide documenten blijven bewaard.';n.fullCredit={original:'OEF-VOLLEDIG',total:35000,credit:-35000,active:0,reason:values.reason};break;
   case 'hide-cash':n.cashHidden=true;n.notice='Kas verborgen. Bestaande geschiedenis is niet verwijderd.';break;
   case 'cash-receipt':n.cashHidden=false;n.cash=5000;n.notice='Kas €50. Eén contante klantbetaling van een bestaande verkoop; geen tweede factuur.';break;
   case 'cash-bank':n.cash-=5000;n.bank.push({id:'OEF-KAS-BANK',date:'2026-09-06',cents:5000,name:'Eigen Kas',category:'interne overboeking'});n.notice='Kas €0; Bank €50 hoger. Verkoop blijft gelijk.';break;
   case 'loan':n.loan=100000;n.bank.push({id:'OEF-LENING',date:'2026-09-01',cents:100000,name:'Oefenlening',category:'lening'});break;
   case 'quarter-links':allocate(n,'OEF-T1',35000);for(const [id,category] of [['OEF-T1','klantbetaling'],['OEF-T2','zakelijke uitgave'],['OEF-T3','privéstorting'],['OEF-T4','privéopname']])mark(id,category);break;
   case 'vat':if(summary(n).unknown)throw Error('Er staan nog ongekoppelde oefentransacties. Los de onderbouwing en koppelingen eerst op.');if(!n.reconciledDate)throw Error('Stem eerst de oefenbank af.');break;
   case 'settings':n.settings=clone(values);n.notice='Alleen de fictieve bedrijfskaart gecontroleerd. Uitlegvelden worden geen echte app-instellingen.';break;
  }
  n.events.push({step:p.key,action:p.action,synthetic:true,...(values.reason?{reason:values.reason}:{})});n.completedSteps.push(p.key);n.step++;return n;
 }
 function document(s,liveValues){const inv=liveValues?{...s.invoice,...liveValues}:s.issued||s.invoice,t=totals(inv);return {invoiceNo:s.issued&&!liveValues?s.issued.number:'OEFENCONCEPT',date:inv.date,dueDate:inv.due,period:inv.period,description:inv.description,quantity:1,lines:[{description:inv.description,quantity:1,unitCents:t.gross,amountCents:t.gross}],subtotalCents:t.gross,grossCents:t.gross,discountCents:t.discount,discountInputCents:t.discount,discountMode:'amount',discountNote:inv.discountNote,netCents:t.net,vatCents:t.vat,totalCents:t.total,vatBasisPoints:2100,vatStatus:'normal',vatMethod:'invoice',priceMode:'inclusive',customer:{name:inv.client,address:'Oefenlaan 2',postalCity:'1000 BB Voorbeeldstad',country:'Nederland',email:'noor@example.test'},settings:{businessName:'FitMetZorge Oefenbedrijf',ownerName:'Oefenowner',address:'Voorbeeldstraat 10',postalCity:'1000 AA Voorbeeldstad',country:'Nederland',email:'oefenbedrijf@example.test',iban:'OEFENBANK - GEEN ECHTE REKENING',note:'Uitsluitend leermateriaal. Niets betalen.'}};}
 const model={money,cents,totals,transactions,csv,state,summary,plans,apply,document,invoiceDefault,clone};
 if(typeof module!=='undefined')module.exports=model;else root.FMZCourseModel=model;
})(typeof window==='undefined'?globalThis:window);
