/* Owner-only UI. No finance data, document bytes or drafts are persisted in browser storage. */
window.FMZAccounting=(()=>{
 const M=FMZAccountingModel,esc=s=>escapeHTML(String(s??'')),copy=x=>JSON.parse(JSON.stringify(x)),uid=()=>crypto.randomUUID(),today=()=>todayISO();
 const menus=[['overview','Overzicht'],['sales','Verkoopfacturen'],['expenses','Uitgaven en bonnen'],['bank','Bank en kas'],['private','Privéstortingen en privéopnames'],['assets','Bezittingen en schulden'],['vat','Btw-overzicht'],['reports','Rapporten en export'],['settings','Administratie-instellingen']];
 let owner=null,epoch=0,access=null,snapshot=null,loading=null,page='overview',revision=0,rendered='',pending=null,commandBusy=false,error='',modal=null,invoice=null,invoiceTimer=null,formBusy=false;
 const formDrafts=new Map(),invoiceDrafts=new Map(),urls=new Set();let importData=null;
 let salesFilter='all';let periodType='month',periodValue=new Date().toISOString().slice(0,7);
 const list=k=>snapshot?.records.filter(r=>r.kind===k)||[],get=id=>snapshot?.records.find(r=>r.id===id),accountOpts=()=>list('account').filter(r=>!r.data.hidden).map(r=>[r.id,r.data.name]);
 const balance=(code,ref)=>M.project(snapshot).balance(code,ref),ready=()=>Boolean(access&&onlineReady&&owner===onlineProfile?.id);
 function assertOwner(gen=epoch){if(!ready()||gen!==epoch)throw Error('Sessie gewijzigd. Log opnieuw in.');}
 function status(message,bad=false){error=bad?message:'';document.querySelectorAll('[data-acc-status]').forEach(e=>{e.textContent=message;e.classList.toggle('error',bad);});}
 async function rpc(name,args){const gen=epoch;const {data,error:e}=await supabaseClient.rpc(name,args);if(gen!==epoch||owner!==onlineProfile?.id)throw Error('Sessie gewijzigd.');if(e){if(e.code==='28000')lockOnlineSession();throw Object.assign(Error(e.message),{code:e.code});}return data;}
 async function init(){
  if(!onlineReady||!isTrainer()){lock();return;}
  if(owner===onlineProfile.id&&loading)return loading;
  if(owner===onlineProfile.id&&snapshot)return;
  owner=onlineProfile.id;const gen=++epoch;access=null;
  loading=(async()=>{try{const data=await rpc('fmz_accounting_read');if(gen!==epoch)return;snapshot=data;access=true;revision++;error='';}catch(e){if(gen!==epoch)return;access=e.code==='42501'?false:null;error=access===false?'Administratie is alleen beschikbaar voor de geverifieerde owner.':'Administratie laden mislukt — opnieuw proberen.';}finally{if(gen===epoch){loading=null;renderNav();render(true);}}})();return loading;
 }
 async function refresh(){assertOwner();snapshot=await rpc('fmz_accounting_read');revision++;rendered='';return snapshot;}
 async function command(action,payload){
  assertOwner();if(commandBusy)throw Error('Een administratieverzoek wordt nog verwerkt.');
  const body=JSON.stringify({action,payload});if(pending&&pending.body!==body)throw Error('Een eerdere opslag heeft nog geen bevestiging. Probeer eerst diezelfde handeling opnieuw.');
  if(!pending)pending={body,args:{action,payload:copy(payload),request_id:uid()}};
  commandBusy=true;const gen=epoch;
  try{const result=await rpc('fmz_accounting_command',pending.args);assertOwner(gen);pending=null;return result;}
  catch(e){if(gen===epoch&&e.code&&(/^(PT409|22|23|42|P0001)/.test(e.code)))pending=null;throw e;}
  finally{if(gen===epoch)commandBusy=false;}
 }
 function lock(){document.body.classList.remove('accounting-mode');epoch++;owner=null;access=null;snapshot=null;loading=null;pending=null;commandBusy=false;invoice=null;clearTimeout(invoiceTimer);modal?.close();modal?.remove();modal=null;formBusy=false;formDrafts.clear();invoiceDrafts.clear();importData=null;uploadStates.clear();pdfBytes.clear();urls.forEach(URL.revokeObjectURL);urls.clear();document.querySelectorAll('[data-accounting-root]').forEach(e=>e.replaceChildren());rendered='';}
 function btn(label,action,id='',cls='secondary-btn'){return `<button type="button" class="${cls}" data-acc-action="${esc(action)}" data-id="${esc(id)}">${esc(label)}</button>`;}
 function input(name,label,value='',type='text',extra=''){return `<label class="field"><span>${esc(label)}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
 function area(name,label,value=''){return `<label class="field full"><span>${esc(label)}</span><textarea name="${name}" rows="3">${esc(value)}</textarea></label>`;}
 function select(name,label,options,value=''){return `<label class="field"><span>${esc(label)}</span><select name="${name}">${options.map(([id,text])=>`<option value="${esc(id)}" ${String(id)===String(value)?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;}
 const amount=(name,label,value='')=>input(name,label,value,'text','inputmode="decimal"'),date=(name,label,value=today())=>input(name,label,value,'date','required');
 function checkbox(name,label,checked=false){return `<label class="acc-check"><input name="${name}" type="checkbox" ${checked?'checked':''}>${esc(label)}</label>`;}
 const panel=(title,body)=>`<section class="panel acc-panel"><h2>${esc(title)}</h2>${body}</section>`;
 function cards(rows){return rows.length?rows.join(''):'<p class="empty-mini">Nog geen posten.</p>';}
 const card=(title,body,actions='')=>`<article class="finance-card acc-card"><div><strong>${esc(title)}</strong>${body}</div><div class="finance-card-actions">${actions}</div></article>`;
 const info=(s,tag='p')=>`<${tag}>${esc(s)}</${tag}>`;
 function form(id,title,fields,label='Boeking opslaan'){return panel(title,`<form data-acc-form="${id}" class="acc-form" novalidate>${fields}<div class="full"><button class="primary-btn" type="submit">${label}</button><p data-form-status role="status"></p></div></form>`);}
 function chooseRecord(name,label,kind,predicate=()=>true){return select(name,label,[['','Kies…'],...list(kind).filter(predicate).map(r=>[r.id,r.number||r.data.description||r.data.name])]);}
 function periodControl(){const v=periodType==='quarter'?select('periodValue','Kwartaal',[1,2,3,4].map(q=>[`${periodValue.slice(0,4)}-Q${q}`,`${periodValue.slice(0,4)} kwartaal ${q}`]),periodValue):input('periodValue',periodType==='year'?'Jaar':'Maand',periodValue,periodType==='year'?'number':'month');return `<div class="acc-period">${select('periodType','Periode',[['month','Maand'],['quarter','Kwartaal'],['year','Jaar']],periodType)}${v}${periodType==='quarter'?input('quarterYear','Jaar',periodValue.slice(0,4),'number'):''}${btn('Toepassen','period-filter')}</div>`;}
 function range(){return M.period(periodType,periodValue);}
 function signals(p){return p.flags.length?`<aside class="acc-notice"><strong>Nog te controleren</strong><ul>${p.flags.map(f=>`<li>${esc(f)}</li>`).join('')}</ul></aside>`:'<p>Technische aansluiting gecontroleerd. Het btw-overzicht blijft voorbereidend.</p>';}
 function salesHTML(){
  const p=M.project(snapshot),matches=r=>{const i=p.invoices.find(x=>x.id===r.id);return salesFilter==='all'||salesFilter==='draft'&&r.status==='draft'||salesFilter==='cancelled'&&i?.cancelled||salesFilter==='credited'&&(r.parent_id||i?.credits<0)||salesFilter==='paid'&&i?.statusLabel==='Betaald'||salesFilter==='posted'&&r.status==='posted'&&!r.parent_id&&!i?.cancelled&&i?.credits===0;};
  return btn('Pakketfactuur: concept openen','new-package','','primary-btn')+' '+btn('Vrije factuur: concept openen','new-invoice')+select('salesStatus','Facturen tonen',[['all','Alle facturen'],['draft','Concept'],['posted','Definitief'],['paid','Betaald'],['cancelled','Geannuleerd'],['credited','Gecrediteerd']],salesFilter)+cards(list('invoice').filter(matches).slice().reverse().map(r=>{
   const d=r.data.document,i=p.invoices.find(x=>x.id===r.id),cancelled=!!r.data.cancellation_id;
   const links=list('invoice').filter(x=>x.parent_id===r.id&&x.status==='posted').map(x=>info('Credit: '+x.number+' · '+M.money(x.data.document.totalCents))+btn('Credit bekijken','detail',x.id)).join('');
   const correction=r.parent_id?info('Credit op '+(get(r.parent_id)?.number||'')):cancelled?info('Geannuleerd: '+r.data.cancellation_reason):'';
   const actions=r.status==='draft'?btn('Concept openen / bewerken','invoice',r.id)+btn('Concept verwijderen','draft-delete',r.id):btn('PDF openen','invoice-open',r.id)+btn('PDF downloaden','invoice-pdf',r.id)+btn('Delen','invoice-share',r.id)+(!r.parent_id&&!cancelled?btn('Factuur annuleren','invoice-cancel',r.id)+btn('Creditfactuur maken','credit',r.id):'')+btn('Boekingen en betalingen','detail',r.id);
   return card(r.number||'Concept — nog geen factuur',info(d?.customer.name||r.data.customer?.name)+info(d?.description||r.data.description)+info(d?`${M.money(d.totalCents)} · ${r.parent_id?'Creditfactuur':i?.statusLabel}${i?' · resterend '+M.money(i.outstanding):''}`:'Alleen een concept; geen omzetboeking')+correction+links,actions);
  }))+legacyHTML();
 }

 function legacyCard(item){return card(item.invoiceNo||'Historische bron',info(item.description)+info(item.amount===''?'Bedrag onbekend':M.money(Math.round(Number(item.amount||0)*100)))+info('Historische bron — niet opnieuw geboekt'),item.document?btn('Historische PDF downloaden','legacy-pdf',item.id):'');}
 function legacyHTML(){const legacy=list('legacy').find(r=>r.status==='unreviewed');const items=legacy?.data.finance?.adminItems||[];return `<details class="acc-legacy"><summary>Historische administratie (${items.length}) — aansluiting controleren</summary>${cards(items.map(legacyCard))}${info('Historische bedragen blijven ongewijzigd. Deze bron is nog niet automatisch in het grootboek geboekt.')}</details>`;}
 function overview(){const {from,to}=range(),p=M.project(snapshot,from,to);return periodControl()+`<div class="kpi-grid">${[['Omzet excl. btw',p.revenue],['Kosten',p.cost],['Resultaat',p.profit],['Openstaande facturen',p.invoices.reduce((n,r)=>n+Math.max(0,r.outstanding),0)]].map(([label,n])=>`<div class="kpi"><span>${label}</span><strong>${M.money(n)}</strong></div>`).join('')}</div>`+signals(p)+panel('Bank en kas',cards(p.bank.map(r=>card(r.data.name,info(r.known?M.money(r.cents):'Beginstand onbekend — geen volledige bankstand')+info('Boekhoudkundig resultaat is niet het beschikbare banksaldo.')))))+panel('Dagelijks',info('1. Controleer je conceptfactuur en sla de PDF definitief op. 2. Voeg bonnen toe. 3. Importeer bankmutaties en koppel betalingen. 4. Stem de bankstand af en controleer ontbrekende informatie. 5. Download geregeld een volledige export.'));}
 function expenses(){const p=M.project(snapshot);return form('expense','Uitgave toevoegen',input('supplier','Leverancier')+date('date','Factuurdatum')+area('description','Omschrijving')+select('category','Categorie',snapshot.accounts.filter(a=>a.category==='expense'&&a.code!=='5800').map(a=>[a.code,a.name]))+amount('gross','Bedrag op bon incl. eventuele btw (€)')+select('vat_treatment','Btw-behandeling',[['unknown','Nog onbekend'],['21','21% — bedrag van bon controleren'],['9','9% — bedrag van bon controleren'],['zero','0%'],['exempt','Vrijgesteld'],['kor','KOR leverancier'],['non_deductible','Niet aftrekbaar'],['reverse','Btw verlegd']])+amount('vat','Btw-bedrag op bon / voorbelasting (€)','0')+amount('charge_vat','Verschuldigde verlegde btw (€)','0')+amount('business','Zakelijk aandeel (%)','100')+amount('deductible','Aftrekbaar aandeel zakelijke btw (%)','0')+select('paid','Betaalstatus',[['unpaid','Nog te betalen / via bank koppelen'],['private','Privé voorgeschoten']])+select('account_id','Betaalrekening (optioneel)',[['','Nog kiezen'],...accountOpts()])+input('proof','Originele bon of factuur','', 'file','accept="image/*,application/pdf"')+checkbox('reverse_confirmed','Verlegde btw-behandeling gecontroleerd')+info('Geen bon of onbekende btw? De uitgave wordt zichtbaar gemarkeerd en niet stilzwijgend als aftrekbare btw verwerkt.'))+panel('Uitgaven en privévoorschotten',cards(p.expenses.slice().reverse().map(r=>card(r.data.supplier,info(`${r.date} · ${r.data.description}`)+info(`${M.money(r.data.gross_cents)} · nog ${M.money(r.outstanding)} ${r.data.control==='1900'?'aan privé te vergoeden':'te betalen'}`)+(r.data.flags||[]).map(f=>info(f,'small')).join(''),fileButtons(r.id)+btn('Bekijken / boekingen','detail',r.id)+btn('Tegenboeken','expense-correction',r.id)))));}
 function bankHTML(){const p=M.project(snapshot);return panel('Bank en Kas: eerst je beginstand',info('Bank is je zakelijke bankrekening. Kas is uitsluitend werkelijk contant geld. Gebruik je geen contant geld? Laat Kas weg of verberg de kasrekening.')+info('De openingsstand is het afschrift-/kassaldo aan het einde van de dag vóór je eerste transactie. Kies als begindatum die eerste transactiedag. Een leeg saldo blijft onbekend; €0 wordt nooit namens jou bevestigd.'))+
  form('account','1. Rekening toevoegen',input('name','Naam rekening (bijvoorbeeld ING Zakelijk)')+select('type','Type',[['bank','Bank'],['cash','Kas']])+input('iban','IBAN (leeg voor Kas)')+date('opening_date','Begindatum (optioneel)','')+amount('opening_amount','Openingssaldo vóór die dag (€; leeg = onbekend)'),'Rekening toevoegen')+
  panel('2. Rekeningen en aansluiting',cards(p.bank.map(r=>card(r.data.name,info(r.data.type==='cash'?'Kas — alleen contant geld':'Zakelijke bankrekening')+info(r.data.iban)+info(r.known?`Beginstand ${M.money(r.data.opening_cents)} vóór ${r.data.opening_date} · huidige stand ${M.money(r.cents)}`:'Beginstand onbekend')+(r.data.type==='cash'&&r.cents<0?info('Let op: negatief kassaldo. Controleer ontbrekende ontvangsten of een verkeerde datum.'):''),r.data.hidden?btn('Rekening weer tonen','account-visibility',r.id):btn(r.known?'Afstemmen':'Beginstand invoeren',r.known?'reconcile':'opening',r.id)+btn(r.data.type==='cash'?'Kas uitschakelen / verbergen':'Rekening verbergen','account-visibility',r.id)))))+
  form('bank','3. Handmatige Bank- of Kasmutatie',select('account_id','Rekening',accountOpts())+date('date','Boekdatum')+select('direction','Richting',[['in','Ontvangen'],['out','Uitgegeven']])+amount('amount','Bedrag (€)')+area('description','Omschrijving')+checkbox('cash_negative_confirmed','Alleen bij een waarschuwing: ik heb het negatieve kassaldo gecontroleerd'))+
  panel('Betalingen één keer boeken',info('Koppel een klantbetaling aan de bestaande factuur. Koppel een uitgaande betaling aan de uitgave/bon. Bankkosten voeg je eerst als uitgave met categorie Bankkosten toe.')+info('Privéstortingen en privéopnames zijn geen omzet of zakelijke kosten. Contant ontvangen geld boek je één keer in Kas. Stort je dat later op je bank? Koppel de uitgaande kasmutatie en inkomende bankmutatie met Eigen overboeking. Dat geeft geen tweede omzet.'))+
  panel('CSV downloaden en controleren',info('Een CSV is een transactiebestand van je bank. Iedere regel bevat bijvoorbeeld een datum, bedrag, naam van de tegenpartij en omschrijving. Het bestand bevat geen inlogwachtwoord.')+`<details><summary>Hoe download ik een ING-CSV?</summary><ol><li>Log via een browser in bij Mijn ING Zakelijk.</li><li>Open je zakelijke rekening en de af- en bijschrijvingen.</li><li>Kies downloaden of exporteren.</li><li>Selecteer de gewenste periode.</li><li>Kies CSV als bestandsformaat.</li><li>Upload hieronder en controleer het importvoorbeeld.</li></ol><p>ING kan benamingen wijzigen. CSV-bestanden van andere banken kunnen via kolomkoppeling worden ingelezen. APPFMZ vraagt nooit om bankwachtwoorden of tokens.</p></details>`)+
  form('import-start','4. ING / bank CSV importeren',select('account_id','Rekening',accountOpts())+input('csv','Originele CSV','', 'file','accept=".csv,text/csv"'),'Voorbeeld en kolommen bekijken')+
  panel('Niet-gekoppelde transacties',cards(list('bank').filter(r=>r.status!=='reversed'&&balance('1400',r.id)!==0).slice().reverse().map(r=>card(r.data.description||'Bankmutatie',info(`${r.date} · ${get(r.data.account_id)?.data.name||''} · ${M.money(r.data.cents)}`)+info(`Nog te koppelen: ${M.money(Math.abs(balance('1400',r.id)))}`),btn('Koppelen / splitsen','allocate',r.id)+btn('Eigen overboeking','transfer',r.id)+btn('Bron en boekingen','detail',r.id)))))+
  panel('Alle transacties',`<details><summary>Gekoppelde en teruggedraaide transacties bekijken</summary>${cards(list('bank').slice().reverse().map(r=>card(r.data.description||'Bankmutatie',info(`${r.date} · ${M.money(r.data.cents)} · ${r.status==='reversed'?'Teruggedraaid':balance('1400',r.id)===0?'Gekoppeld':'Nog te koppelen'}`),btn('Bron en boekingen','detail',r.id))))}</details>`)+
  panel('Imports',cards(list('import').slice().reverse().map(r=>card(r.date,info(`${r.data.imported_ids?.length||0} mutaties · ${r.status==='reversed'?'Teruggedraaid':'Verwerkt'}`),fileButtons(r.id)+btn('Details','detail',r.id)+(r.status==='posted'?btn('Ongekoppelde import terugdraaien','import-undo',r.id):'')))));
 }

 function privateHTML(){return form('private','Privéstorting of privéopname',select('account_id','Zakelijke rekening',accountOpts())+date('date','Datum')+select('direction','Ontvangen / uitgegeven',[['deposit','Ontvangen — Privéstorting'],['withdrawal','Uitgegeven — Privéopname']])+amount('amount','Bedrag (€)')+area('description','Omschrijving')+checkbox('cash_negative_confirmed','Alleen bij een waarschuwing: ik heb het negatieve kassaldo gecontroleerd'), 'Privétransactie opslaan')+info('Voorbeeld: vul 0,20 in voor twintig cent van privé naar zakelijk. Geen omzet of btw. Een bankkostenpost is een afzonderlijke uitgave.')+panel('Privéboekingen',ledgerHTML(['2010','2020','1900']));}
 function assetsHTML(){return form('asset','Bedrijfsmiddel registreren',date('date','Datum')+area('description','Omschrijving')+amount('amount','Boekwaarde / te activeren kosten (€)')+amount('residual','Gecontroleerde restwaarde (€)')+chooseRecord('expense_id','Aanschafuitgave (indien al geboekt)','expense')+checkbox('opening_confirmed','Zonder uitgave: dit is een bestaande bezitting op de beginbalans'))+form('loan','Schuld of lening registreren',date('date','Datum')+area('description','Schuldeiser en omschrijving')+amount('amount','Bedrag (€)')+checkbox('opening_confirmed','Dit is een bestaande schuld op de beginbalans')+info('Nieuwe lening? Koppel de daadwerkelijke ontvangst bij Bank en kas. Rente wordt afzonderlijk als uitgave verwerkt.'))+panel('Bedrijfsmiddelen',cards(list('asset').map(r=>card(r.data.description,info('Boekwaarde '+M.money(balance('1300',r.id)+balance('1390',r.id)))+info('Restwaarde '+M.money(r.data.residual_cents)),btn('Gecontroleerd afschrijven','depreciation',r.id)+btn('Boekingen','detail',r.id)))))+panel('Schulden',cards(list('loan').map(r=>card(r.data.description,info('Openstaande schuld '+M.money(-balance('1700',r.id))),btn('Boekingen','detail',r.id)))));}
 function vatHTML(){const {from,to}=range(),p=M.project(snapshot,from,to),report=FMZAccountingReports.build(snapshot,{from,to},'vat');return periodControl()+info('Voorbereidend btw-overzicht. Er wordt geen aangifte ingediend.')+info('Methode: '+(p.methods.map(x=>x==='cash'?'Kasstelsel':'Factuurstelsel').join(' / ')||'Nog niet bevestigd'))+panel(p.flags.length?'Overzicht onvolledig':'Technisch afgestemd — controleer vóór aangifte',info(p.outputVAT-p.inputVAT>=0?'Naar verwachting te betalen':'Naar verwachting terug te vragen')+info(M.money(Math.abs(p.outputVAT-p.inputVAT))))+signals(p)+btn('Btw-overzicht als PDF','report-vat','','primary-btn')+cards(report.sections.filter(x=>x.title!=='Aansluiting en controlepunten').map(x=>panel(x.title,cards(x.rows.map(row=>info(Array.isArray(row)?row.join(' · '):row))))));}

 function ledgerHTML(codes=null){const {from,to}=range(),j=new Map(snapshot.journals.map(x=>[x.id,x]));return cards(snapshot.lines.filter(l=>(!codes||codes.includes(l.account_code))&&j.get(l.journal_id).date>=from&&j.get(l.journal_id).date<=to&&l.cents).map(l=>card(`${j.get(l.journal_id).date} · ${l.account_code}`,info(j.get(l.journal_id).description)+info(`${l.cents>=0?'Debet':'Credit'} ${M.money(Math.abs(l.cents))}`),btn('Bron','detail',j.get(l.journal_id).record_id))));}
 function reports(){const {from,to}=range(),p=M.project(snapshot,from,to);return periodControl()+btn('Volledig administratieoverzicht als PDF','report-all','','primary-btn')+btn('Verkoopfacturen als PDF','report-sales')+btn('Uitgavenoverzicht als PDF','report-expenses')+btn('Btw-overzicht als PDF','report-vat')+btn('Volledige export en back-up downloaden','export','','primary-btn')+info('ZIP met leesbare overzichten, CSV, grootboek, auditgeschiedenis en alle bevestigde originele bijlagen. Bewaar een kopie buiten dit apparaat. Niet afgeronde uploads worden expliciet gemeld.')+signals(p)+panel('Resultaat en balans',info(`Omzet excl. btw ${M.money(p.revenue)} · kosten ${M.money(p.cost)} · resultaat ${M.money(p.profit)}`)+cards(p.accounts.filter(a=>a.cents||a.period_cents).map(a=>card(`${a.code} ${a.name}`,info(`Stand t/m ${to}: ${M.money(a.cents)} · mutatie in periode: ${M.money(a.period_cents)}`)))))+panel('Openstaande klanten',cards(p.invoices.filter(r=>r.outstanding).map(r=>card(r.number,info(`${r.data.document.customer.name} · ${M.money(r.outstanding)}`),btn('Bron','detail',r.id)))))+panel('Openstaande leveranciers / privévoorschotten',cards(p.expenses.filter(r=>r.outstanding).map(r=>card(r.data.supplier,info(M.money(r.outstanding)),btn('Bron','detail',r.id)))))+panel('Grootboek',ledgerHTML())+form('correction','Gecontroleerde balanscorrectie',date('date','Boekdatum')+area('description','Reden en bron van correctie')+select('debit','Debetrekening',snapshot.accounts.filter(a=>!['1100','1600','1900','1800','1200','4000'].includes(a.code)).map(a=>[a.code,a.name]))+select('credit','Creditrekening',snapshot.accounts.filter(a=>!['1100','1600','1900','1800','1200','4000'].includes(a.code)).map(a=>[a.code,a.name]))+amount('amount','Bedrag (€)')+info('Facturen corrigeer je met een creditfactuur. Een correctie voegt boekingen toe; het origineel blijft behouden.'));}
 function settingsHTML(){const s=list('settings').at(-1)?.data||{};return form('settings','Bedrijfs- en fiscale gegevens controleren',date('date','Ingangsdatum')+input('businessName','Juridische bedrijfsnaam',s.businessName)+input('ownerName','Naam eigenaar',s.ownerName)+input('address','Volledig bedrijfsadres',s.address)+input('postalCity','Postcode en plaats',s.postalCity)+input('country','Land',s.country)+input('email','E-mail',s.email,'email')+input('phone','Telefoon',s.phone)+input('website','Website (optioneel)',s.website)+input('chamberNumber','KVK-nummer',s.chamberNumber)+checkbox('kvk_registered','Ingeschreven bij KVK',s.kvk_registered!==false)+input('vatNumber','Btw-identificatienummer',s.vatNumber)+input('iban','IBAN op factuur',s.iban)+select('vat_status','Btw/KOR-status',[['unknown','Nog controleren'],['standard','Btw-plichtig'],['kor','Kleineondernemersregeling'],['exempt','Vrijgestelde prestaties']],s.vat_status)+select('vat_method','Methode omzetbelasting',[['unknown','Nog controleren'],['invoice','Factuurstelsel'],['cash','Kasstelsel']],s.vat_method)+select('vat_period','Aangifteperiode',[['unknown','Nog controleren'],['month','Maand'],['quarter','Kwartaal'],['year','Jaar'],['none','Geen reguliere aangifte']],s.vat_period)+select('vat_basis_points','Btw-tarief dienstverlening',[['','Nog controleren'],['0','0%'],['900','9%'],['2100','21%']],s.vat_basis_points??Number(s.vatPercent||0)*100)+input('paymentTermDays','Standaard betaaltermijn (dagen)',s.paymentTermDays??14,'number','min="0" max="3650"')+area('note','Factuurtekst / toepasselijke vrijstellingsgrondslag',s.note)+checkbox('confirmed','Ik heb deze bedrijfsgegevens en fiscale keuzes gecontroleerd'),'Instellingen met ingangsdatum bevestigen')+
  panel('Eerdere instellingen',cards(list('settings').map(r=>card(r.date,info(`${r.status==='confirmed'?'Bevestigd':'Nog niet bevestigd'} · ${r.data.vat_status} · ${r.data.vat_method}`),btn('Details','detail',r.id)))))+
  form('legacy-review','Historie aansluiten',area('reason','Wat is gecontroleerd, welke beginboekingen zijn gemaakt en welke periodes ontbreken?'),'Aansluiting vastleggen')+
  form('close-period','Periode afsluiten',date('from','Vanaf')+date('to','Tot en met')+area('reason','Reden en resterende controlepunten'),'Periode afsluiten')+
  panel('Periodes',cards(list('period').map(r=>card(`${r.data.from} – ${r.data.to}`,info(r.status==='closed'?'Afgesloten':'Heropend')+info(r.data.reason),r.status==='closed'?btn('Heropenen met reden','reopen',r.id):''))))+
  panel('Bewaren en wijzigen',info('Basisadministratie doorgaans 7 jaar, onroerende zaken en OSS 10 jaar na einde actualiteitswaarde. Bij onbekend startmoment blijven bestanden bewaard. Er is geen automatische verwijdering. Open een document bij Bron en boekingen om de bewaartermijn vast te leggen.')+info('De administratie wordt niet verwijderd met een gewone accountverwijdering. Elke boeking, bevestiging en correctie wordt met account en tijdstip vastgelegd.')+`<details><summary>Wijzigingsgeschiedenis (${snapshot.audit.length})</summary>${cards(snapshot.audit.slice().reverse().map(a=>card(a.action,info(`${a.at} · ${a.actor_id}`)+`<details><summary>Wat is gewijzigd?</summary><pre>${esc(JSON.stringify(a.detail,null,2))}</pre></details>`)))}</details>`);}
 function render(force=false){
  if(typeof isTrainer!=='function'||!isTrainer())return;
  for(const id of ['administration','invoice']){const view=document.getElementById(id);if(!view)continue;let root=view.querySelector('[data-accounting-root]');if(!root){[...view.children].forEach(e=>e.hidden=true);root=document.createElement('div');root.dataset.accountingRoot=id;view.append(root);root.addEventListener('click',click);root.addEventListener('submit',submit);root.addEventListener('input',rememberForm);root.addEventListener('change',rememberForm);root.addEventListener('change',selectChanged);}}
  if(!['administration','invoice'].includes(currentView))return;
  const stamp=[owner,access,revision,currentView,page,periodType,periodValue,error].join('|');if(!force&&rendered===stamp)return;
  const root=document.querySelector(`#${currentView} [data-accounting-root]`);if(!root)return;
  if(!snapshot||!ready()){root.innerHTML=panel('Administratie',info(error||'Ownerrechten controleren…')+btn('Opnieuw laden','reload'));rendered=stamp;return;}
  const selected=currentView==='invoice'?'sales':page;
  const content={overview, sales:salesHTML,expenses,bank:bankHTML,private:privateHTML,assets:assetsHTML,vat:vatHTML,reports,settings:settingsHTML}[selected]();
  root.innerHTML=`<div class="acc-heading"><div><p class="eyebrow">FitMetZorge · privé voor de owner</p><h1 tabindex="-1">${esc(menus.find(m=>m[0]===selected)[1])}</h1></div>${btn('Verversen','reload')}</div><p data-acc-status role="status">${esc(error)}</p><div class="acc-layout"><details class="acc-navigation" ${innerWidth>1100?'open':''}><summary>Onderdeel kiezen: ${esc(menus.find(m=>m[0]===selected)[1])}</summary><nav class="acc-menu" aria-label="Administratieonderdelen">${menus.map(([id,label])=>`<button type="button" data-acc-page="${id}" class="${id===selected?'active':''}">${esc(label)}</button>`).join('')}</nav></details><div class="acc-content">${content}</div></div>`;
  root.querySelectorAll('form[data-acc-form]').forEach(f=>{const d=formDrafts.get(f.dataset.accForm);if(d)for(const [k,v]of Object.entries(d.values)){const e=f.elements.namedItem(k);if(e&&e.type!=='file'){if(e.type==='checkbox')e.checked=v;else e.value=v;}}});rendered=stamp;
 }
 function selectChanged(e){
  if(e.target.name==='salesStatus'){salesFilter=e.target.value;render(true);return;}
  if(e.target.name==='periodType'){const next=e.target.value,year=periodValue.slice(0,4),month=periodType==='quarter'?(Number(periodValue.slice(-1))-1)*3+1:periodType==='month'?Number(periodValue.slice(5,7)):1;periodType=next;periodValue=next==='year'?year:next==='quarter'?year+'-Q'+Math.ceil(month/3):year+'-'+String(month).padStart(2,'0');render(true);}
 }
 function rememberForm(e){const f=e.target.closest('[data-acc-form]');if(!f)return;const old=formDrafts.get(f.dataset.accForm)||{id:uid()};old.values=formValues(f);old.dirty=true;if(e.target.type==='file')old.file=e.target.files[0];formDrafts.set(f.dataset.accForm,old);}
 function formValues(f){const v=Object.fromEntries(new FormData(f));f.querySelectorAll('[type=checkbox]').forEach(e=>v[e.name]=e.checked);return v;}
 function showModal(title,body){modal?.remove();modal=document.createElement('dialog');modal.className='acc-dialog';modal.innerHTML=`<header><h2>${esc(title)}</h2>${btn('Sluiten','close')}</header>${body}`;document.body.append(modal);modal.addEventListener('click',click);modal.addEventListener('submit',submit);modal.addEventListener('input',rememberForm);modal.addEventListener('change',rememberForm);modal.addEventListener('cancel',e=>{e.preventDefault();modal.querySelector('[data-acc-action=close]').click();});modal.showModal();return modal;}
 async function click(e){const target=e.target.closest('[data-acc-action],[data-acc-page]');if(!target)return;e.preventDefault();if(target.dataset.accPage){page=target.dataset.accPage;showView('administration');render(true);const h=document.querySelector('#administration [data-accounting-root] h1');h?.focus({preventScroll:true});h?.scrollIntoView({block:'start'});return;}
  const a=target.dataset.accAction,id=target.dataset.id;try{
   if(a==='close'){if(formBusy||invoice?.busy)return;if(invoice?.dirty&&!(await persistInvoice(invoice)))return;modal?.close();invoice=null;clearTimeout(invoiceTimer);return;}
   if(a==='reload'){if(!snapshot){loading=null;await init();return;}await refresh();render(true);return;}
   assertOwner();
   if(a==='period-filter'){const scope=target.closest('.acc-period');periodType=scope.querySelector('[name=periodType]').value;const v=scope.querySelector('[name=periodValue]').value;periodValue=periodType==='year'?v.slice(0,4):periodType==='quarter'?(scope.querySelector('[name=quarterYear]')?.value||v.slice(0,4))+'-Q'+(v.includes('Q')?v.slice(-1):Math.ceil(Number(v.slice(5,7)||1)/3)):v.includes('Q')?v.slice(0,4)+'-'+String((Number(v.slice(-1))-1)*3+1).padStart(2,'0'):v.length===4?v+'-01':v;range();render(true);}
   else if(a==='new-package'||a==='new-invoice')await newInvoice(a==='new-package');
   else if(a==='invoice')await openInvoice(id);
   else if(a==='invoice-line-add'){addInvoiceLine();invoice.capture();}
   else if(a==='invoice-line-remove'){target.closest('[data-invoice-line]').remove();invoice.capture();}
   else if(a==='draft-delete')await deleteDraft(id);
   else if(a==='invoice-save')await saveInvoice(target);
   else if(a==='invoice-open'||a==='invoice-share')await viewInvoice(id,a==='invoice-share');
   else if(a==='invoice-cancel'){const r=get(id);showModal('Factuur annuleren',form('invoice-cancel',r.number,input('record_id','Factuur',id,'hidden')+area('reason','Reden van annuleren')+checkbox('unpaid_unsent_confirmed','Ik bevestig dat deze factuur niet is verzonden en nooit is betaald of gekoppeld.')+info('Alleen in een open periode. Nummer, originele PDF en boekingshistorie blijven behouden. Voor verzonden of betaalde facturen gebruik je een creditfactuur.'),'Annulering bevestigen'));}
   else if(a==='account-visibility'){const r=get(id);await command('account_visibility',{id,version:r.version,data:{hidden:!r.data.hidden}});await refresh();render(true);}
   else if(a==='import-undo'){showModal('Ongekoppelde import terugdraaien',form('import-undo','Import controleren',input('record_id','Import',id,'hidden')+area('reason','Reden voor terugdraaien')+info('Alleen ongekoppelde, niet-afgestemde mutaties in open perioden. De originele CSV en historie blijven behouden; er komen tegenboekingen.'),'Import terugdraaien'));}
   else if(a?.startsWith('report-')){target.disabled=true;try{const data=FMZAccountingReports.build(snapshot,range(),a.slice(7)),bytes=await FMZInvoices.report(data);downloadBlob(new Blob([bytes],{type:'application/pdf'}),`FitMetZorge-${a.slice(7)}-${data.period.from}-${data.period.to}.pdf`);}finally{target.disabled=false;}}
   else if(a==='invoice-pdf')await downloadInvoice(id);
   else if(a==='invoice-refresh')await refreshInvoice();
   else if(a==='invoice-use-mine'){invoice.version=invoice.remote.version;invoice.conflict=false;invoice.dirty=true;invoice.message.textContent='Vernieuwde versie gekozen. Jouw concept wordt opnieuw opgeslagen.';await persistInvoice(invoice);}
   else if(a==='credit')await creditInvoice(id);
   else if(a==='legacy-pdf'){const item=list('legacy').find(r=>r.status==='unreviewed')?.data.finance?.adminItems?.find(x=>x.id===id);if(item?.document)downloadBlob(new Blob([await FMZInvoices.pdf(item.document)],{type:'application/pdf'}),(item.invoiceNo||'historische-factuur')+'.pdf');}
   else if(a==='file')await openFile(id);
   else if(a==='export'){target.disabled=true;try{await exportAll();}finally{target.disabled=false;}}
   else if(a==='detail')detail(id);
   else if(a==='opening'||a==='reconcile'){const r=get(id);showModal(a==='opening'?'Beginstand bevestigen':'Bankstand afstemmen',form(a,r.data.name,input('account_id','Rekening-ID',id,'hidden')+date('date',a==='opening'?'Beginstand vóór mutaties op deze datum':'Eindstand op deze datum')+amount('amount',a==='opening'?'Beginstand (€; negatief toegestaan)':'Eindstand volgens afschrift (€)')+area('description','Bron / toelichting')));}
   else if(a==='allocate')allocationModal(id);
   else if(a==='add-split')addSplit();
   else if(a==='remove-split')target.closest('.acc-split').remove();
   else if(a==='transfer'){const r=get(id);showModal('Overboeking eigen rekeningen',form('transfer','Twee bankmutaties koppelen',select('from_id','Uitgaande mutatie',list('bank').filter(x=>x.data.cents<0&&balance('1400',x.id)>0).map(x=>[x.id,`${x.date} ${x.data.description} ${M.money(x.data.cents)}`]),r.data.cents<0?id:'')+select('to_id','Inkomende mutatie',list('bank').filter(x=>x.data.cents>0&&balance('1400',x.id)<0).map(x=>[x.id,`${x.date} ${x.data.description} ${M.money(x.data.cents)}`]),r.data.cents>0?id:'')+date('date','Koppeldatum')+amount('amount','Te koppelen bedrag (€)')));}
   else if(a==='depreciation'){const r=get(id);showModal('Gecontroleerd afschrijven',form('depreciation',r.data.description,input('asset_id','Bedrijfsmiddel',id,'hidden')+date('date','Boekdatum')+amount('amount','Afschrijving (€)')+area('description','Gecontroleerde afschrijvingsgrondslag / reden')));}
   else if(a==='expense-correction')showModal('Uitgave tegenboeken',form('expense-correction','Uitgave corrigeren',input('expense_id','Uitgave',id,'hidden')+date('date','Correctiedatum')+area('description','Reden van de tegenboeking')+info('Het origineel blijft bestaan. Voeg daarna zo nodig een juiste uitgave met de juiste bron toe. Een betaalde uitgave krijgt na tegenboeken een te ontvangen terugbetaling. Koppel die bij Bank en kas. Geactiveerde bedrijfsmiddelen vereisen eerst aansluiting.')));
   else if(a==='reopen')showModal('Periode heropenen',form('reopen','Heropening vastleggen',input('period_id','Periode',id,'hidden')+area('reason','Reden'),'Periode heropenen'));
   else if(a==='retention'){const f=snapshot.files.find(x=>x.id===id);showModal('Bewaargrondslag',form('retention',f.original_name,input('file_id','Document',id,'hidden')+select('class','Documentsoort',[['basis','Basisadministratie — 7 jaar'],['contract','Contract — na einde actualiteit 7 jaar'],['onroerend','Onroerende zaken — 10 jaar'],['oss','OSS — 10 jaar'],['overig','Overig — grondslag controleren']],f.retention_class)+date('active_until','Einde actualiteitswaarde (leeg = onbekend / blijven bewaren)',f.active_until||'')+area('reason','Waarom begint de bewaartermijn op deze datum?')));}
   else if(a==='import-preview')await importPreview();
   else if(a==='import-confirm')await importConfirm(target);
  }catch(ex){(modal?.open?modal.querySelector('[data-form-status],[data-invoice-message]'):null)?.replaceChildren(document.createTextNode(ex.message));status(ex.message,true);}
 }
 async function deleteDraft(id){
  if(invoice?.busy||invoice?.finalBusy||commandBusy)return;if(!confirm('Dit concept definitief verwijderen? Er wordt geen definitieve factuur verwijderd.'))return;
  const d=invoiceDrafts.get(id);clearTimeout(invoiceTimer);if(d){clearTimeout(d.previewTimer);if(!d.version){invoiceDrafts.delete(id);d.dirty=false;modal?.close();invoice=null;render(true);return;}}
  const r=get(id);await command('draft_delete',{id,version:r.version,data:{confirmed:true}});invoiceDrafts.delete(id);if(invoice?.id===id){invoice.dirty=false;modal?.close();invoice=null;}await refresh();render(true);status('Concept verwijderd');
 }
 function fileButtons(rid){return snapshot.files.filter(f=>f.record_id===rid&&f.status==='ready').map(f=>btn(f.kind==='invoice_pdf'?'PDF downloaden':f.original_name,'file',f.id)).join('');}
 function detail(id){const r=get(id);if(!r)return;const js=snapshot.journals.filter(j=>j.record_id===id||snapshot.lines.some(l=>l.journal_id===j.id&&l.reference_id===id));showModal(r.number||r.data.description||r.kind,panel('Brongegevens',`<pre>${esc(JSON.stringify(r.data,(k,v)=>k==='logo'?'[ingebed bedrijfslogo]':v,2))}</pre>`)+panel('Boekingen',cards(js.map(j=>card(j.date+' · '+j.description,snapshot.lines.filter(l=>l.journal_id===j.id).map(l=>info(`${l.account_code}: ${l.cents>=0?'debet':'credit'} ${M.money(Math.abs(l.cents))}`)).join('')))))+panel('Originele bestanden',fileButtons(id)+cards(snapshot.files.filter(f=>f.record_id===id).map(f=>card(f.original_name,info(`SHA-256 ${f.sha256}`)+info(`Bewaren: ${f.keep_until?'minimaal t/m '+f.keep_until:'einde actualiteitswaarde onbekend; blijven bewaren'}`),btn('Bewaargrondslag','retention',f.id))))));}
 function allocationModal(id){const r=get(id);showModal('Betaling koppelen / splitsen',form('allocate',`${r.data.description} · ${M.money(Math.abs(balance('1400',id)))} beschikbaar`,input('bank_id','Bankmutatie',id,'hidden')+date('date','Koppeldatum',r.date)+'<div class="acc-splits full"></div>'+btn('Nog een verdeling','add-split'),'Verdeling opslaan'));addSplit();}
 function addSplit(){const root=modal.querySelector('.acc-splits');if(!root)return;const row=document.createElement('div');row.className='acc-split';row.innerHTML=select('split_target','Koppelen aan',[['','Kies…'],...list('invoice').filter(r=>r.status==='posted'&&!r.parent_id&&!r.data.cancellation_id).map(r=>['invoice:'+r.id,r.number+' · '+r.data.document.customer.name]),...list('expense').map(r=>['expense:'+r.id,r.data.supplier+' · '+r.data.description]),['deposit:','Privéstorting'],['withdrawal:','Privéopname'],...list('loan').map(r=>['loan:'+r.id,'Lening: '+r.data.description])])+amount('split_amount','Deelbedrag (€)')+btn('Deze verdeling verwijderen','remove-split');root.append(row);}
 async function submit(e){const f=e.target.closest('[data-acc-form]');if(!f)return;e.preventDefault();e.stopPropagation();if(formBusy)return;assertOwner();if(f.dataset.committed==='true'){try{await refresh();render(true);status('Opgeslagen');}catch(ex){status('Opgeslagen — overzicht vernieuwen mislukt. Probeer Verversen.',true);}return;}const kind=f.dataset.accForm,existing=formDrafts.get(kind),v=pending&&existing?.request?existing.values:formValues(f),d=existing||{id:uid(),values:v};d.values=v;formDrafts.set(kind,d);const message=f.querySelector('[data-form-status]'),gen=epoch;formBusy=true;f.querySelector('[type=submit]').disabled=true;
  try{
   message.textContent='Opslaan…';status('Opslaan…');let action=kind,data={...v},id=d.id;
   if(kind==='import-start'){const file=f.elements.csv.files[0]||d.file;if(!file)throw Error('Kies een CSV-bestand.');if(file.size>12000000)throw Error('CSV is groter dan 12 MB.');const rows=M.csv(await file.text());if(rows.length<2||rows.length>2001)throw Error('Kies een CSV met 1 tot 2000 mutaties.');importData={file,rows,account_id:v.account_id,map:M.mapping(rows[0]),id:uid()};importModal();return;}
   if(kind==='expense'){const proof=f.elements.proof.files[0]||d.file;if(proof&&!d.file_id)d.file_id=(await upload(proof,{kind:'evidence'})).id;
    data={date:M.date(v.date),supplier:v.supplier,description:v.description,category:v.category,gross_cents:M.cents(v.gross),vat_treatment:v.vat_treatment,vat_cents:M.cents(v.vat),charge_vat_cents:M.cents(v.charge_vat),business_bp:M.cents(v.business),deductible_bp:M.cents(v.deductible),paid_privately:v.paid==='private',account_id:v.account_id||null,file_id:d.file_id||null,reverse_confirmed:v.reverse_confirmed};
   }else if(kind==='bank'||kind==='private'){data={account_id:v.account_id,date:M.date(v.date),cents:M.cents(v.amount)*(kind==='bank'&&v.direction==='out'?-1:1),direction:v.direction,description:v.description,cash_negative_confirmed:v.cash_negative_confirmed===true};}
   else if(kind==='opening'||kind==='reconcile'){action=kind==='reconcile'?'reconcile':'opening';data={account_id:v.account_id,date:M.date(v.date),[kind==='opening'?'cents':'closing_cents']:M.cents(v.amount,true),description:v.description};}
   else if(kind==='allocate'){data={bank_id:v.bank_id,date:M.date(v.date),parts:[...f.querySelectorAll('.acc-split')].map(row=>{const [type,target_id]=row.querySelector('[name=split_target]').value.split(':');return {type,target_id:target_id||null,cents:M.cents(row.querySelector('[name=split_amount]').value)};})};}
   else if(kind==='transfer'){data={from_id:v.from_id,to_id:v.to_id,date:M.date(v.date),cents:M.cents(v.amount)};}
   else if(kind==='asset'||kind==='loan'){data={date:M.date(v.date),description:v.description,cents:M.cents(v.amount),opening_confirmed:v.opening_confirmed,...(kind==='asset'?{residual_cents:M.cents(v.residual),expense_id:v.expense_id||null}:{})};}
   else if(kind==='depreciation'){data={asset_id:v.asset_id,date:M.date(v.date),description:v.description,cents:M.cents(v.amount)};}
   else if(kind==='expense-correction'){action='expense_correction';data={expense_id:v.expense_id,date:M.date(v.date),description:v.description};}
   else if(kind==='correction'){if(v.debit===v.credit)throw Error('Kies verschillende debet- en creditrekeningen.');const n=M.cents(v.amount);if(n<=0)throw Error('Vul een positief correctiebedrag in.');data={date:M.date(v.date),description:v.description,lines:[[v.debit,n,null],[v.credit,-n,null]]};}
   else if(kind==='settings'){data={...v,date:M.date(v.date),vat_basis_points:v.vat_basis_points===''?null:Number(v.vat_basis_points),paymentTermDays:Number(v.paymentTermDays)};if(!v.confirmed||v.vat_status==='unknown'||v.vat_method==='unknown'||v.vat_period==='unknown'||data.vat_basis_points===null)throw Error('Controleer en bevestig de fiscale keuzes en het btw-tarief.');if(!/^\d+$/.test(v.paymentTermDays)||Number(v.paymentTermDays)>3650)throw Error('Controleer de betaaltermijn.');if(v.vat_status==='exempt'&&!v.note.trim())throw Error('Vul de vrijstellingsgrondslag in.');}
   else if(kind==='legacy-review'){action='legacy_review';data={reason:v.reason};}
   else if(kind==='close-period'){action='close_period';data={from:M.date(v.from),to:M.date(v.to),reason:v.reason};}
   else if(kind==='reopen'){action='reopen_period';id=v.period_id;data={reason:v.reason};}
   else if(kind==='retention'){id=v.file_id;data={class:v.class,active_until:v.active_until?M.date(v.active_until):null,reason:v.reason};}
   else if(kind==='invoice-cancel'||kind==='import-undo'){action=kind==='invoice-cancel'?'invoice_cancel':'import_undo';id=v.record_id;data={reason:v.reason,unpaid_unsent_confirmed:v.unpaid_unsent_confirmed};}
   else if(kind==='account'){data={name:v.name,type:v.type,iban:v.iban.trim(),...(v.opening_date||v.opening_amount?{opening_date:M.date(v.opening_date),opening_cents:M.cents(v.opening_amount,true)}:{})};}
   if(!pending||!d.request)d.request={action,payload:{id,data,...(['invoice_cancel','import_undo'].includes(action)?{version:get(id).version}:{})}};f.querySelectorAll('input,select,textarea').forEach(e=>e.disabled=true);await command(d.request.action,d.request.payload);assertOwner(gen);d.committed=true;f.dataset.committed='true';d.dirty=false;formDrafts.delete(kind);message.textContent='Opgeslagen';await refresh();if(modal?.contains(f)){modal.close();modal.remove();modal=null;}render(true);status('Opgeslagen');
  }catch(ex){if(gen===epoch){message.textContent=(d.committed?'Opgeslagen — overzicht vernieuwen mislukt: ':'Niet opgeslagen — ')+ex.message;status(message.textContent,true);if(d.committed)f.querySelector('[type=submit]').textContent='Opgeslagen — overzicht opnieuw laden';}}
  finally{if(gen===epoch){formBusy=false;const b=f.querySelector('[type=submit]');if(b)b.disabled=false;if(!pending&&!d.committed)f.querySelectorAll('input,select,textarea').forEach(e=>e.disabled=false);}}
 }
 async function upload(file,meta){assertOwner();const gen=epoch,bytes=new Uint8Array(await file.arrayBuffer()),sha=await M.hash(bytes),mime=file.type||(/\.csv$/i.test(file.name)?'text/csv':'application/octet-stream');const reservationKey=JSON.stringify([sha,meta]);let stateFile=uploadStates.get(reservationKey);if(!stateFile){stateFile={id:uid()};uploadStates.set(reservationKey,stateFile);}
  let f=stateFile.record;
  if(!f){f=await command('file_reserve',{id:stateFile.id,data:{...meta,original_name:file.name,mime,bytes:bytes.length,sha256:sha}});stateFile.record=f;}
  assertOwner(gen);
  if(f.status==='ready')return f;
  if(f.sha256!==sha){const existing=await supabaseClient.storage.from('fmz-finance').download(f.path);if(existing.error)throw Error('Eerdere PDF-upload heeft nog geen bevestiging. Probeer dezelfde PDF opnieuw.');if(await M.hash(await existing.data.arrayBuffer())!==f.sha256)throw Error('Eerdere PDF wijkt af van het archiefkenmerk.');}
  else{const {error:uploadError}=await supabaseClient.storage.from('fmz-finance').upload(f.path,bytes,{contentType:mime,upsert:false});assertOwner(gen);if(uploadError){const retry=await supabaseClient.storage.from('fmz-finance').download(f.path);if(retry.error||await M.hash(await retry.data.arrayBuffer())!==sha)throw Error('Bestand niet opgeslagen — opnieuw proberen.');}}
  assertOwner(gen);f=await command('file_finish',{id:f.id});stateFile.record=f;return f;
 }
 const uploadStates=new Map();
 function downloadBlob(blob,name){assertOwner();const url=URL.createObjectURL(blob);urls.add(url);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>{URL.revokeObjectURL(url);urls.delete(url)},60000);}
 async function fileBlob(f){const gen=epoch;assertOwner(gen);const {data,error:e}=await supabaseClient.storage.from('fmz-finance').download(f.path);if(e)throw Error('Bestand downloaden mislukt — probeer opnieuw.');const bytes=await data.arrayBuffer();assertOwner(gen);if(bytes.byteLength!==f.bytes||await M.hash(bytes)!==f.sha256)throw Error('Bestandscontrole mislukt. Download niet gebruikt.');return new Blob([bytes],{type:f.mime});}
 async function openFile(id){const f=snapshot.files.find(f=>f.id===id&&f.status==='ready');if(!f)throw Error('Origineel bestand nog niet bevestigd.');const blob=await fileBlob(f);if(f.mime.startsWith('image/')&&!['image/heic','image/heif'].includes(f.mime)){const url=URL.createObjectURL(blob);urls.add(url);showModal(f.original_name,`<img class="acc-proof" src="${url}" alt="Origineel bewijs">${btn('Origineel downloaden','file-download',id)}`);modal.querySelector('[data-acc-action=file-download]').onclick=()=>downloadBlob(blob,f.original_name);}else downloadBlob(blob,f.original_name);}
 function currentSettings(d=today()){return copy(list('settings').filter(r=>r.status==='confirmed'&&r.date<=d).at(-1)?.data||list('settings').at(-1)?.data||{});}
 async function newInvoice(packageOnly=true){assertOwner();const selected=client();const opts=[['','Kies een klant'],...state.clients.map(c=>[c.id,c.name+' · '+clientPackageLabel(c)])];showModal(packageOnly?'Pakketfactuur openen':'Factuurconcept openen',`<div class="acc-form">${select('invoice_client','Klant',opts,selected?.id||'')}${btn('Concept openen','choose-invoice')}</div>`);modal.querySelector('[data-acc-action=choose-invoice]').onclick=()=>{
   const c=state.clients.find(c=>c.id===modal.querySelector('[name=invoice_client]').value);if(!c){status('Kies eerst een klant.',true);return;}
   const pkg=packageByValue(c.profile?.package),amountValue=packageOnly?clientPackageAmount(c):'',s=currentSettings(),id=uid();
   const raw={description:packageOnly?`Pakket: ${clientPackageLabel(c)} — ${monthLabel(today().slice(0,7))}`:'',amount:amountValue===''?'':String(amountValue),discount:'0',discountNote:'',date:today(),term:String(s.paymentTermDays??14),customerName:c.name,customerAddress:[c.profile?.address,c.profile?.postalCode,c.profile?.city].filter(Boolean).join(', '),customerEmail:c.email||'',serviceDate:today(),serviceExtent:packageOnly&&pkg?.sessions?`${pkg.sessions} trainingen in deze maand`:'',quantity:String(packageOnly&&pkg?.sessions?pkg.sessions:1)};
   raw.unitPrice=amountValue===''?'':String(Number(amountValue)/(packageOnly&&pkg?.sessions?pkg.sessions:1));raw.priceMode='inclusive';raw.discountMode='fixed';raw.discountPercent='0';raw.extraLines=[];raw.period=today().slice(0,7);
   const d={id,owner,version:0,values:raw,clientId:c.id,packageLabel:clientPackageLabel(c),dirty:true};invoiceDrafts.set(id,d);showInvoice(d);
  };
 }
 async function openInvoice(id){assertOwner();let r=get(id);if(!r){const legacy=list('legacy').find(r=>r.status==='unreviewed')?.data.finance?.adminItems?.find(i=>i.id===id);if(legacy){showModal('Historische factuur',legacyCard(legacy)+info('Historische facturen zijn alleen-lezen en worden niet opnieuw uitgegeven.'));return;}throw Error('Factuur ontbreekt. Ververs de administratie.');}
  if(r.status==='posted'){detail(id);return;}let d=invoiceDrafts.get(id);if(!d){d={id,owner,version:r.version,values:r.data.raw||{},clientId:r.data.client_id,packageLabel:r.data.packageLabel,creditOf:r.data.credit_of,dirty:false};invoiceDrafts.set(id,d);}showInvoice(d);
 }
 async function creditInvoice(id){const original=get(id);if(!original||original.status!=='posted'||original.parent_id)throw Error('Kies een oorspronkelijke factuur.');const doc=original.data.document,remaining=doc.totalCents+list('invoice').filter(r=>r.status==='posted'&&r.parent_id===id).reduce((n,r)=>n+r.data.document.totalCents,0);if(remaining<=0)throw Error('Deze factuur is volledig gecrediteerd.');const d={id:uid(),owner,version:0,creditOf:id,packageLabel:doc.packageLabel,dirty:true,values:{description:'',amount:(remaining/100).toFixed(2),discount:'0',discountNote:'',date:today(),term:'14',customerName:doc.customer.name,customerAddress:doc.customer.address,customerEmail:doc.customer.email,serviceDate:doc.serviceDate,serviceExtent:doc.serviceExtent,quantity:'1'}};invoiceDrafts.set(d.id,d);showInvoice(d);}
 function showInvoice(d){
  invoice=d;d.values=FMZInvoiceEditor.normalize(d.values);const v=d.values;
  showModal(d.creditOf?'Creditfactuur — concept':'Factuur — concept',`<form id="invoiceDraftForm" class="acc-form" novalidate>
   <p class="full">${esc(d.packageLabel||'')} · ${d.creditOf?'Correctie op '+esc(get(d.creditOf)?.number):'Nummer volgt pas bij definitief opslaan'}</p>
   ${input('customerName','Klantnaam',v.customerName)}${input('customerEmail','Klant e-mail (er wordt niets verstuurd)',v.customerEmail,'email')}${input('customerAddress','Volledig klantadres',v.customerAddress)}
   ${select('priceMode','Ingevoerde regelprijzen',[['inclusive','Inclusief btw'],['exclusive','Exclusief btw']],v.priceMode)}
   ${area('description',d.creditOf?'Reden van credit':'Omschrijving regel 1',v.description)}${input('quantity','Aantal regel 1',v.quantity,'text','inputmode="decimal"')}${amount('unitPrice','Prijs per stuk (€)',v.unitPrice)}
   <div class="full" data-extra-invoice-lines></div>${d.creditOf?'':btn('Factuurregel toevoegen','invoice-line-add')}
   ${input('amount','Subtotaal regelprijzen (€)',v.amount,'text','readonly aria-readonly="true"')}
   ${select('discountMode','Soort korting',[['fixed','Vast bedrag (€)'],['percent','Percentage (%)']],v.discountMode)}${amount('discount','Korting (€)',v.discount)}${amount('discountPercent','Korting (%)',v.discountPercent)}${area('discountNote','Toelichting korting (optioneel)',v.discountNote)}
   ${date('date','Factuurdatum',v.date)}${input('term','Betaaltermijn (dagen)',v.term,'text','inputmode="numeric"')}${date('serviceDate','Leverdatum / vooruitbetalingsdatum',v.serviceDate)}${input('serviceExtent','Omvang van de dienst',v.serviceExtent)}${input('period','Factuurperiode (optioneel)',v.period)}${input('reference','Referentie (optioneel)',v.reference)}
   <section class="invoice-draft-preview full" aria-live="polite"></section>
   <details class="full invoice-a4" open><summary>A4-voorbeeld van de PDF</summary><p data-preview-status role="status">Voorbeeld voorbereiden…</p><div data-pdf-preview></div></details>
   <p data-invoice-message role="status" class="full">Concept — typen geeft geen factuur uit.</p><div class="full acc-actions">${btn('Definitief opslaan en PDF downloaden','invoice-save',d.id,'primary-btn')}${btn('Serverconcept verversen / vergelijken','invoice-refresh',d.id)}${btn('Concept verwijderen','draft-delete',d.id)}</div></form>`);
  const f=modal.querySelector('form');d.message=f.querySelector('[data-invoice-message]');
  for(const row of v.extraLines||[])addInvoiceLine(row);
  if(d.creditOf){for(const name of ['discount','discountPercent','priceMode','discountMode','quantity']){f.elements[name].readOnly=true;if(f.elements[name].tagName==='SELECT')f.elements[name].disabled=true;}v.discount='0';v.discountPercent='0';v.priceMode='inclusive';}
  d.capture=()=>{if(d.finalBusy)return;d.values={...d.values,...FMZInvoiceEditor.read(f)};d.dirty=true;if(!d.conflict)d.message.textContent=d.busy?'Nieuwere invoer nog niet opgeslagen…':'Niet opgeslagen';invoicePreview(d);clearTimeout(invoiceTimer);if(!d.conflict)invoiceTimer=setTimeout(()=>persistInvoice(d),650);};
  f.addEventListener('input',d.capture);f.addEventListener('change',e=>{if(e.target.tagName==='SELECT')d.capture();});
  f.addEventListener('submit',e=>{e.preventDefault();saveInvoice(f.querySelector('[data-acc-action=invoice-save]'));});invoicePreview(d);
 }
 function addInvoiceLine(row={description:'',quantity:'1',unitPrice:''}){const target=modal.querySelector('[data-extra-invoice-lines]'),div=document.createElement('div');div.dataset.invoiceLine='';div.className='invoice-extra-line';div.innerHTML=`<label class="field full"><span>Omschrijving</span><textarea data-line-field="description">${esc(row.description)}</textarea></label><label class="field"><span>Aantal</span><input inputmode="decimal" data-line-field="quantity" value="${esc(row.quantity)}"></label><label class="field"><span>Prijs per stuk (€)</span><input inputmode="decimal" data-line-field="unitPrice" value="${esc(row.unitPrice)}"></label>${btn('Regel verwijderen','invoice-line-remove')}`;target.append(div);}

 function draftPayload(d,strict=false){
  const v=d.values,parse=s=>{try{return M.cents(s)}catch(e){if(strict)throw e;return null;}},body={raw:copy(v),date:v.date||today(),client_id:d.clientId||null,packageLabel:d.packageLabel||'',credit_of:d.creditOf||null,customer:{name:v.customerName||'',email:v.customerEmail||'',address:v.customerAddress||''},description:v.description||'',gross_cents:null,discount_cents:parse(v.discount??'0'),discountNote:v.discountNote||'',service_date:v.serviceDate||null,service_extent:v.serviceExtent||'',quantity:1,term_days:/^\d+$/.test(v.term)?Number(v.term):null};
  try{const lines=FMZInvoiceEditor.body(v),s=d.creditOf?get(d.creditOf).data.document.settings:currentSettings(body.date),totals=M.invoiceTotals(lines,['kor','exempt'].includes(s.vat_status)?0:Number(s.vat_basis_points??0));Object.assign(body,lines,{gross_cents:totals.grossCents,discount_cents:totals.discountCents,quantity:lines.lines[0].quantity_milli/1000});}catch(e){if(strict)throw e;}
  if(!d.creditOf)body.settings_id=list('settings').filter(r=>r.status==='confirmed'&&r.date<=body.date).at(-1)?.id||null;
  if(strict){M.date(v.date);M.date(v.serviceDate);if(!body.customer.name.trim()||!body.customer.address.trim())throw Error('Vul klantnaam en volledig adres in.');if(!body.description.trim()||!body.service_extent.trim()||!body.quantity||body.term_days===null||body.term_days>3650)throw Error('Controleer omschrijving, omvang, hoeveelheid en betaaltermijn.');}
  return body;
 }
 function previewDocument(d,body=draftPayload(d,true)){const original=d.creditOf?get(d.creditOf).data.document:null,s=original?.settings||currentSettings(body.date),credited=d.creditOf?-list('invoice').filter(r=>r.status==='posted'&&r.parent_id===d.creditOf).reduce((n,r)=>n+r.data.document.totalCents,0):0;return FMZInvoiceEditor.document(body,s,d.logo,original,credited);}
 function invoicePreview(d){
  const t=modal?.querySelector('.invoice-draft-preview');if(!t)return;clearTimeout(d.previewTimer);d.previewRevision=(d.previewRevision||0)+1;const revision=d.previewRevision,root=modal.querySelector('[data-pdf-preview]'),note=modal.querySelector('[data-preview-status]');
  try{const b=draftPayload(d),doc=previewDocument(d,b);modal.querySelector('[name=amount]').value=(Math.abs(doc.subtotalCents)/100).toFixed(2);for(const [name,shown]of [['discount',d.values.discountMode!=='percent'],['discountPercent',d.values.discountMode==='percent']])modal.querySelector(`[name=${name}]`).closest('label').hidden=!shown;
   t.innerHTML=`<p>Subtotaal ${M.money(doc.subtotalCents)}</p><p>Korting − ${M.money(doc.discountInputCents)}</p>${info(b.discountNote)}<p>${doc.settings.confirmed?'Btw '+doc.vatBasisPoints/100+'% '+M.money(doc.vatCents):'Fiscale instellingen nog niet bevestigd'}</p><p class="invoice-total"><strong>${d.creditOf?'Te crediteren':'Te betalen'} ${M.money(doc.totalCents)}</strong></p>`;
   note.textContent='A4-voorbeeld bijwerken…';d.previewTimer=setTimeout(async()=>{const gen=epoch;try{d.logo ||= await logo();assertOwner(gen);if(invoice!==d||revision!==d.previewRevision)return;const bytes=await FMZInvoices.pdf({...doc,logo:d.logo});if(invoice!==d||revision!==d.previewRevision)return;await FMZInvoices.renderPDF(bytes,root,()=>invoice===d&&revision===d.previewRevision&&gen===epoch);if(invoice===d&&revision===d.previewRevision)note.textContent='PDF-voorbeeld — nummer volgt bij definitief opslaan.';}catch(e){if(gen===epoch&&revision===d.previewRevision)note.textContent='Voorbeeld niet gereed: '+e.message;}},650);
  }catch(e){t.textContent=e.message;note.textContent='Vul geldige factuurregels en bedragen in voor het A4-voorbeeld.';root.replaceChildren();}
 }

 async function persistInvoice(d,strict=false){if(d.owner!==owner||!ready()||d.busy||d.conflict)return false;clearTimeout(invoiceTimer);if(!d.dirty&&d.version)return true;const gen=epoch;let acknowledged=false;d.busy=true;
  try{const payload=d.pending||{id:d.id,version:d.version,data:draftPayload(d,strict)};d.pending=payload;d.message.textContent='Concept opslaan…';const saved=await (d.inflight=command('draft',payload));assertOwner(gen);acknowledged=true;d.pending=null;d.version=saved.version;const current=JSON.stringify(draftPayload(d));d.dirty=current!==JSON.stringify(payload.data);d.message.textContent=d.dirty?'Nieuwere invoer nog niet opgeslagen…':'Concept opgeslagen';if(snapshot){const ix=snapshot.records.findIndex(r=>r.id===d.id);if(ix<0)snapshot.records.push(saved);else snapshot.records[ix]=saved;revision++;}return !d.dirty;
  }catch(e){if(gen===epoch){if(e.code==='PT409'){d.conflict=true;d.pending=null;}else if(e.code&&/^(22|23|42|P0001)/.test(e.code))d.pending=null;d.message.textContent='Niet opgeslagen — '+e.message;}return false;}
  finally{if(gen===epoch){d.busy=false;if(acknowledged&&d.dirty&&!d.conflict&&!d.pending&&invoice===d)invoiceTimer=setTimeout(()=>persistInvoice(d),650);}}
 }
 async function refreshInvoice(){const d=invoice;if(!d||d.busy)return;await refresh();const r=get(d.id);if(!r)throw Error('Nog geen serverconcept; jouw invoer blijft in dit tabblad.');if(r.status==='posted'){d.dirty=false;invoiceDrafts.delete(d.id);showModal(r.number,info('Deze factuur is definitief opgeslagen. Het lokale concept kan deze niet overschrijven.')+btn('PDF downloaden','invoice-pdf',r.id));return;}d.remote=r;const compare=document.createElement('section');compare.className='full acc-notice';compare.innerHTML=`<h3>Serverconcept (versie ${r.version})</h3><pre>${esc(JSON.stringify(r.data.raw||r.data,null,2))}</pre><p>Jouw invoer blijft hierboven staan. Vergelijk voordat je die op de vernieuwde versie opslaat.</p>${btn('Gebruik mijn concept op vernieuwde versie','invoice-use-mine')}`;modal.querySelector('form').append(compare);}
 async function logo(){const response=await fetch(FMZ_LOGO_FILE,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Bedrijfslogo laden mislukt.');const blob=await response.blob();return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Logo lezen mislukt'));reader.readAsDataURL(blob);});}
 async function saveInvoice(button){const d=invoice;if(!d||d.finalBusy)return;if(d.busy){try{await d.inflight;}catch{}if(d.busy||invoice!==d)return;}assertOwner();const gen=epoch,f=button.closest('form');if(!pending)d.values={...d.values,...FMZInvoiceEditor.read(f)};d.finalBusy=true;button.disabled=true;const closeButton=modal.querySelector('[data-acc-action=close]');if(closeButton)closeButton.disabled=true;f.querySelectorAll('input,textarea,select').forEach(e=>e.disabled=true);clearTimeout(invoiceTimer);
  try{draftPayload(d,true);if(d.conflict)throw Error('Vergelijk eerst het vernieuwde serverconcept.');const saved=await persistInvoice(d,true);if(!saved)throw Error('Concept heeft nog geen bevestigde opslag. Probeer opnieuw.');
   d.busy=true;f.querySelectorAll('input,textarea,select').forEach(e=>e.disabled=true);d.message.textContent='Definitief opslaan…';
   let record=get(d.id);if(record?.status!=='posted'){
    if(!d.logo)d.logo=await logo();assertOwner(gen);
    if(record.data.logo!==d.logo){const data={...record.data,logo:d.logo};record=await command('draft',{id:d.id,version:d.version,data});d.version=record.version;d.logoSaved=true;snapshot.records[snapshot.records.findIndex(r=>r.id===d.id)]=record;}
    await FMZInvoices.pdf(previewDocument(d,record.data));
    record=await command('final_invoice',{id:d.id,version:d.version});assertOwner(gen);snapshot.records[snapshot.records.findIndex(r=>r.id===d.id)]=record;revision++;
   }
   d.dirty=false;invoiceDrafts.delete(d.id);d.message.textContent='Factuur opgeslagen — PDF archiveren…';await ensurePDF(record);assertOwner(gen);d.message.textContent='Opgeslagen — PDF-download gestart';await downloadInvoice(record.id);await refresh();render(true);
   button.textContent='PDF opnieuw downloaden';button.dataset.accAction='invoice-pdf';
  }catch(e){if(gen===epoch){const posted=get(d.id)?.status==='posted';d.message.textContent=posted?'Factuur opgeslagen — PDF nog niet gereed: '+e.message:'Niet definitief opgeslagen — '+e.message;if(posted){button.textContent='PDF opnieuw opslaan / downloaden';button.dataset.accAction='invoice-pdf';}else if(e.code==='PT409')d.conflict=true;}}
  finally{if(gen===epoch){d.busy=false;d.finalBusy=false;button.disabled=false;if(closeButton)closeButton.disabled=false;if(get(d.id)?.status!=='posted'&&!pending)f.querySelectorAll('input,textarea,select').forEach(e=>e.disabled=false);}}
 }
 async function viewInvoice(id,sharing=false){
  const r=get(id);if(!r?.data.document)throw Error('Definitieve factuur ontbreekt.');const gen=epoch,f=await ensurePDF(r),blob=await fileBlob(f);assertOwner(gen);
  showModal(r.number,`<p>Dit is de originele opgeslagen PDF. Latere betalingen en correcties staan bij Boekingen en betalingen.</p><div class="acc-actions">${btn('PDF downloaden','invoice-pdf',id)}${sharing?'<button type="button" class="primary-btn" data-native-share>Delen via je apparaat</button>':''}</div><div class="invoice-a4"><div data-pdf-preview></div></div><p data-form-status role="status"></p>`);
  const root=modal.querySelector('[data-pdf-preview]');await FMZInvoices.renderPDF(new Uint8Array(await blob.arrayBuffer()),root);assertOwner(gen);
  const share=modal?.querySelector('[data-native-share]');if(share){const file=new File([blob],r.number+'.pdf',{type:'application/pdf'});share.onclick=async()=>{try{if(!navigator.canShare?.({files:[file]}))throw Error('Dit apparaat ondersteunt geen bestanden delen. Download de PDF en deel die vanuit Bestanden.');await navigator.share({files:[file],title:r.number});await command('invoice_sent',{id});await refresh();status('Deelvenster afgerond; factuur als gedeeld geregistreerd.');}catch(e){if(e.name!=='AbortError')modal?.querySelector('[data-form-status]')?.replaceChildren(document.createTextNode(e.message));}};}
 }
 const pdfBytes=new Map();
 async function ensurePDF(r){let f=snapshot.files.find(f=>f.record_id===r.id&&f.kind==='invoice_pdf');if(f?.status==='ready')return f;let bytes=pdfBytes.get(r.id);if(!bytes){bytes=await FMZInvoices.pdf(copy(r.data.document));pdfBytes.set(r.id,bytes);}f=await upload(new File([bytes],r.number+'.pdf',{type:'application/pdf'}),{record_id:r.id,kind:'invoice_pdf'});const ix=snapshot.files.findIndex(x=>x.id===f.id);if(ix<0)snapshot.files.push(f);else snapshot.files[ix]=f;return f;}
 async function downloadInvoice(id){assertOwner();let r=get(id);if(!r){await refresh();r=get(id);}if(!r||r.kind!=='invoice'||r.status!=='posted')throw Error('Maak het concept eerst definitief.');const f=await ensurePDF(r);downloadBlob(await fileBlob(f),r.number+'.pdf');if(invoice?.id===id)invoice.message.textContent='Opgeslagen — PDF-download gestart';}
 function importModal(){const map=importData.map;showModal('CSV-kolommen en importvoorbeeld',`<div class="acc-form" data-import-map>${Object.entries({date:'Datum',amount:'Bedrag',direction:'Af / Bij (optioneel)',account:'Rekening (optioneel)',counterparty:'Tegenrekening (optioneel)',description:'Omschrijving',note:'Mededelingen (optioneel)',reference:'Unieke transactie-ID (indien aanwezig)'}).map(([k,label])=>select(k,label,[[-1,'Geen kolom'],...importData.rows[0].map((h,i)=>[i,h])],map[k])).join('')}</div>${btn('Voorbeeld controleren','import-preview')}<div data-import-preview></div>`);importPreview();}
 async function importPreview(){if(!importData)return;importData.map=Object.fromEntries([...modal.querySelectorAll('[data-import-map] select')].map(e=>[e.name,Number(e.value)]));if(importData.map.date<0||importData.map.amount<0)throw Error('Koppel minimaal datum en bedrag.');const account=get(importData.account_id);if(!account)throw Error('Kies eerst een bankrekening.');const rows=await M.importRows(importData.rows,importData.map,account,list('bank'));importData.preview=rows;modal.querySelector('[data-import-preview]').innerHTML=info('Controleer rekening, tekens en datums. Eerder geïmporteerde of identieke regels worden niet opnieuw geselecteerd. Zonder bankreferentie kan een identieke nieuwe betaling een controlepunt zijn.')+`<div class="acc-import-rows">${rows.map((r,i)=>`<label class="acc-import-row"><input type="checkbox" data-import-row="${i}" ${r.selected?'checked':''} ${r.error?'disabled':''}><span>Regel ${r.line}: ${esc(r.date||'')} · ${Number.isInteger(r.cents)?M.money(r.cents):''} · ${esc(r.description||'')}<small>${esc(r.error||(r.duplicate?'Al geïmporteerd':r.ambiguous?'Identieke regel — expliciet controleren':'Nieuw'))}</small></span></label>`).join('')}</div>${area('duplicateReason','Bij opnieuw geselecteerde identieke regels: waarom is dit een afzonderlijke echte transactie?')}${btn('Geselecteerde mutaties importeren','import-confirm','','primary-btn')}<p data-form-status role="status"></p>`;}
 async function importConfirm(button){if(importData?.busy)return;const d=importData;if(!d)return;d.busy=true;button.disabled=true;const gen=epoch;try{if(!d.payload){const selected=[...modal.querySelectorAll('[data-import-row]:checked')].map(e=>d.preview[Number(e.dataset.importRow)]),reason=modal.querySelector('[name=duplicateReason]').value.trim();if(!selected.length)throw Error('Geen nieuwe mutaties geselecteerd.');if(selected.some(r=>r.duplicate||r.ambiguous)&&reason.length<10)throw Error('Leg vast waarom de identieke mutatie afzonderlijk geboekt moet worden.');
    if(!d.file_id)d.file_id=(await upload(d.file,{kind:'bank_import'})).id;
    const rows=selected.map(r=>{const row=copy(r);if(r.duplicate||r.ambiguous){row.original_source_key=r.source_key;row.source_key=r.source_key+':review:'+r.id;row.duplicate_reason=reason;}return row;});d.payload={id:d.id,data:{file_id:d.file_id,account_id:d.account_id,rows,mapping:d.map,date:today()}};
   }
   const result=d.result||await command('import',d.payload);d.result=result;assertOwner(gen);await refresh();modal.close();modal.remove();modal=null;importData=null;render(true);status(`${result.data.imported_ids.length} mutaties opgeslagen; ${result.data.skipped} reeds aanwezig.`);
  }catch(e){if(gen===epoch)modal.querySelector('[data-form-status]').textContent=(d.result?'Import opgeslagen — overzicht vernieuwen mislukt: ':'Niet geïmporteerd — ')+e.message;}finally{if(gen===epoch){d.busy=false;button.disabled=false;}}
 }
 async function exportAll(){assertOwner();status('Export samenstellen en originele bestanden controleren…');await refresh();const s=copy(snapshot),p=M.project(s),zip={},index=[],missing=s.files.filter(f=>f.status!=='ready');if(missing.length)throw Error(`${missing.length} uploads zijn nog niet bevestigd. Rond deze af voor een volledige export.`);
  zip['administratie.json']=fflate.strToU8(JSON.stringify(s,null,2));
  zip['boekingen.csv']=fflate.strToU8(M.csvOut([['Datum','Journaal-ID','Bron-ID','Omschrijving','Rekening','Debet centen','Credit centen','Referentie'],...s.lines.map(l=>{const j=s.journals.find(j=>j.id===l.journal_id);return [j.date,j.id,j.record_id,j.description,l.account_code,Math.max(0,l.cents),Math.max(0,-l.cents),l.reference_id]})]));
  zip['facturen.csv']=fflate.strToU8(M.csvOut([['ID','Nummer','Status','Datum','Klant','Omschrijving','Oorspronkelijk centen','Korting centen','Totaal centen','Btw centen','Credit op'],...s.records.filter(r=>r.kind==='invoice').map(r=>{const d=r.data.document||{};return [r.id,r.number,r.status,r.date,d.customer?.name||r.data.customer?.name,d.description||r.data.description,d.grossCents,d.discountCents,d.totalCents,d.vatCents,r.parent_id]})]));
  zip['bankmutaties.csv']=fflate.strToU8(M.csvOut([['ID','Datum','Rekening','Bedrag centen','Omschrijving','Bronherkenning'],...s.records.filter(r=>r.kind==='bank').map(r=>[r.id,r.date,r.data.account_id,r.data.cents,r.data.description,r.source_key])]));
  zip['uitgaven.csv']=fflate.strToU8(M.csvOut([['ID','Datum','Leverancier','Omschrijving','Bedrag centen','Kosten centen','Voorbelasting centen','Privévoorschot','Controlepunten'],...s.records.filter(r=>r.kind==='expense').map(r=>[r.id,r.date,r.data.supplier,r.data.description,r.data.gross_cents,r.data.cost_cents,r.data.input_vat_cents,r.data.paid_privately,(r.data.flags||[]).join('; ')])]));
  for(const f of s.files){const blob=await fileBlob(f),name='bijlagen/'+f.id+'/'+f.original_name.replace(/[^a-zA-Z0-9._-]/g,'_');zip[name]=new Uint8Array(await blob.arrayBuffer());index.push({...f,export_path:name});}
  zip['bestandsindex.json']=fflate.strToU8(JSON.stringify(index,null,2));zip['bestandsindex.csv']=fflate.strToU8(M.csvOut([['Bestand-ID','Boeking-ID','Soort','Originele naam','Exportpad','SHA-256','Bewaren t/m'],...index.map(f=>[f.id,f.record_id,f.kind,f.original_name,f.export_path,f.sha256,f.keep_until||'Onbekend: blijven bewaren'])]));
  const html=`<!doctype html><html lang="nl"><meta charset="utf-8"><title>FitMetZorge administratie-export</title><style>body{font:16px system-ui;margin:3rem;max-width:1100px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:.5rem;text-align:left}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style><h1>Administratie-export ${esc(s.organization.name)}</h1><p>Omzet excl. btw ${M.money(p.revenue)} · kosten ${M.money(p.cost)} · resultaat ${M.money(p.profit)}. Dit is geen beschikbare bankstand.</p><h2>Controlepunten</h2><ul>${p.flags.map(f=>'<li>'+esc(f)+'</li>').join('')}</ul><h2>Rekeningen en standen</h2><table><tr><th>Rekening</th><th>Getekende stand (debet positief)</th></tr>${p.accounts.map(a=>'<tr><td>'+esc(a.code+' '+a.name)+'</td><td>'+M.money(a.cents)+'</td></tr>').join('')}</table><h2>Facturen en bronnen</h2>${s.records.map(r=>`<article id="${r.id}"><h3>${esc(r.number||r.kind)} · ${esc(r.date)}</h3><pre>${esc(JSON.stringify(r.data,(k,v)=>k==='logo'?'[ingebed bedrijfslogo]':v,2))}</pre>${index.filter(f=>f.record_id===r.id).map(f=>`<p><a href="${esc(f.export_path)}">${esc(f.original_name)}</a></p>`).join('')}</article>`).join('')}<h2>Alle originele bestanden</h2>${index.map(f=>`<p><a href="${esc(f.export_path)}">${esc(f.original_name)}</a> · ${esc(f.record_id||'nog geen boeking')} · SHA-256 ${f.sha256}</p>`).join('')}<p>Volledige data en wijzigingsgeschiedenis: administratie.json. CSV-bedragen staan op centen. Geen aangiftebestand.</p></html>`;
  zip['LEESMIJ.html']=fflate.strToU8(html);const payload={id:uid(),data:{file_count:index.length}};await command('export',payload);downloadBlob(new Blob([fflate.zipSync(zip,{level:6})],{type:'application/zip'}),`FitMetZorge-administratie-${today()}.zip`);status('Export gecontroleerd — download gestart');
 }
 window.addEventListener('beforeunload',e=>{if(pending||[...formDrafts.values()].some(d=>d.dirty)||[...invoiceDrafts.values()].some(d=>d.dirty)){e.preventDefault();e.returnValue='';}});
 return {init,render,lock,get access(){return access},get ready(){return ready()},get snapshot(){return snapshot},refresh,command,newInvoice,openInvoice,saveInvoice,downloadInvoice,legacyCard,exportAll};
})();
