/* Owner agreement editor; transient drafts only. Explicit confirmation, never autosave. */
window.FMZBilling=(()=>{
 const B=FMZBillingPeriods,M=FMZAccountingModel,esc=s=>escapeHTML(String(s??'')),today=()=>todayISO();let dialog=null,busy=false,draft=null;
 const versions=id=>(FMZAccounting.snapshot?.agreements||[]).filter(v=>v.client_id===id),get=(id,at=today())=>B.active(versions(id),id,at);
 function allowed(){if(!FMZAccounting.ready)throw Error('Alleen de geverifieerde owner kan klantafspraken beheren.');}
 const field=(name,title,value,type='text')=>`<label class="field"><span>${esc(title)}</span><input name="${name}" type="${type}" value="${esc(value)}" required></label>`;
 const select=(name,title,options,value)=>`<label class="field"><span>${esc(title)}</span><select name="${name}">${options.map(([id,label])=>`<option value="${id}" ${id===value?'selected':''}>${esc(label)}</option>`).join('')}</select></label>`;
 const note=v=>v.cycle==='four_weeks'?'Facturatie iedere 4 weken (28 dagen), 13 betaalperiodes per jaar. De cyclus loopt zonder reset door over de jaargrens.':v.cycle==='calendar_month'?'Serviceperiode: eerste tot en met laatste dag van de maand. Factuurdatum standaard aan het einde van de maand.':'Geen terugkerende betaalperiode.';
 function summary(v,at=today()){
  if(!v)return '<p>Er is nog geen bevestigde klantafspraak. Nieuwe overeenkomsten staan standaard op vier weken.</p>';
  let p;try{p=B.period(v,at);}catch{p=B.period(v,v.effective_from);}
  const r=FMZAccounting.snapshot.records.find(r=>r.data.billing?.agreementVersionId===v.id&&r.data.billing?.start===p.start&&!r.parent_id&&!r.data.credit_of),projection=M.project(FMZAccounting.snapshot),status=r?.status==='posted'?projection.invoices.find(x=>x.id===r.id)?.statusLabel:r?'Concept':'Nog geen factuur';
  let next=p,nextVersion=v;
  if(v.enabled&&r?.status==='posted'){
   next=null;
   if(p.nextStart){nextVersion=get(v.client_id,p.nextStart);if(nextVersion?.enabled)next=B.period(nextVersion,p.nextStart);}
  }
  return `<p><strong>${esc(v.package_label)} · ${M.money(v.amount_cents)} ${B.label(v.cycle)}</strong></p><p>Ingangsdatum: ${B.display(v.effective_from)} · versie ${v.version}</p><p>Serviceperiode: ${B.display(p.start)} t/m ${B.display(p.end)}</p><p>${v.enabled?'Volgende factuurdatum: '+(next?B.display(next.invoiceDate):'geen geplande vervolgfactuur')+' · Huidige factuur: '+esc(status):'Geen pakketfacturen — uitgesloten van voorstellen'}</p><p>${esc(note(v))}</p>`;
 }
 function close(force=false){if(busy&&!force)return;if(!force&&draft?.dirty&&!confirm('Deze klantafspraak is nog niet opgeslagen. Sluiten en dit concept verwerpen?'))return;dialog?.remove();dialog=null;draft=null;busy=false;}
 function show(title,body){close(true);dialog=document.createElement('dialog');dialog.className='acc-dialog';dialog.innerHTML=`<header><h2>${esc(title)}</h2><button type="button" data-billing-close class="secondary-btn">Sluiten</button></header>${body}<p data-billing-status role="status"></p>`;dialog.querySelector('[data-billing-close]').onclick=()=>close();dialog.addEventListener('cancel',e=>{e.preventDefault();close();});document.body.append(dialog);dialog.showModal();return dialog;}
 function message(text){dialog?.querySelector('[data-billing-status]')?.replaceChildren(document.createTextNode(text));}
 function changed(){if(!dialog)return;const f=dialog.querySelector('form');if(draft)draft.dirty=true;const c=B.catalog.find(p=>p.id===f.elements.package_id.value);if(!c)return;const cycle=f.elements.cycle;cycle.disabled=!c.recurring;if(!c.recurring)cycle.value='none';else if(cycle.value==='none')cycle.value='four_weeks';
  const v={package_label:c.label,amount_cents:c.cents,cycle:cycle.value,effective_from:f.elements.effective_from.value};const out=f.querySelector('[data-billing-summary]');try{const p=B.period(v,v.effective_from);out.textContent=`${c.label}: ${M.money(c.cents)} ${B.label(v.cycle)} vanaf ${B.display(v.effective_from)}. Eerste serviceperiode ${B.display(p.start)} t/m ${B.display(p.end)}. ${f.elements.enabled.checked?'Pakketfacturen toegestaan.':'Geen pakketfacturen.'} Eerdere afspraken en definitieve facturen blijven ongewijzigd.`;}catch{out.textContent='Kies een geldige ingangsdatum.';}f.elements.confirmed.checked=false;
 }
 async function openAgreement(id){allowed();const client=state.clients.find(c=>c.id===id);if(!client)throw Error('Klant ontbreekt');const all=versions(id),last=all.at(-1),current=get(id),pkg=B.catalog.find(p=>p.id===last?.package_id)||B.catalog.find(p=>p.id===client.profile?.package)||B.catalog[0];
  let from=today();if(last&&last.enabled&&last.cycle!=='none'){let p=B.period(last,from<last.effective_from?last.effective_from:from);from=p.nextStart;}
  const cycle=last?.cycle||'four_weeks';if(cycle==='calendar_month'&&from.slice(-2)!=='01'){const d=B.date(from);d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+1);from=d.toISOString().slice(0,10);}
  show('Klantafspraak: '+client.name,summary(current)+`<details><summary>Eerdere en geplande versies (${all.length})</summary>${all.map(v=>`<article class="acc-notice"><strong>Versie ${v.version}</strong>${summary(v,v.effective_from)}<p>${esc(v.reason)}</p></article>`).join('')}</details><form class="acc-form" data-billing-form>
  ${select('package_id','Pakket',B.catalog.map(p=>[p.id,`${p.label} — ${M.money(p.cents)} incl. btw`]),pkg.id)}
  ${select('cycle','Betaalperiode',[['four_weeks','Vier weken — standaard voor nieuwe overeenkomsten'],['calendar_month','Kalendermaand — bestaande/afwijkende afspraak'],['none','Eenmalig — alleen losse training of strippenkaart']],cycle)}
  ${field('effective_from','Ingangsdatum nieuwe versie',from,'date')}<label class="field"><span>Toelichting wijziging</span><input name="reason" value=""></label>
  <label class="acc-check full"><input name="enabled" type="checkbox" ${last?.enabled===false?'':'checked'}>Pakketfacturen voor deze klant toestaan</label>
  <p class="full acc-notice">Kies een aansluitende periodegrens bij een wijziging. Kalendermaanden beginnen op de eerste; vierwekenperiodes duren exact 28 dagen. Er worden geen halve periodes of prijsomrekeningen gemaakt. Duo houdt de bestaande pakketprijs; deze wordt niet automatisch verdubbeld of gehalveerd.</p>
  <p class="full" data-billing-summary></p><label class="acc-check full"><input name="confirmed" type="checkbox" required>Ik heb pakket, bedrag, betaalperiode en ingangsdatum gecontroleerd</label><button class="primary-btn" type="submit">Nieuwe afspraakversie opslaan</button></form>`);
  draft={id,version:last?.version||0,dirty:false};const f=dialog.querySelector('form');f.addEventListener('input',e=>{if(e.target.name==='confirmed'){draft.dirty=true;return;}changed();});f.addEventListener('change',e=>{if(e.target.tagName==='SELECT')changed();});changed();draft.dirty=false;
  f.onsubmit=async e=>{e.preventDefault();if(busy)return;allowed();if(!f.reportValidity())return;const origin=onlineProfile.id,payload=draft.pending||{client_id:id,expected_version:draft.version,package_id:f.elements.package_id.value,cycle:f.elements.cycle.value,effective_from:f.elements.effective_from.value,enabled:f.elements.enabled.checked,confirmed:f.elements.confirmed.checked,reason:f.elements.reason.value};draft.pending=payload;busy=true;f.querySelectorAll('input,select,button').forEach(x=>x.disabled=true);message('Afspraak opslaan…');
   try{await FMZAccounting.command('save_agreement',payload,'fmz_billing_command');if(onlineProfile?.id!==origin)throw Error('Sessie gewijzigd');await FMZAccounting.refresh();draft.dirty=false;message('Opgeslagen — eerdere facturen zijn ongewijzigd');close(true);renderAll();}
   catch(e){if(!dialog)return;if(e.code&&/^(PT409|22|23|42|P0001)/.test(e.code))draft.pending=null;message('Niet opgeslagen — '+e.message);}
   finally{busy=false;if(dialog){f.querySelectorAll('input,select,button').forEach(x=>x.disabled=!!draft.pending);f.querySelector('[type=submit]').disabled=false;if(draft.pending){f.querySelector('[type=submit]').textContent='Dezelfde bevestiging opnieuw opvragen';message('Uitkomst nog niet bevestigd — probeer dezelfde handeling opnieuw. Jouw invoer blijft bewaard.');}else f.elements.cycle.disabled=!B.catalog.find(p=>p.id===f.elements.package_id.value)?.recurring;}}
  };
 }
 async function openInvoiceChooser(){allowed();const selected=client();show('Pakketfactuur: periode kiezen',`<form class="acc-form" data-billing-invoice>${select('client_id','Klant',state.clients.map(c=>[c.id,c.name]),selected?.id)}${field('at_date','Datum binnen de te factureren serviceperiode',today(),'date')}<div class="full" data-period-choice></div><div class="full acc-actions"><button class="primary-btn" type="submit">Concept openen</button><button class="secondary-btn" type="button" data-edit-agreement>Klantafspraak beheren</button></div></form>`);
  const f=dialog.querySelector('form'),update=()=>{const c=f.elements.client_id.value,at=f.elements.at_date.value;try{const v=get(c,at);f.querySelector('[data-period-choice]').innerHTML=summary(v,at);if(v){const period=B.period(v,at),old=FMZAccounting.snapshot.records.filter(r=>r.kind==='invoice'&&!r.parent_id&&!r.data.credit_of&&!r.data.billing&&r.data.client_id===c&&r.date>=period.start&&r.date<=period.end);if(old.length)f.querySelector('[data-period-choice]').innerHTML+='<aside class="acc-notice"><strong>Bestaande facturen controleren</strong><p>Er zijn '+old.length+' facturen of concepten zonder vastgelegde serviceperiode. Kies bewust een bestaand concept; bedragen en invoer blijven behouden. Een definitieve factuur wordt niet aangepast.</p>'+select('adopt_draft','Bestaand concept voor deze periode gebruiken',[['','Geen concept gekozen'],...old.filter(r=>r.status==='draft').map(r=>[r.id,r.data.description||'Bestaand concept'])],'')+'</aside>';}}catch(e){f.querySelector('[data-period-choice]').textContent=e.message;}};f.addEventListener('change',update);update();f.querySelector('[data-edit-agreement]').onclick=()=>openAgreement(f.elements.client_id.value);
  let pending=null;
  f.onsubmit=async e=>{e.preventDefault();if(busy||!f.reportValidity())return;busy=true;pending??={client_id:f.elements.client_id.value,at_date:f.elements.at_date.value,...(f.elements.adopt_draft?.value?{adopt_draft:f.elements.adopt_draft.value}:{})};f.querySelectorAll('input,select,button').forEach(x=>x.disabled=true);message('Periodeconcept ophalen…');try{const r=await FMZAccounting.command('prepare_invoice',pending,'fmz_billing_command');await FMZAccounting.refresh();close(true);await FMZAccounting.openInvoice(r.id);}catch(e){if(e.code&&/^(PT409|22|23|42|P0001)/.test(e.code))pending=null;message('Niet geopend — '+e.message+(pending?' Probeer dezelfde aanvraag opnieuw.':''));}finally{busy=false;if(dialog){f.querySelectorAll('input,select,button').forEach(x=>x.disabled=!!pending);f.querySelector('[type=submit]').disabled=false;}}};
 }
 function controls(id){return FMZAccounting.ready?`<button type="button" class="secondary-btn" data-client-agreement="${esc(id)}">Klantafspraak / betaalperiode</button>`:'';}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-client-agreement]');if(b){e.preventDefault();openAgreement(b.dataset.clientAgreement).catch(e=>alert(e.message));}});
 window.addEventListener('beforeunload',e=>{if(draft?.dirty){e.preventDefault();e.returnValue='';}});
 return {get,summary,controls,openAgreement,openInvoiceChooser,lock:()=>close(true)};
})();
