/* Private in-memory image viewer. Only vector annotations cross the checked RPC. */
(()=>{
 const drafts=new Map();let current=null,timer;const dialog=document.createElement('dialog');dialog.id='photoViewer';dialog.innerHTML=`<header><strong>Foto bekijken</strong><button type="button" data-photo-close>Sluiten</button></header><div class="photo-toolbar"><button data-photo-tool="pan">Verschuiven</button><button data-photo-zoom="1.25">+</button><button data-photo-zoom="0.8">−</button><button data-photo-reset>Passend</button><span class="trainer-tools"><button data-photo-tool="draw">Tekenen</button><button data-photo-tool="erase">Gum</button><label>Kleur <input id="photoColor" type="color" value="#ff3344"></label><label>Lijndikte <input id="photoWidth" type="range" min="2" max="35" value="6"></label><button data-photo-undo>Ongedaan maken</button><button data-photo-redo>Opnieuw</button><button data-photo-share>Delen met lid</button></span><button data-photo-retry>Opnieuw opslaan</button><span id="photoStatus" role="status"></span></div><div class="photo-viewport"><div class="photo-stage"><img alt="Originele voortgangsfoto" draggable="false"><canvas></canvas></div></div>`;document.body.append(dialog);
 const stage=dialog.querySelector('.photo-stage'),img=stage.querySelector('img'),canvas=stage.querySelector('canvas'),ctx=canvas.getContext('2d'),status=dialog.querySelector('#photoStatus');
 const copy=x=>JSON.parse(JSON.stringify(x));const key=b=>JSON.stringify([b.owner,b.client_id,b.week,b.day,b.slot,b.source_hash]);
 const dirty=b=>!!b&&(b.pending||JSON.stringify(b.strokes)!==JSON.stringify(b.saved));
 function showStatus(b,text){if(current===b)status.textContent=text;}
 function paint(){if(!current)return;ctx.clearRect(0,0,canvas.width,canvas.height);for(const s of current.strokes){ctx.globalCompositeOperation=s.tool==='erase'?'destination-out':'source-over';ctx.strokeStyle=s.color;ctx.lineWidth=s.width*canvas.width;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();s.points.forEach(([x,y],i)=>i?ctx.lineTo(x*canvas.width,y*canvas.height):ctx.moveTo(x*canvas.width,y*canvas.height));if(s.points.length===1){const [x,y]=s.points[0];ctx.lineTo(x*canvas.width+.1,y*canvas.height+.1)}ctx.stroke();}ctx.globalCompositeOperation='source-over';}
 function fit(){if(!current||!img.naturalWidth)return;const rect=dialog.querySelector('.photo-viewport').getBoundingClientRect(),ratio=img.naturalWidth/img.naturalHeight;const w=Math.min(rect.width-16,(rect.height-16)*ratio);stage.style.width=w+'px';stage.style.height=w/ratio+'px';stage.style.transform=`translate(${current.x}px,${current.y}px) scale(${current.zoom})`;}
 async function persist(b,share=false){if(!b||b.role!=='trainer')return true;clearTimeout(timer);const task=async()=>{if(onlineProfile?.id!==b.owner)return false;try{
  if(!b.pending&&!dirty(b)&&!share)return true;
  b.pending ||= {client_id:b.client_id,week:b.week,day:b.day,slot:b.slot,source_hash:b.source_hash,action:share?'share':'save',strokes:copy(b.strokes),expected_version:b.version,request_id:crypto.randomUUID()};const sent=b.pending;showStatus(b,'Opslaan…');
  const {data,error}=await supabaseClient.rpc('fmz_photo_annotation',sent);if(error){if(error.code==='PT409'||error.code==='42501')b.pending=null;throw error;}if(onlineProfile?.id!==b.owner)return false;if(!data||data.source_hash!==b.source_hash||data.version!==sent.expected_version+1)throw Error('Geen bevestiging');b.version=data.version;b.saved=copy(sent.strokes);b.pending=null;showStatus(b,dirty(b)?'Opslaan…':sent.action==='share'?'Gedeeld met lid':'Concept opgeslagen');if(dirty(b))timer=setTimeout(()=>persist(b),650);if(share&&sent.action!=='share')return false;return true;
 }catch(e){showStatus(b,e.code==='PT409'?'Conflict — sluit en heropen na veiligstellen':'Niet opgeslagen — opnieuw proberen');return false;}};b.queue=(b.queue||Promise.resolve()).then(task,task);return b.queue;}
 async function open(day,slot){if(!onlineProfile)return;const c=client(),week=activeWeekStart(),owner=onlineProfile.id,role=onlineProfile.role,source=c.dailyWeightByWeek?.[week]?.[day]?.[slot];if(!/^data:image\/(jpeg|png|webp|gif);base64,/.test(source||'')){alert('Deze foto is niet beschikbaar in de privé-opslag.');return;}
  if(!(await saveStateToCloud()).ok){alert('Sla de foto eerst op. Je invoer blijft in dit tabblad.');return;}
  const binding={owner,role,client_id:c.id,week,day,slot};const {data,error}=await supabaseClient.rpc('fmz_photo_annotation',{client_id:c.id,week,day,slot});if(onlineProfile?.id!==owner)return;if(error){alert('Foto openen mislukt. Probeer opnieuw.');return;}
  Object.assign(binding,{...data,strokes:copy(data.strokes),saved:copy(data.strokes),redo:[],zoom:1,x:0,y:0,tool:'pan'});current=drafts.get(key(binding))||binding;drafts.set(key(binding),current);dialog.querySelector('.trainer-tools').hidden=role!=='trainer';dialog.querySelector('[data-photo-retry]').hidden=role!=='trainer';status.textContent=role==='trainer'?'Trainerconcept — deel pas als het klaar is':data.shared_at?'Gedeelde aantekeningen':'Originele foto';img.onload=()=>{const ratio=img.naturalWidth/img.naturalHeight;canvas.width=Math.max(1,Math.round(1600*Math.min(1,ratio)));canvas.height=Math.max(1,Math.round(1600*Math.min(1,1/ratio)));fit();paint()};img.src=source;dialog.showModal();if(img.complete){fit();paint();}}
 function close(){pointer=null;if(current&&dirty(current))persist(current);dialog.close();img.removeAttribute('src');ctx.clearRect(0,0,canvas.width,canvas.height);current=null;}
 function lock(){pointer=null;clearTimeout(timer);if(current)drafts.set(key(current),current);dialog.close();img.removeAttribute('src');ctx.clearRect(0,0,canvas.width,canvas.height);current=null;status.textContent='';}
 dialog.addEventListener('cancel',e=>{e.preventDefault();close()});document.addEventListener('click',e=>{const button=e.target.closest('[data-view-photo]');if(button){const [day,slot]=button.dataset.viewPhoto.split(':');open(Number(day),slot);}});
 dialog.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t||!current)return;const b=current;if(t.hasAttribute('data-photo-close'))return close();if(t.dataset.photoTool)b.tool=t.dataset.photoTool;if(t.dataset.photoZoom){b.zoom=Math.max(.5,Math.min(6,b.zoom*Number(t.dataset.photoZoom)));fit();}if(t.hasAttribute('data-photo-reset')){b.zoom=1;b.x=b.y=0;fit();}if(t.hasAttribute('data-photo-undo')&&b.role==='trainer'&&b.strokes.length)b.redo.push(b.strokes.pop());if(t.hasAttribute('data-photo-redo')&&b.role==='trainer'&&b.redo.length)b.strokes.push(b.redo.pop());if(t.hasAttribute('data-photo-undo')||t.hasAttribute('data-photo-redo')){paint();showStatus(b,'Opslaan…');clearTimeout(timer);timer=setTimeout(()=>persist(b),650);}if(t.hasAttribute('data-photo-retry'))persist(b);if(t.hasAttribute('data-photo-share')){t.disabled=true;try{if(await persist(b))await persist(b,true);}finally{t.disabled=false;}}});
 let pointer=null;const point=e=>{const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]};
 canvas.addEventListener('pointerdown',e=>{if(!current||pointer)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);pointer={id:e.pointerId,x:e.clientX,y:e.clientY};if(current.role==='trainer'&&current.tool!=='pan'){current.redo=[];current.strokes.push({tool:current.tool,color:dialog.querySelector('#photoColor').value,width:Number(dialog.querySelector('#photoWidth').value)/1000,points:[point(e)]});paint();}});
 canvas.addEventListener('pointermove',e=>{if(!current||pointer?.id!==e.pointerId)return;e.preventDefault();if(current.tool==='pan'||current.role!=='trainer'){current.x+=e.clientX-pointer.x;current.y+=e.clientY-pointer.y;pointer.x=e.clientX;pointer.y=e.clientY;fit();}else{const s=current.strokes.at(-1);if(s.points.length<20000)s.points.push(point(e));paint();}});
 const end=e=>{if(pointer?.id!==e.pointerId)return;pointer=null;if(current&&current.role==='trainer'&&current.tool!=='pan'){showStatus(current,'Opslaan…');clearTimeout(timer);const b=current;timer=setTimeout(()=>persist(b),650);}};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
 dialog.querySelector('.photo-viewport').addEventListener('wheel',e=>{if(!current)return;e.preventDefault();current.zoom=Math.max(.5,Math.min(6,current.zoom*(e.deltaY<0?1.1:.9)));fit();},{passive:false});window.addEventListener('resize',fit);
 window.addEventListener('beforeunload',e=>{if([...drafts.values()].some(dirty)){e.preventDefault();e.returnValue='';}});window.FMZPhotos={lock,open};
})();
