/* Restore a synthetic portable export in an isolated database and filesystem. Never production. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{unzipSync,strFromU8}=require('fflate'),{setup}=require('./database.cjs'),{extend}=require('./accounting-database.cjs');
async function restore(archive='tests/artifacts/accounting-export.zip'){
 const zip=unzipSync(fs.readFileSync(archive)),s=JSON.parse(strFromU8(zip['administratie.json'])),index=JSON.parse(strFromU8(zip['bestandsindex.json']));
 const {db,ids}=await setup();await extend({db,ids});const output=path.resolve('tests/artifacts/restore-'+crypto.randomUUID());fs.mkdirSync(output,{recursive:true});
 try{
 await db.exec('truncate fmz_accounting.receipts,fmz_accounting.audit,fmz_accounting.files,fmz_accounting.lines,fmz_accounting.journals,fmz_accounting.records,fmz_accounting.accounts,fmz_accounting.organizations');
 const actors=new Set([s.organization.owner_id,...s.records.map(r=>r.created_by),...s.audit.map(a=>a.actor_id)]);
 for(const id of actors){await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'restore@example.test',now()) on conflict(id) do nothing",[id]);await db.query("insert into public.profiles(id,role,name,email) values($1,'trainer','Isolated restore','restore@example.test') on conflict(id) do nothing",[id]);await db.query('insert into auth.sessions values($1,$1) on conflict(id) do nothing',[id]);}
 const data={organizations:[s.organization],accounts:s.accounts,records:[],journals:s.journals,lines:s.lines,files:s.files,audit:s.audit};
 const pending=[...s.records],seen=new Set();while(pending.length){const ix=pending.findIndex(r=>!r.parent_id||seen.has(r.parent_id));if(ix<0)throw Error('Archive has unresolved parent links');const [r]=pending.splice(ix,1);data.records.push(r);seen.add(r.id);}
 for(const [table,rows]of Object.entries(data))for(const row of rows){const cols=Object.keys(row);await db.query(`insert into fmz_accounting.${table} (${cols.map(x=>'"'+x+'"').join(',')}) ${table==='audit'?'overriding system value ':''}values(${cols.map((_,i)=>'$'+(i+1)).join(',')})`,cols.map(k=>row[k]!==null&&typeof row[k]==='object'?JSON.stringify(row[k]):row[k]));}
 for(const [table,rows]of Object.entries(data)){const ok=(await db.query(`select not exists((select to_jsonb(t) from fmz_accounting.${table} t except select to_jsonb(t) from jsonb_populate_recordset(null::fmz_accounting.${table},$1) t) union all (select to_jsonb(t) from jsonb_populate_recordset(null::fmz_accounting.${table},$1) t except select to_jsonb(t) from fmz_accounting.${table} t)) ok`,[JSON.stringify(rows.map(r=>table==='organizations'?{...r,test_marker:null}:r))])).rows[0].ok;assert(ok,table+' restored exactly');}
 for(const f of index){const target=path.resolve(output,f.export_path);assert(target.startsWith(output+path.sep));const bytes=zip[f.export_path];assert(bytes,'Original is present');assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),f.sha256);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,bytes);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(target)).digest('hex'),f.sha256);}
 const invalid=(await db.query('select journal_id,sum(cents) total from fmz_accounting.lines group by journal_id having sum(cents)<>0')).rows;assert.equal(invalid.length,0);
 const actor=s.organization.owner_id;await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:actor,session_id:actor})]);await db.exec('set role authenticated');const restored=(await db.query('select public.fmz_accounting_read() result')).rows[0].result;await db.exec('reset role');assert.equal(restored.records.length,s.records.length);assert.equal(restored.files.length,index.length);
 const report={isolated:true,records:s.records.length,journals:s.journals.length,lines:s.lines.length,audit:s.audit.length,originalFiles:index.length,allOriginalHashesMatch:true,balanced:true,ownerReadAfterRestore:true};fs.writeFileSync('tests/artifacts/accounting-restore-result.json',JSON.stringify(report,null,2));console.log('PASS isolated restore: '+JSON.stringify(report));return report;
 }finally{await db.close();}
}
if(require.main===module)restore(process.argv[2]).catch(e=>{console.error(e.message);process.exitCode=1});module.exports={restore};
