const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright'),{PDFDocument}=require('pdf-lib'),{unzipSync,strFromU8}=require('fflate'),{start}=require('./preview.cjs');
test('owner administration phone and desktop: draft, PDF, payments, bank CSV, receipts, export and restored sources',{timeout:240000},async()=>{
 const live=process.env.FMZ_LIVE_TESTS==='1',preview=live?null:await start(0),url=live?process.env.FMZ_RELEASE_URL:preview.url;
 const account=live?JSON.parse(fs.readFileSync('C:/Users/Fitme/.codex/backups/appfmz-20260908/synthetic-accounts.json')).accounts.trainer:{email:'trainer@example.test',password:'test'};
 const browser=await chromium.launch({headless:true,channel:'msedge'}),p=await browser.newPage({acceptDownloads:true,viewport:{width:1400,height:1000}}),errors=[];
 p.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});
 async function login(){await p.locator('#loginForm select[name=role]').selectOption('trainer');await p.locator('#loginForm input[name=email]').fill(account.email);await p.locator('#loginForm input[name=password]').fill(account.password);await p.locator('#loginForm button[type=submit]').click();await p.waitForFunction(()=>onlineReady&&FMZAccounting.ready);}
 async function page(name){await p.evaluate(name=>{showView('administration');document.querySelector(`[data-acc-page="${name}"]`).click()},name);}
 async function submit(id){await p.locator(`[data-acc-form="${id}"] [type=submit]`).click();await p.waitForFunction(()=>[...document.querySelectorAll('[data-acc-status]')].some(e=>e.textContent==='Opgeslagen'));}
 const fill=async(form,values)=>{for(const [k,v]of Object.entries(values))await form.locator(`[name="${k}"]`).fill(String(v));};
 try{
 if(!live)await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url);await login();
 await page('settings');let f=p.locator('[data-acc-form=settings]');await fill(f,{date:'2026-09-01',businessName:'Synthetic FitMetZorge',address:'Teststraat 1',postalCity:'1000 AA Teststad',chamberNumber:'00000000',vatNumber:'NL000000000B00',email:'synthetic@example.test',iban:'TEST-IBAN',paymentTermDays:14});await f.locator('[name=vat_status]').selectOption('standard');await f.locator('[name=vat_method]').selectOption('invoice');await f.locator('[name=vat_period]').selectOption('quarter');await f.locator('[name=vat_basis_points]').selectOption('2100');await f.locator('[name=confirmed]').check();await submit('settings');console.log('PASS owner settings');
 await p.evaluate(async()=>{state.ui.selectedClientId='a';client().profile.package='pt-progressie';await saveStateToCloud();});
 const invoices=[];
 for(const [pkg,price] of [['pt-basis',200],['pt-progressie',380],['pt-transformatie',480]]){
  await p.evaluate(async pkg=>{client().profile.package=pkg;await saveStateToCloud();},pkg);await page('sales');await p.locator('[data-accounting-root=administration] [data-acc-action=new-package]').click();await p.locator('.acc-dialog [data-acc-action=choose-invoice]').click();f=p.locator('#invoiceDraftForm');assert.equal(await f.locator('[name=amount]').inputValue(),String(price));await fill(f,{customerAddress:'Testweg 2, 1000 AB Teststad',description:'Synthetic '+pkg});
  await p.waitForFunction(()=>document.querySelector('[data-invoice-message]')?.textContent==='Concept opgeslagen');assert.equal(await p.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.kind==='invoice'&&r.status==='posted').length),invoices.length);
  if(pkg==='pt-progressie'){await fill(f,{discount:30,discountNote:'Synthetic korting',term:21});await p.setViewportSize({width:390,height:844});await f.locator('[name=discount]').scrollIntoViewIfNeeded();assert.match(await f.locator('.invoice-total').innerText(),/350,00/);assert.equal(await f.evaluate(e=>e.scrollWidth<=e.clientWidth),true);fs.mkdirSync('tests/artifacts',{recursive:true});await p.screenshot({path:'tests/artifacts/accounting-invoice-mobile.png'});}
  await p.waitForFunction(()=>document.querySelector('[data-invoice-message]')?.textContent==='Concept opgeslagen');const wait=p.waitForEvent('download');await f.locator('[data-acc-action=invoice-save]').dblclick();const dl=await wait;console.log('PDF',pkg,await f.locator('[data-invoice-message]').innerText());await dl.saveAs('tests/artifacts/'+pkg+'.pdf');const bytes=fs.readFileSync('tests/artifacts/'+pkg+'.pdf');assert.equal(bytes.subarray(0,5).toString(),'%PDF-');const doc=await PDFDocument.load(bytes);assert.equal(doc.getPages()[0].getWidth(),595.28);const r=await p.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.kind==='invoice'&&r.status==='posted').at(-1));assert.equal(r.data.document.totalCents,pkg==='pt-progressie'?35000:price*100);invoices.push(r);await p.locator('.acc-dialog [data-acc-action=close]').click();
 }
 assert.equal(new Set(invoices.map(r=>r.number)).size,3);assert.equal(await p.evaluate(()=>FMZAccounting.snapshot.files.filter(f=>f.kind==='invoice_pdf'&&f.status==='ready').length),3);console.log('PASS 3 monthly amounts, private real PDFs and no invoice from typing');
 await p.setViewportSize({width:1400,height:1000});await page('bank');f=p.locator('[data-acc-form=account]');await fill(f,{name:'ING synthetisch',iban:'TEST-ING'});
 if(!live){let failRead=true;await p.route('**/__test__/rpc',r=>{if(failRead&&r.request().postDataJSON().name==='fmz_accounting_read'){failRead=false;return r.abort();}return r.continue();});await f.locator('[type=submit]').click();await p.waitForFunction(()=>document.querySelector('[data-acc-form=account] [data-form-status]')?.textContent.startsWith('Opgeslagen — overzicht'));await f.locator('[type=submit]').click();await p.waitForFunction(()=>document.querySelector('[data-acc-status]')?.textContent==='Opgeslagen');await p.unroute('**/__test__/rpc');assert.equal(await p.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.kind==='account').length),1);console.log('PASS lost refresh after confirmed booking retries read without a duplicate');}else await submit('account');const bank=await p.evaluate(()=>FMZAccounting.snapshot.records.find(r=>r.kind==='account'));await p.locator(`[data-acc-action=opening][data-id="${bank.id}"]`).click();f=p.locator('[data-acc-form=opening]');await fill(f,{date:'2026-09-01',amount:'0',description:'Synthetische openingsbalans'});await submit('opening');
 const inv=invoices[1];
 for(const value of ['100','250']){f=p.locator('[data-acc-form=bank]');await fill(f,{date:'2026-09-10',amount:value,description:'Synthetic factuurbetaling '+value});await submit('bank');const mutation=await p.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.kind==='bank').at(-1));await p.locator(`[data-acc-action=allocate][data-id="${mutation.id}"]`).click();f=p.locator('[data-acc-form=allocate]');await f.locator('[name=split_target]').selectOption('invoice:'+inv.id);await f.locator('[name=split_amount]').fill(value);await submit('allocate');const remaining=await p.evaluate(id=>FMZAccountingModel.project(FMZAccounting.snapshot).invoices.find(r=>r.id===id).outstanding,inv.id);assert.equal(remaining,value==='100'?25000:0);}
 await page('private');f=p.locator('[data-acc-form=private]');await fill(f,{date:'2026-09-10',amount:'0,20',description:'Twintig cent privé'});await submit('private');assert.equal(await p.evaluate(()=>FMZAccountingModel.project(FMZAccounting.snapshot).balance('2010')),-20);
 await page('bank');await p.locator(`[data-acc-action=reconcile][data-id="${bank.id}"]`).click();await fill(p.locator('[data-acc-form=reconcile]'),{date:'2026-09-10',amount:'350,20',description:'Synthetic afschrift'});await submit('reconcile');console.log('PASS partial/full payment, 20-cent deposit and bank reconciliation');
 f=p.locator('[data-acc-form=import-start]');await f.locator('[name=csv]').setInputFiles({name:'ing.csv',mimeType:'text/csv',buffer:Buffer.from('"Datum";"Naam / Omschrijving";"Rekening";"Tegenrekening";"Af Bij";"Bedrag (EUR)";"Mededelingen"\r\n"20260910";"Privéstorting";"TEST-ING";"PRIVATE";"Bij";"0,20";"CSV voorbeeld"')});await f.locator('[type=submit]').click();await p.locator('[data-import-row]').waitFor();await p.locator('[data-acc-action=import-confirm]').click();await p.waitForFunction(()=>document.querySelector('[data-acc-status]')?.textContent.includes('1 mutaties opgeslagen'));const bankCount=await p.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.kind==='bank').length);
 f=p.locator('[data-acc-form=import-start]');await f.locator('[name=csv]').setInputFiles({name:'overlap.csv',mimeType:'text/csv',buffer:Buffer.from('"Datum";"Naam / Omschrijving";"Rekening";"Tegenrekening";"Af Bij";"Bedrag (EUR)";"Mededelingen"\r\n"20260910";"Privéstorting";"TEST-ING";"PRIVATE";"Bij";"0,20";"CSV voorbeeld"')});await f.locator('[type=submit]').click();await p.locator('[data-import-row]').waitFor();assert.equal(await p.locator('[data-import-row]').isChecked(),false);assert.match(await p.locator('[data-import-preview]').innerText(),/Al geïmporteerd/);await p.locator('.acc-dialog [data-acc-action=close]').click();assert.equal(await p.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.kind==='bank').length),bankCount);console.log('PASS ING preview and overlapping CSV deduplication');
 await page('expenses');f=p.locator('[data-acc-form=expense]');await fill(f,{supplier:'Synthetic leverancier',date:'2026-09-10',description:'Privé betaald materiaal',gross:'121',vat:'21',business:'100',deductible:'100'});await f.locator('[name=vat_treatment]').selectOption('21');await f.locator('[name=paid]').selectOption('private');await f.locator('[name=proof]').setInputFiles('tests/artifacts/pt-basis.pdf');await submit('expense');assert.equal(await p.evaluate(()=>FMZAccountingModel.project(FMZAccounting.snapshot).balance('1200')),2100);assert.equal(await p.evaluate(()=>FMZAccountingModel.project(FMZAccounting.snapshot).balance('1900')),-12100);
 await p.reload();await p.waitForFunction(()=>FMZAccounting.ready);await p.locator('#logoutButton').click();await p.waitForFunction(()=>!onlineReady);await login();assert.equal(await p.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.kind==='invoice'&&r.status==='posted').length),3);
 await p.evaluate(()=>showView('invoice'));const download=p.waitForEvent('download');await p.locator(`[data-accounting-root=invoice] [data-acc-action=invoice-pdf][data-id="${inv.id}"]`).click();const dl=await download;await dl.saveAs('tests/artifacts/progressie-redownload.pdf');assert.deepEqual(fs.readFileSync('tests/artifacts/progressie-redownload.pdf'),fs.readFileSync('tests/artifacts/pt-progressie.pdf'));
 await page('reports');const zipWait=p.waitForEvent('download');await p.locator('[data-acc-action=export]').click();const archive=await zipWait;await archive.saveAs('tests/artifacts/accounting-export.zip');const files=unzipSync(fs.readFileSync('tests/artifacts/accounting-export.zip')),index=JSON.parse(strFromU8(files['bestandsindex.json'])),snap=JSON.parse(strFromU8(files['administratie.json']));assert.equal(index.length,5);assert(files['LEESMIJ.html']);for(const f of index){assert.equal(require('node:crypto').createHash('sha256').update(files[f.export_path]).digest('hex'),f.sha256);}fs.writeFileSync('tests/artifacts/accounting-export-snapshot.json',JSON.stringify(snap));assert.deepEqual(errors,[]);console.log('PASS receipts/VAT/private advance, re-login, identical stored PDF, portable export and all original hashes');
 await p.setViewportSize({width:390,height:844});await page('overview');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await p.screenshot({path:'tests/artifacts/accounting-overview-mobile.png'});
 }finally{await browser.close();await preview?.close();}
});
