const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{setup}=require('./database.cjs');
test('idempotent writes and private draft/share annotations preserve originals and reject outsiders',async()=>{const {db,as,read,ids}=await setup();try{
 const photo='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
 const changes=[{client_id:'a',path:['dailyWeightByWeek','2026-09-07'],before_exists:false,before:null,after_exists:true,after:[{photoFront:photo}]}],rid=randomUUID();
 const once=()=>as('a','select public.fmz_save_changes_once($1,$2) as r',[JSON.stringify(changes),rid]);assert.equal((await once()).rows[0].r.changed,1);assert.deepEqual((await once()).rows[0].r,{ok:true,changed:1});
 await assert.rejects(as('a','select public.fmz_save_changes_once($1,$2)',[JSON.stringify([]),rid]),e=>e.code==='PT409');
 async function annotation(who,action='read',strokes=[],version=0,hash=null,rid=null){return (await as(who,'select public.fmz_photo_annotation($1,$2,$3,$4,$5,$6,$7,$8,$9) as r',['a','2026-09-07',0,'photoFront',hash,action,JSON.stringify(strokes),version,rid])).rows[0].r;}
 const first=await annotation('trainer');assert.deepEqual(first.strokes,[]);const lines=[{tool:'draw',color:'#ff0000',width:.01,points:[[.1,.1],[.8,.8]]}];const request=randomUUID();const draft=await annotation('trainer','save',lines,0,first.source_hash,request);assert.equal(draft.version,1);assert.deepEqual(await annotation('trainer','save',lines,0,first.source_hash,request),draft);assert.deepEqual((await annotation('a')).strokes,[]);
 await assert.rejects(annotation('a','share',lines,1,first.source_hash,randomUUID()),e=>e.code==='42501');await assert.rejects(annotation('b'),e=>e.code==='42501');
 await db.query("insert into public.profiles(id,role,name,email) values($1,'trainer','Other','other@example.test')",[ids.new]);await assert.rejects(annotation('new'),e=>e.code==='42501');
 const shared=await annotation('trainer','share',lines,1,first.source_hash,randomUUID());assert.equal(shared.version,2);assert.deepEqual((await annotation('a')).strokes,lines);await annotation('trainer','save',[],2,first.source_hash,randomUUID());assert.deepEqual((await annotation('a')).strokes,lines);await assert.rejects(annotation('trainer','save',lines,1,first.source_hash,randomUUID()),e=>e.code==='PT409');
 assert.equal((await read('a')).clients[0].dailyWeightByWeek['2026-09-07'][0].photoFront,photo);await assert.rejects(as('a','select * from fmz_private.photo_annotations'),/permission denied/);
 await as('a',"select public.fmz_save_changes($1)",[JSON.stringify([{client_id:'a',path:['dailyWeightByWeek','2026-09-07'],before_exists:true,before:[{photoFront:photo}],after_exists:true,after:[{photoFront:photo+'A'}]}])]);await assert.rejects(annotation('trainer','save',lines,3,first.source_hash,randomUUID()),e=>e.code==='PT409');assert.deepEqual((await annotation('a')).strokes,[]);
 const legacy={clients:[{id:'old',trainingPlan:[{exercise:'test'}],nutritionPlan:[{meal:'test'}]}]};const normalized=(await db.query('select fmz_private.ensure_plan_ids($1) as r',[JSON.stringify(legacy)])).rows[0].r;assert.equal(normalized.clients[0].nutritionPlan[0].meal,'test');assert.equal(normalized.clients[0].nutritionPlan[0].id,'legacy-nutritionPlan-old-1');
 }finally{await db.close();}});
