const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright'),{start}=require('./preview.cjs');
test('month and four-week agreements: phone controls, preview, private PDF, relogin and lost response',{timeout:180000},async()=>{
 const preview=await start(0),browser=await chromium.launch({headless:true,channel:'msedge'}),p=await browser.newPage({acceptDownloads:true,viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await preview.database.db.query('update public.profiles set name=$1 where id=$2',['Synthetic billing trainer',preview.database.ids.trainer]);
 async function login(){await p.locator('#loginForm input[name=email]').fill('trainer@example.test');await p.locator('#loginForm input[name=password]').fill('test');await p.locator('#loginForm button[type=submit]').click();await p.waitForFunction(()=>FMZAccounting.ready);}
 const fill=async(f,values)=>{for(const [key,value]of Object.entries(values))await f.locator(`[name=${key}]`).fill(value);};
 try{await p.route('**/*',r=>r.request().url().startsWith(preview.url)?r.continue():r.abort());await p.goto(preview.url);await login();
  await p.evaluate(async()=>{await FMZAccounting.command('settings',{data:{date:'2020-01-01',confirmed:true,businessName:'Synthetic billing example',address:'Voorbeeldstraat 1',postalCity:'1000 AA Teststad',kvk_registered:false,vatNumber:'NLTEST',vat_status:'standard',vat_method:'invoice',vat_period:'quarter',vat_basis_points:2100}});await FMZAccounting.refresh();showView('clients');});
  await p.locator('[data-client-agreement=a]').first().click();let f=p.locator('[data-billing-form]');assert.equal(await f.locator('[name=cycle]').inputValue(),'four_weeks');await f.locator('[name=package_id]').selectOption('pt-progressie');await f.locator('[name=effective_from]').fill('2026-09-28');await f.locator('[name=reason]').fill('Synthetic new agreement');await f.locator('[name=confirmed]').check();await f.locator('[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('[data-billing-form]'));assert.equal(await p.evaluate(()=>FMZAccounting.snapshot.agreements[0].cycle),'four_weeks');
  await p.evaluate(()=>FMZBilling.openInvoiceChooser());f=p.locator('[data-billing-invoice]');await f.locator('[name=client_id]').selectOption('a');await f.locator('[name=at_date]').fill('2026-09-28');await f.locator('[type=submit]').click();f=p.locator('#invoiceDraftForm');await f.waitFor();await fill(f,{customerAddress:'Synthetische straat 2',discount:'30',discountNote:'Voorbeeldkorting'});await p.waitForFunction(()=>document.querySelector('[data-invoice-message]')?.textContent==='Concept opgeslagen');assert.match(await f.locator('.invoice-total').innerText(),/350,00/);
  let first=await p.evaluate(()=>FMZAccounting.snapshot.records.find(r=>r.kind==='invoice'));assert.equal(first.data.billing.start,'2026-09-28');assert.equal(first.data.billing.end,'2026-10-25');await p.waitForFunction(()=>document.querySelector('[data-pdf-preview] canvas'));fs.mkdirSync('tests/artifacts/billing',{recursive:true});await p.screenshot({path:'tests/artifacts/billing/four-weeks-mobile.png'});
  const downloaded=p.waitForEvent('download');await f.locator('[data-acc-action=invoice-save]').dblclick();const pdf=await downloaded;await pdf.saveAs('tests/artifacts/billing/four-weeks.pdf');assert.equal(fs.readFileSync('tests/artifacts/billing/four-weeks.pdf').subarray(0,5).toString(),'%PDF-');await p.locator('.acc-dialog [data-acc-action=close]').click();
  // Distinct request IDs and a lost response must still return the same invoice and number.
  const counts=await p.evaluate(()=>({invoices:FMZAccounting.snapshot.records.filter(r=>r.kind==='invoice').length,number:FMZAccounting.snapshot.organization.next_number}));let lost=false,requests=[];
  await p.route('**/__test__/rpc',async r=>{const b=r.request().postDataJSON();if(b.name==='fmz_billing_command'&&b.params.action==='prepare_invoice'){requests.push(b.params);if(!lost){lost=true;await r.fetch();return r.abort();}}return r.continue();});
  await p.evaluate(()=>FMZBilling.openInvoiceChooser());f=p.locator('[data-billing-invoice]');await f.locator('[name=client_id]').selectOption('a');await f.locator('[name=at_date]').fill('2026-10-01');await f.locator('[type=submit]').click();await p.waitForFunction(()=>document.querySelector('[data-billing-status]')?.textContent.startsWith('Niet geopend'));await p.waitForTimeout(800);assert.equal(requests.length,1);await f.locator('[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('[data-billing-invoice]'));assert.equal(requests[0].request_id,requests[1].request_id);await p.unroute('**/__test__/rpc');await p.locator('.acc-dialog [data-acc-action=close]').click();assert.deepEqual(await p.evaluate(()=>({invoices:FMZAccounting.snapshot.records.filter(r=>r.kind==='invoice').length,number:FMZAccounting.snapshot.organization.next_number})),counts);
  await p.evaluate(()=>FMZBilling.openAgreement('b'));f=p.locator('[data-billing-form]');await f.locator('[name=cycle]').selectOption('calendar_month');await f.locator('[name=effective_from]').fill('2026-10-01');await f.locator('[name=confirmed]').check();await f.locator('[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('[data-billing-form]'));
  await p.evaluate(()=>FMZBilling.openInvoiceChooser());f=p.locator('[data-billing-invoice]');await f.locator('[name=client_id]').selectOption('b');await f.locator('[name=at_date]').fill('2026-10-05');await f.locator('[type=submit]').click();f=p.locator('#invoiceDraftForm');await f.waitFor();await fill(f,{customerAddress:'Synthetische straat 3',discount:'20'});await p.waitForFunction(()=>document.querySelector('[data-invoice-message]')?.textContent==='Concept opgeslagen');assert.match(await f.locator('.invoice-total').innerText(),/180,00/);const monthlyWait=p.waitForEvent('download');await f.locator('[data-acc-action=invoice-save]').click();await (await monthlyWait).saveAs('tests/artifacts/billing/calendar-month.pdf');await p.locator('.acc-dialog [data-acc-action=close]').click();
  await p.reload();await p.waitForFunction(()=>FMZAccounting.ready);await p.locator('#logoutButton').click();await p.waitForFunction(()=>!onlineReady);await login();assert.equal(await p.evaluate(()=>FMZAccounting.snapshot.agreements.length),2);
  const again=p.waitForEvent('download');await p.evaluate(id=>FMZAccounting.downloadInvoice(id),first.id);await (await again).saveAs('tests/artifacts/billing/redownload.pdf');assert.deepEqual(fs.readFileSync('tests/artifacts/billing/redownload.pdf'),fs.readFileSync('tests/artifacts/billing/four-weeks.pdf'));
  for(const [width,height]of [[320,700],[390,844],[768,1024],[1400,1000]]){await p.setViewportSize({width,height});await p.evaluate(()=>{showView('clients');FMZBilling.openAgreement('a')});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await p.evaluate(()=>document.querySelector('[data-billing-form]').scrollWidth<=document.querySelector('[data-billing-form]').clientWidth),true);await p.screenshot({path:`tests/artifacts/billing/agreement-${width}.png`});await p.locator('[data-billing-close]').click();}
  assert.deepEqual(errors,[]);
 }finally{await browser.close();await preview.close();}
});
