const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),PDFLib=require('pdf-lib'),M=require('../accounting-model.js');
test('real A4 invoice documents preserve all lines across pages and share totals with preview',async()=>{
 const ctx={window:{}};new Function('window','PDFLib','FMZAccountingModel',fs.readFileSync('invoice-documents.js','utf8'))(ctx.window,PDFLib,M);
 const settings={businessName:'FitMetZorge — synthetisch voorbeeld',address:'Voorbeeldstraat 1',postalCity:'1000 AA Teststad',email:'synthetic@example.test',website:'example.test',phone:'0000000000',kvk_registered:true,chamberNumber:'00000000',vatNumber:'NL000000000B00',ownerName:'Synthetische rekeninghouder',iban:'TEST-IBAN'},logo='data:image/png;base64,'+fs.readFileSync('fit-met-zorge-logo.png').toString('base64');
 const body={lines:[{description:'Progressie: acht persoonlijke trainingen',quantity_milli:8000,unit_cents:4750}],price_mode:'inclusive',discount_mode:'fixed',discount_input_cents:3000},amounts=M.invoiceTotals(body,2100);
 const doc={...amounts,invoiceNo:'SYNTHETISCH-2026-0001',settings,customer:{name:'Voorbeeldlid',address:'Voorbeeldstraat 2\n1000 AB Teststad',number:'TEST-001'},date:'2026-09-11',dueDate:'2026-09-25',paymentTermDays:14,serviceDate:'2026-09-11',serviceExtent:'8 trainingen in september',quantity:8,period:'September 2026',reference:'Synthetische controle',vatStatus:'standard',vatBasisPoints:2100,priceMode:'inclusive',logo,discountNote:'Synthetische korting'};
 fs.mkdirSync('tests/artifacts',{recursive:true});const single=await ctx.window.FMZDocuments.pdf(doc);fs.writeFileSync('tests/artifacts/hotfix-a4-single.pdf',single);assert.equal((await PDFLib.PDFDocument.load(single)).getPageCount(),1);
 const two={...doc,...M.invoiceTotals({...body,lines:[{description:'Pakket 1-op-1 PT Progressie - 8 per maand - 380,00 per maand - september 2026',quantity_milli:8000,unit_cents:4750},{description:'Aanvullende synthetische dienst',quantity_milli:1000,unit_cents:2000}],discount_mode:'percent',discount_bp:1000},2100),customer:{...doc.customer,email:'synthetic-long-account-name@example.test'},discountMode:'percent',discountBasisPoints:1000};const twoBytes=await ctx.window.FMZDocuments.pdf(two);fs.writeFileSync('tests/artifacts/hotfix-a4-two-lines.pdf',twoBytes);assert.equal((await PDFLib.PDFDocument.load(twoBytes)).getPageCount(),1,'Two ordinary invoice lines should fit one A4');
 const rows=Array.from({length:65},(_,i)=>({description:`REGEL-${String(i+1).padStart(3,'0')} Persoonlijke training met uitleg en een aanvullende toelichting voor de klant.`,quantity_milli:1000,unit_cents:50+i}));
 const many={...doc,...M.invoiceTotals({...body,lines:rows,discount_input_cents:100},2100),invoiceNo:'SYNTHETISCH-2026-0002',description:'Veel regels'};const multi=await ctx.window.FMZDocuments.pdf(many);fs.writeFileSync('tests/artifacts/hotfix-a4-multiple.pdf',multi);const parsed=await PDFLib.PDFDocument.load(multi);assert(parsed.getPageCount()>=3);for(const page of parsed.getPages()){assert.equal(page.getWidth(),595.28);assert.equal(page.getHeight(),841.89);}fs.writeFileSync('tests/artifacts/hotfix-a4-expected.json',JSON.stringify({single:{total:35000,net:28926,vat:6074},multi:{total:many.totalCents,net:many.netCents,vat:many.vatCents,lines:65,pages:parsed.getPageCount()}}));
});
