const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require('playwright'),{start}=require('./preview.cjs');
test('autosave workout/nutrition flows, lost acknowledgement, draft/photo sharing and mobile drawing', {timeout:180000},async()=>{
 const live=process.env.FMZ_LIVE_TESTS==='1',preview=live?null:await start(0),url=live?process.env.FMZ_RELEASE_URL:preview.url;
 const accounts=live?JSON.parse(fs.readFileSync('C:/Users/Fitme/.codex/backups/appfmz-20260908/synthetic-accounts.json')).accounts:Object.fromEntries(['trainer','a','b'].map(x=>[x,{email:x+'@example.test',password:'test'}]));
 const browser=await chromium.launch({headless:true,channel:'msedge'});const errors=[];
 async function page(role,width=1400){const p=await (await browser.newContext({viewport:{width,height:950}})).newPage();p.on('pageerror',e=>errors.push(e.message));if(!live)await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url);await p.locator('#loginForm select[name=role]').selectOption(role==='trainer'?'trainer':'client');await p.locator('#loginForm input[name=email]').fill(accounts[role].email);await p.locator('#loginForm input[name=password]').fill(accounts[role].password);await p.locator('#loginForm button[type=submit]').click();await p.waitForFunction(()=>onlineReady);await p.evaluate(()=>{state.ui.selectedClientId='a';state.ui.trackingWeekStart='2026-09-07';state.ui.trainingDay='Dinsdag';state.ui.trackerDayIndex=1;renderAll()});return p;}
 async function saved(p){await p.waitForFunction(()=>!hasPendingChanges()&&document.querySelector('#syncStatus').textContent==='Opgeslagen');}
 const rpc=live?'**/rest/v1/rpc/fmz_save_changes_once':'**/__test__/rpc';const isSave=r=>live||r.postDataJSON().name==='fmz_save_changes_once';
 try{
 const a=await page('a');await a.evaluate(()=>showView('training'));const field=a.locator('[data-training-log="0:actualWeight"]');await field.fill('');await field.pressSequentially('72.5',{delay:70});await field.evaluate(e=>window.savedInputNode=e);await saved(a);assert.equal(await field.evaluate(e=>e===window.savedInputNode&&document.activeElement===e),true);assert.equal(await field.inputValue(),'72.5');assert.equal(await a.locator('[data-save-training-day]').first().isVisible(),false);
 await field.fill('72.');await a.waitForTimeout(800);assert.equal(await field.inputValue(),'72.');assert.equal(await a.evaluate(()=>hasPendingChanges()),true);await field.fill('73.5');await a.evaluate(()=>{state.ui.trackingWeekStart='2026-09-14';renderAll()});await saved(a);assert.equal(await a.evaluate(()=>client().trainingPlan[0].logsByWeek['2026-09-07'].actualWeight),'73.5');
 await a.evaluate(()=>{state.ui.trackingWeekStart='2026-09-07';showView('training')});let release,entered;const arrived=new Promise(r=>entered=r);let delayed=false;await a.route(rpc,async r=>{if(!isSave(r.request())||delayed)return r.continue();delayed=true;const response=await r.fetch();entered();await new Promise(r=>release=r);return r.fulfill({response})});await a.locator('[data-training-log="0:notes"]').fill('older acknowledgement');await arrived;await a.locator('[data-training-log="0:notes"]').fill('newer input');release();await a.waitForFunction(()=>cloudBaseline.clients[0].trainingPlan[0].logsByWeek['2026-09-07'].notes==='older acknowledgement');assert.equal(await a.evaluate(()=>hasPendingChanges()),true);assert.notEqual(await a.locator('#syncStatus').innerText(),'Opgeslagen');await saved(a);await a.unroute(rpc);
 let lost=false,requests=[];await a.route(rpc,async r=>{if(!isSave(r.request()))return r.continue();requests.push(r.request().postDataJSON());if(!lost){lost=true;await r.fetch();return r.abort()}return r.continue()});await a.locator('[data-training-log="0:notes"]').fill('lost reply note');await a.waitForFunction(()=>document.querySelector('#syncStatus').textContent.startsWith('Niet opgeslagen'));assert.equal(await a.locator('[data-training-log="0:notes"]').inputValue(),'lost reply note');await a.locator('.sync-actions summary').click();await a.locator('#retrySave').click();await saved(a);assert.equal((requests[0].params||requests[0]).request_id,(requests[1].params||requests[1]).request_id);await a.unroute(rpc);await a.reload();await a.waitForFunction(()=>onlineReady);assert.equal(await a.evaluate(()=>client().trainingPlan[0].logsByWeek['2026-09-07'].notes),'lost reply note');console.log('PASS debounce/focus/incomplete input/date binding, newer input and lost-response retry');
 const t=await page('trainer');await t.evaluate(()=>showView('training'));await t.locator('#trainingForm [name=exercise]').fill('Synthetic workout');await t.locator('#trainingForm [name=sets]').fill('3');await t.locator('#trainingForm [name=reps]').fill('8');await t.locator('#trainingForm button[type=submit]').dblclick();await saved(t);assert.equal(await t.evaluate(()=>client().trainingPlan.filter(e=>e.exercise==='Synthetic workout').length),1);const ti=await t.evaluate(()=>client().trainingPlan.findIndex(e=>e.exercise==='Synthetic workout'));await t.locator(`[data-training-plan="${ti}:sets"]`).fill('4');await t.locator(`[data-training-plan="${ti}:targetWeight"]`).fill('42.5');await saved(t);await t.locator(`[data-publish-training="${ti}"]`).click();await saved(t);
 await t.evaluate(()=>showView('nutrition'));await t.locator('#nutritionPlanForm [name=mealType]').selectOption('lunch');await t.locator('#nutritionPlanForm [name=meal]').fill('Synthetic bowl');await t.locator('#nutritionPlanForm [name=items]').fill('Oats and fruit');await t.locator('#nutritionPlanForm [name=kcal]').fill('500');await t.locator('#nutritionPlanForm button[type=submit]').dblclick();await saved(t);assert.equal(await t.evaluate(()=>client().nutritionPlan.filter(m=>m.meal==='Synthetic bowl').length),1);const mi=await t.evaluate(()=>client().nutritionPlan.findIndex(m=>m.meal==='Synthetic bowl'));await t.locator(`[data-meal-plan="${mi}:items"]`).fill('Oats, fruit and yogurt');await t.locator(`[data-meal-plan="${mi}:kcal"]`).fill('550');await saved(t);await t.locator(`[data-publish-meal="${mi}"]`).click();await saved(t);
 await a.reload();await a.waitForFunction(()=>onlineReady);assert.equal(await a.evaluate(()=>client().trainingPlan.find(e=>e.exercise==='Synthetic workout').sets),'4');assert.equal(await a.evaluate(()=>client().nutritionPlan.find(m=>m.meal==='Synthetic bowl').kcal),'550');await a.evaluate(()=>{state.ui.trackingWeekStart='2026-09-07';state.ui.trackerDayIndex=1;showView('nutrition')});const mealId=await a.evaluate(()=>client().nutritionPlan.find(m=>m.meal==='Synthetic bowl').id);await a.locator('[data-food-plan="2026-09-08:lunch"]').selectOption(mealId);await a.locator('[data-food-status="2026-09-08:lunch"]').selectOption('Gegeten zoals plan');await a.locator('[data-food-amount="2026-09-08:lunch"]').fill('1.5');await a.locator('[data-food-note="2026-09-08:lunch"]').fill('Synthetic daily note');await saved(a);await a.reload();await a.waitForFunction(()=>onlineReady);assert.equal(await a.evaluate(()=>client().foodLog.find(e=>e.date==='2026-09-08'&&e.mealType==='lunch').kcal),825);await t.locator('#refreshWorkspace').click();await t.waitForFunction(()=>client().foodLog.some(e=>e.note==='Synthetic daily note'));console.log('PASS workout and nutrition create/edit/publish and daily quantities retained');
 await a.evaluate(()=>{state.ui.trackingWeekStart='2026-09-07';state.ui.trackerDayIndex=1;showView('trackers')});const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');await a.locator('[data-progress-file="1:photoFront"]').setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:png});await a.waitForFunction(()=>client().dailyWeightByWeek['2026-09-07'][1].photoFront);await saved(a);const original=await a.evaluate(()=>client().dailyWeightByWeek['2026-09-07'][1].photoFront);await a.locator('[data-view-photo="1:photoFront"]').click();await a.locator('#photoViewer').waitFor({state:'visible'});assert.equal(await a.locator('#photoViewer .trainer-tools').isVisible(),false);await a.locator('[data-photo-close]').click();
 await t.locator('#refreshWorkspace').click();await t.waitForFunction(()=>client().dailyWeightByWeek['2026-09-07'][1].photoFront);await t.evaluate(()=>showView('trackers'));await t.locator('[data-view-photo="1:photoFront"]').click();await t.locator('#photoViewer').waitFor({state:'visible'});await t.locator('[data-photo-tool="draw"]').click();let box=await t.locator('#photoViewer canvas').boundingBox();await t.mouse.move(box.x+box.width*.2,box.y+box.height*.2);await t.mouse.down();await t.mouse.move(box.x+box.width*.8,box.y+box.height*.8,{steps:8});await t.mouse.up();await t.waitForFunction(()=>document.querySelector('#photoStatus').textContent==='Concept opgeslagen');
 await a.locator('[data-view-photo="1:photoFront"]').click();assert.equal(await a.locator('#photoStatus').innerText(),'Originele foto');await a.locator('[data-photo-close]').click();await t.locator('[data-photo-tool="erase"]').click();await t.mouse.move(box.x+box.width*.45,box.y+box.height*.45);await t.mouse.down();await t.mouse.move(box.x+box.width*.55,box.y+box.height*.55,{steps:4});await t.mouse.up();await t.locator('[data-photo-undo]').click();await t.locator('[data-photo-redo]').click();await t.locator('[data-photo-share]').click();await t.waitForFunction(()=>document.querySelector('#photoStatus').textContent==='Gedeeld met lid');await t.setViewportSize({width:390,height:844});await t.locator('[data-photo-zoom="1.25"]').click();await t.locator('[data-photo-tool="pan"]').click();box=await t.locator('#photoViewer canvas').boundingBox();await t.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await t.mouse.down();await t.mouse.move(box.x+box.width*.5+15,box.y+box.height*.5+15);await t.mouse.up();fs.mkdirSync('tests/artifacts',{recursive:true});await t.screenshot({path:'tests/artifacts/annotations-mobile.png'});await t.locator('[data-photo-close]').click();
 await a.reload();await a.waitForFunction(()=>onlineReady);await a.evaluate(()=>{state.ui.trackingWeekStart='2026-09-07';state.ui.trackerDayIndex=1;showView('trackers')});await a.locator('[data-view-photo="1:photoFront"]').click();await a.waitForFunction(()=>document.querySelector('#photoStatus').textContent==='Gedeelde aantekeningen');assert.equal(await a.evaluate(()=>client().dailyWeightByWeek['2026-09-07'][1].photoFront),original);assert.equal(await a.locator('#photoViewer .trainer-tools').isVisible(),false);console.log('PASS original photo unchanged, private concept, sharing and mobile viewer');assert.deepEqual(errors,[]);
 await a.locator('[data-photo-close]').click();await a.evaluate(()=>{state.ui.trainingDay='Dinsdag';showView('training')});await a.locator('[data-training-log="0:actualSets"]').fill('4');await a.locator('[data-training-log="0:actualReps"]').fill('9');await saved(a);await a.locator('[data-complete-training="1"]').click();await saved(a);await a.reload();await a.waitForFunction(()=>onlineReady);assert.equal(await a.evaluate(()=>client().trainingAttendanceByWeek['2026-09-07'][1].status),'Geweest');assert.equal(await a.evaluate(()=>client().trainingPlan[0].logsByWeek['2026-09-07'].actualReps),'9');await t.locator('#refreshWorkspace').click();await t.waitForFunction(()=>client().trainingAttendanceByWeek['2026-09-07'][1].status==='Geweest');
 await t.evaluate(()=>showView('training'));await t.locator(`[data-remove-training="${ti}"]`).click();await saved(t);await t.evaluate(()=>showView('nutrition'));await t.locator(`[data-remove-meal="${mi}"]`).click();await saved(t);await t.reload();await t.waitForFunction(()=>onlineReady);assert.equal(await t.evaluate(()=>client().trainingPlan.some(e=>e.exercise==='Synthetic workout')),false);assert.equal(await t.evaluate(()=>client().nutritionPlan.some(e=>e.meal==='Synthetic bowl')),false);assert.equal(await t.evaluate(()=>client().foodLog.find(e=>e.note==='Synthetic daily note').kcal),825);console.log('PASS explicit completion, performed sets/reps, trainer date/week and removal preserve daily history');
 }finally{await browser.close();await preview?.close();}
});
