const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('playwright'),{PDFDocument}=require('pdf-lib'),{start}=require('./preview.cjs');
test('package invoices: explicit draft, both views, cents, real PDF, retry and persisted snapshot',{timeout:180000},async()=>{
 const live=process.env.FMZ_LIVE_TESTS==='1',preview=live?null:await start(0),url=live?process.env.FMZ_RELEASE_URL:preview.url;
 const account=live?JSON.parse(fs.readFileSync('C:/Users/Fitme/.codex/backups/appfmz-20260908/synthetic-accounts.json')).accounts.trainer:{email:'trainer@example.test',password:'test'};
 const browser=await chromium.launch({headless:true,channel:'msedge'}),errors=[];
 async function login(p){await p.locator('#loginForm select[name=role]').selectOption('trainer');await p.locator('#loginForm input[name=email]').fill(account.email);await p.locator('#loginForm input[name=password]').fill(account.password);await p.locator('#loginForm button[type=submit]').click();await p.waitForFunction(()=>onlineReady);}
 try{
 const p=await browser.newPage({acceptDownloads:true,viewport:{width:1400,height:1000}});p.on('pageerror',e=>{errors.push(e.message);console.log('BROWSER ERROR',e.message)});if(!live)await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url);await login(p);console.log('LOGIN OK');
 await p.evaluate(async()=>{state.ui.selectedClientId='a';state.trainerFinance.invoiceSettings.email='synthetic@example.test';state.trainerFinance.invoiceSettings.address='Teststraat 1';state.trainerFinance.invoiceSettings.iban='TEST-IBAN';renderAll();await saveStateToCloud();showView('administration');});
 const rates=await p.evaluate(()=>CLIENT_PACKAGES.filter(x=>x.sessions).map(x=>({id:x.id,monthly:x.amount,sessions:x.sessions,unit:x.amount/x.sessions,legacy:packageByValue(x.label).id})));assert.deepEqual(rates.map(x=>[x.monthly,x.sessions,x.unit]),[[200,4,50],[380,8,47.5],[480,12,40]]);assert(rates.every(x=>x.legacy===x.id));assert.deepEqual(await p.evaluate(()=>['duo-basis','duo-progressie','duo-transformatie','online-coaching','custom'].map(packageAmount)),[260,520,780,200,'']);assert.equal(await p.evaluate(()=>{const s=FMZSync.clone(state);s.trainerFinance.adminItems=[{id:'historical',type:'invoice',invoiceNo:'FMZ-2025-99',amount:400}];return normalizeState(s).trainerFinance.adminItems[0].amount;}),400);assert.deepEqual(await p.evaluate(()=>{const i=createAppointmentAdminItem(client(),{id:'synthetic-single',date:'2026-09-10'});return [i.amount,i.invoiceNo,i.draft];}),['','',true]);
 const f=p.locator('#invoiceDraftForm'),amount=f.locator('[name=amount]'),discount=f.locator('[name=discount]'),save=f.locator('[data-save-invoice]');
 const numbers=[];
 for(const [pkg,price] of [['pt-basis',200],['pt-progressie',380],['pt-transformatie',480]]){
  await p.evaluate(async pkg=>{client().profile.package=pkg;await saveStateToCloud();renderAll();showView('administration');document.querySelector('#financeAdminForm [name=clientId]').value='a';},pkg);
  const before=await p.evaluate(()=>financeAdminItems().length);await p.locator('[data-create-package-invoice]').click();await f.waitFor({state:'visible'});console.log('DRAFT OPEN',pkg);assert.equal(await amount.inputValue(),String(price));await f.locator('[name=description]').fill('Synthetic '+pkg);await p.waitForTimeout(750);assert.equal(await p.evaluate(()=>financeAdminItems().length),before);
  if(pkg==='pt-progressie'){
   await amount.fill('');await save.click();assert.match(await f.locator('[data-invoice-message]').innerText(),/Niet opgeslagen/);assert.equal(await p.evaluate(()=>financeAdminItems().length),before);
   await amount.fill('380');for(const invalid of ['-1','381','abc']){await discount.fill(invalid);await save.click();assert.match(await f.locator('[data-invoice-message]').innerText(),/Niet opgeslagen/);}
   await discount.fill('30');await f.locator('[name=discountNote]').fill('Synthetic korting');await f.locator('[name=term]').fill('21');assert.match(await f.locator('.invoice-total').innerText(),/350,00/);
   await p.setViewportSize({width:390,height:844});await amount.scrollIntoViewIfNeeded();assert.equal(await f.evaluate(e=>e.scrollWidth<=e.clientWidth),true);fs.mkdirSync('tests/artifacts',{recursive:true});await p.screenshot({path:'tests/artifacts/invoice-mobile.png'});
  }
  const waitDownload=p.waitForEvent('download');await save.dblclick();console.log('SAVE STATUS',await f.locator('[data-invoice-message]').innerText());const dl=await waitDownload;const filename=dl.suggestedFilename();assert(filename.endsWith('.pdf'));fs.mkdirSync('tests/artifacts',{recursive:true});await dl.saveAs('tests/artifacts/'+pkg+'.pdf');const bytes=fs.readFileSync('tests/artifacts/'+pkg+'.pdf');assert.equal(bytes.subarray(0,5).toString(),'%PDF-');const pdf=await PDFDocument.load(bytes);assert.equal(pdf.getPages()[0].getWidth(),595.28);assert(pdf.getPageCount()>=1);
  await p.waitForFunction(()=>document.querySelector('[data-invoice-message]').textContent.startsWith('Opgeslagen'));const issued=await p.evaluate(()=>financeAdminItems().at(-1));assert.equal(issued.amount,pkg==='pt-progressie'?350:price);assert.equal(issued.document.grossCents,price*100);numbers.push(issued.invoiceNo);assert.equal(await p.evaluate(()=>financeAdminItems().length),before+1);await f.locator('[data-close-invoice]').click();
 }
 assert.equal(new Set(numbers).size,3);console.log('PASS 200/380/480, no invoice while typing, discount validation, A4 PDF and double-click guard');
 // Same invoice exists in both card lists. Edit through each actual screen.
 await p.setViewportSize({width:1400,height:1000});const id=await p.evaluate(()=>financeAdminItems().find(i=>i.document?.grossCents===38000).id);
 for(const [view,list,description] of [['administration','#financeInvoiceList','First screen edited'],['invoice','#invoicePageList','Second screen edited']]){
  await p.evaluate(view=>showView(view),view);await p.locator(`${list} [data-edit-invoice="${id}"]`).click();await f.locator('[name=description]').fill(description);await f.locator('[name=date]').fill('2026-09-10');await f.locator('[name=term]').fill('30');const wait=p.waitForEvent('download');await save.click();await wait;await p.waitForFunction(()=>document.querySelector('[data-invoice-message]').textContent.startsWith('Opgeslagen'));assert.equal(await p.evaluate(id=>financeAdminItems().find(i=>i.id===id).document.description,id),description);await f.locator('[data-close-invoice]').click();
 }
 await p.evaluate(async()=>{invoiceSettings().vatPercent=0;invoiceSettings().businessName='Changed later';await saveStateToCloud();});await p.reload();await p.waitForFunction(()=>onlineReady);await p.locator('#logoutButton').click();await p.waitForFunction(()=>!onlineReady);await login(p);const snapshot=await p.evaluate(id=>financeAdminItems().find(i=>i.id===id).document,id);assert.equal(snapshot.totalCents,35000);assert.equal(snapshot.vatBasisPoints,2100);assert.equal(snapshot.dueDate,'2026-10-10');assert.equal(snapshot.description,'Second screen edited');
 await p.evaluate(()=>showView('invoice'));let wait=p.waitForEvent('download');await p.locator(`#invoicePageList [data-download-invoice="${id}"]`).click();await wait;assert.equal(await p.evaluate(()=>financeAdminItems().length),3);console.log('PASS both editor entry points, logout/login and immutable amount/VAT/customer snapshot');
 // A committed write with lost reply is retried with the same server request ID.
 await p.locator(`#invoicePageList [data-edit-invoice="${id}"]`).click();await f.locator('[name=description]').fill('Lost acknowledgement');const rpc=live?'**/rest/v1/rpc/fmz_save_changes_once':'**/__test__/rpc',requests=[];let lost=false;
 await p.route(rpc,async r=>{const body=r.request().postDataJSON();if(!live&&body.name!=='fmz_save_changes_once')return r.continue();requests.push(body.params||body);if(!lost){lost=true;await r.fetch();return r.abort();}return r.continue();});await save.click();await p.waitForFunction(()=>document.querySelector('[data-invoice-message]').textContent.startsWith('Niet opgeslagen'));wait=p.waitForEvent('download');await save.click();await wait;assert.equal(requests[0].request_id,requests[1].request_id);assert.equal(await p.evaluate(()=>financeAdminItems().length),3);await p.unroute(rpc);await f.locator('[data-close-invoice]').click();
 // Download generation failure does not modify the saved invoice or allocate another number.
 await p.evaluate(()=>{window.originalPdfCreate=PDFLib.PDFDocument.create;PDFLib.PDFDocument.create=()=>{throw Error('Synthetic PDF error')};});p.once('dialog',d=>d.accept());await p.locator(`#invoicePageList [data-download-invoice="${id}"]`).click();await p.evaluate(()=>PDFLib.PDFDocument.create=window.originalPdfCreate);wait=p.waitForEvent('download');await p.locator(`#invoicePageList [data-download-invoice="${id}"]`).click();await wait;assert.equal(await p.evaluate(()=>financeAdminItems().length),3);assert.deepEqual(errors,[]);console.log('PASS lost-response retry and PDF-error retry without new invoices or numbers');
 const q=await browser.newPage();if(!live)await q.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await q.goto(url);await login(q);await q.evaluate(()=>showView('invoice'));await q.locator(`#invoicePageList [data-edit-invoice="${id}"]`).click();await q.locator('#invoiceDraftForm [name=description]').fill('Stale draft preserved');
 await p.locator(`#invoicePageList [data-edit-invoice="${id}"]`).click();await f.locator('[name=description]').fill('Concurrent confirmed');wait=p.waitForEvent('download');await save.click();await wait;await f.locator('[data-close-invoice]').click();
 let conflictRequests=0;q.on('request',r=>{if((live&&r.url().includes('/rpc/fmz_save_changes_once'))||(!live&&r.url().endsWith('/__test__/rpc')&&r.postDataJSON()?.name==='fmz_save_changes_once'))conflictRequests++;});await q.locator('#invoiceDraftForm [data-save-invoice]').click();await q.waitForFunction(()=>document.querySelector('[data-invoice-message]').textContent.includes('Conflict'));await q.waitForTimeout(900);assert.equal(conflictRequests,1);assert.equal(await q.locator('#invoiceDraftForm [name=description]').inputValue(),'Stale draft preserved');await q.locator('[data-close-invoice]').click();await q.locator('.sync-actions summary').click();q.once('dialog',d=>d.accept());await q.locator('#discardDraft').click();await q.waitForFunction(()=>!hasPendingChanges());await q.locator(`#invoicePageList [data-edit-invoice="${id}"]`).click();wait=q.waitForEvent('download');await q.locator('#invoiceDraftForm [data-save-invoice]').click();await wait;assert.equal(await q.evaluate(()=>financeAdminItems().length),3);assert.equal(await q.evaluate(id=>financeAdminItems().find(i=>i.id===id).document.description,id),'Stale draft preserved');console.log('PASS one conflict, draft retained and retry after explicit refresh without duplicate numbers');
 }finally{await browser.close();await preview?.close();}
});
