const {test}=require('node:test'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{start}=require('./preview.cjs');
test('invoice regression: both screens edit drafts, delayed acknowledgements, lost reply, conflict, PDF retry and session privacy',{timeout:180000},async()=>{
 const preview=await start(0),browser=await chromium.launch({headless:true,channel:'msedge'});const p=await browser.newPage(),q=await browser.newPage(),errors=[];
 async function login(page){page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(preview.url)?r.continue():r.abort());await page.goto(preview.url);await page.locator('#loginForm input[name=email]').fill('trainer@example.test');await page.locator('#loginForm input[name=password]').fill('test');await page.locator('#loginForm button[type=submit]').click();await page.waitForFunction(()=>FMZAccounting.ready);}
 async function saved(page){await page.waitForFunction(()=>document.querySelector('[data-invoice-message]')?.textContent==='Concept opgeslagen');}
 try{
 await login(p);
 const prices=await p.evaluate(()=>CLIENT_PACKAGES.filter(x=>x.sessions).map(x=>[x.amount,x.sessions,x.amount/x.sessions,packageByValue(x.label).id===x.id]));assert.deepEqual(prices,[[200,4,50,true],[380,8,47.5,true],[480,12,40,true]]);
 assert.deepEqual(await p.evaluate(()=>['duo-basis','duo-progressie','duo-transformatie','online-coaching','custom'].map(packageAmount)),[260,520,780,200,'']);
 assert.deepEqual(await p.evaluate(()=>{const x=createAppointmentAdminItem(client(),{id:'unissued-synthetic',date:'2026-09-10'});return [x.amount,x.invoiceNo,x.draft]}),['','',true]);
 await p.evaluate(async()=>{await FMZAccounting.command('settings',{id:crypto.randomUUID(),data:{date:'2026-01-01',businessName:'Synthetic',address:'Testweg 1',postalCity:'1000 AA Test',kvk_registered:false,vatNumber:'NL000000000B00',vat_status:'standard',vat_method:'invoice',vat_period:'quarter',vat_basis_points:2100,confirmed:true}});await FMZAccounting.refresh();client().profile.package='pt-progressie';await saveStateToCloud();showView('administration');document.querySelector('[data-acc-page=sales]').click();});
 await p.locator('[data-acc-action=new-package]').click();await p.locator('[data-acc-action=choose-invoice]').click();const f=p.locator('#invoiceDraftForm');assert.match(await f.locator('.invoice-total').innerText(),/380,00/);await f.locator('[name=customerAddress]').fill('Testweg 2');await saved(p);const id=await p.evaluate(()=>FMZAccounting.snapshot.records.find(r=>r.kind==='invoice').id);
 await f.locator('[name=amount]').fill('');await saved(p);await f.locator('[data-acc-action=invoice-save]').click();assert.match(await f.locator('[data-invoice-message]').innerText(),/Niet definitief opgeslagen/);assert.equal(await p.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.status==='posted'&&r.kind==='invoice').length),0);
 await f.locator('[name=amount]').fill('380');for(const value of ['-1','381','x']){await f.locator('[name=discount]').fill(value);await p.waitForTimeout(700);await f.locator('[data-acc-action=invoice-save]').click();assert.match(await f.locator('[data-invoice-message]').innerText(),/Niet definitief opgeslagen/);}await f.locator('[name=discount]').fill('30');await saved(p);await p.locator('.acc-dialog [data-acc-action=close]').click();
 for(const view of ['administration','invoice']){await p.evaluate(view=>{showView(view);if(view==='administration')document.querySelector('[data-acc-page=sales]').click()},view);await p.locator(`[data-accounting-root=${view}] [data-acc-action=invoice][data-id="${id}"]`).click();await f.locator('[name=description]').fill('Edited from '+view);await saved(p);await p.locator('.acc-dialog [data-acc-action=close]').click();assert.equal(await p.evaluate(id=>FMZAccounting.snapshot.records.find(r=>r.id===id).data.description,id),'Edited from '+view);}
 await p.locator(`[data-accounting-root=invoice] [data-acc-action=invoice][data-id="${id}"]`).click();let release,startedResolve;const started=new Promise(r=>startedResolve=r),held=new Promise(r=>release=r);let intercept=true;
 await p.route('**/__test__/rpc',async r=>{const b=r.request().postDataJSON();if(intercept&&b.name==='fmz_accounting_command'&&b.params.action==='draft'){intercept=false;const result=await r.fetch();startedResolve();await held;return r.fulfill({response:result});}return r.continue();});
 await f.locator('[name=description]').fill('First sent');await started;await f.locator('[name=description]').fill('Newer input stays');release();await saved(p);assert.equal(await f.locator('[name=description]').inputValue(),'Newer input stays');assert.equal(await p.evaluate(id=>FMZAccounting.snapshot.records.find(r=>r.id===id).data.description,id),'Newer input stays');await p.unroute('**/__test__/rpc');
 let lost=false;const requests=[];await p.route('**/__test__/rpc',async r=>{const b=r.request().postDataJSON();if(b.name==='fmz_accounting_command'&&b.params.action==='draft'){requests.push(b.params);if(!lost){lost=true;await r.fetch();return r.abort();}}return r.continue();});await f.locator('[name=description]').fill('Lost response');await p.waitForFunction(()=>document.querySelector('[data-invoice-message]').textContent.startsWith('Niet opgeslagen'));await p.waitForTimeout(900);assert.equal(requests.length,1);await f.locator('[name=description]').fill('Lost response retained plus new');await saved(p);assert.equal(requests[0].request_id,requests[1].request_id);await p.unroute('**/__test__/rpc');console.log('PASS draft scope, incomplete fields, delayed acknowledgement and idempotent lost reply');
 await login(q);await q.evaluate(id=>{showView('invoice');FMZAccounting.openInvoice(id)},id);let conflicts=0;q.on('request',r=>{if(r.url().endsWith('/__test__/rpc')){const b=r.postDataJSON();if(b.name==='fmz_accounting_command'&&b.params.action==='draft')conflicts++;}});
 await f.locator('[name=description]').fill('Concurrent winner');await saved(p);await q.locator('#invoiceDraftForm [name=description]').fill('My conflicting draft');await q.waitForFunction(()=>document.querySelector('[data-invoice-message]').textContent.includes('elders gewijzigd'));await q.waitForTimeout(1000);assert.equal(conflicts,1);assert.equal(await q.locator('[name=description]').last().inputValue(),'My conflicting draft');await q.locator('[data-acc-action=invoice-refresh]').click();await q.locator('[data-acc-action=invoice-use-mine]').click();await saved(q);console.log('PASS one conflict, input retained and explicit comparison before resave');
 // Fail only the post-confirmation PDF generation; preflight succeeds.
 await q.evaluate(()=>{window.savedCreate=PDFLib.PDFDocument.create;let count=0;PDFLib.PDFDocument.create=async(...a)=>{if(++count===2)throw Error('Synthetic PDF failure');return window.savedCreate(...a)}});await q.locator('[data-acc-action=invoice-save]').click();await q.waitForFunction(()=>document.querySelector('[data-invoice-message]').textContent.includes('Factuur opgeslagen — PDF nog niet gereed'));const issued=await q.evaluate(()=>FMZAccounting.snapshot.records.find(r=>r.kind==='invoice'&&r.status==='posted'));assert(issued.number);await q.evaluate(()=>PDFLib.PDFDocument.create=window.savedCreate);const download=q.waitForEvent('download');await q.locator('.acc-dialog [data-acc-action=invoice-pdf]').click();await download;assert.equal(await q.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.kind==='invoice'&&r.status==='posted').length),1);assert.equal(await q.evaluate(()=>FMZAccounting.snapshot.records.find(r=>r.kind==='invoice').number),issued.number);
 await q.evaluate(()=>expireTestSession());await q.waitForFunction(()=>!onlineReady);assert.equal(await q.evaluate(()=>FMZAccounting.snapshot),null);assert.equal(await q.locator('.acc-dialog').count(),0);assert.deepEqual(errors,[]);console.log('PASS PDF retry uses same final invoice and session loss clears private UI');
 }finally{await browser.close();await preview.close();}
});
