const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright'),{start}=require('./preview.cjs');
test('owner administration actual mobile controls, themes, dropdowns, disclosures, corrections and PDF previews',{timeout:300000},async()=>{
 const live=process.env.FMZ_LIVE_TESTS==='1',preview=live?null:await start(0),url=live?process.env.FMZ_RELEASE_URL:preview.url,owner=live?JSON.parse(fs.readFileSync('C:/Users/Fitme/.codex/backups/appfmz-20260908/synthetic-accounts.json')).accounts.trainer:{email:'trainer@example.test',password:'test'},browser=await chromium.launch({headless:true,channel:'msedge'}),p=await browser.newPage({viewport:{width:1400,height:1000},acceptDownloads:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 const root=()=>p.locator('#administration [data-accounting-root]');
 async function section(id){const nav=root().locator('.acc-navigation');if(await nav.getAttribute('open')===null)await nav.locator('summary').click();await root().locator(`[data-acc-page=${id}]`).click();await root().locator('h1').waitFor();}
 try{if(!live)await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url);await p.locator('#loginForm select[name=role]').selectOption('trainer');await p.locator('#loginForm input[name=email]').fill(owner.email);await p.locator('#loginForm input[name=password]').fill(owner.password);await p.locator('#loginForm button[type=submit]').click();await p.waitForFunction(()=>onlineReady&&FMZAccounting.ready);await p.evaluate(()=>showView('administration'));const revenueBefore=await p.evaluate(()=>FMZAccountingModel.project(FMZAccounting.snapshot).revenue);
  for(const [width,height]of (process.env.FMZ_SKIP_CONTROL_MATRIX==='1'?[]:[[320,700],[390,844],[768,1024],[1400,1000]]))for(const light of [false,true]){
   await p.setViewportSize({width,height});await p.evaluate(light=>{state.ui.theme=light?'light':'dark';document.body.classList.toggle('light',light)},light);
   for(const id of ['overview','sales','expenses','bank','private','assets','vat','reports','settings']){
    await section(id);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${id}: page overflow at ${width}/${light}`);
    const controls=root().locator('select');for(let i=0;i<await controls.count();i++){const c=controls.nth(i);if(!await c.isVisible()||await c.isDisabled())continue;await c.scrollIntoViewIfNeeded();assert.equal(await c.evaluate(e=>{const r=e.getBoundingClientRect();const hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);window.lastControlHit={name:e.name,rect:r.toJSON(),hit:hit?.outerHTML?.slice(0,400),width:innerWidth,theme:document.body.className};return hit===e;}),true,`${id} select is obstructed`);await c.click();await p.keyboard.press('Escape');}
    const summaries=root().locator('.acc-content details > summary');for(let i=0;i<await summaries.count();i++){const summary=summaries.nth(i);if(!await summary.isVisible())continue;await summary.click();assert.equal(await summary.evaluate(e=>e.parentElement.open),true);await summary.click();}
   }
   fs.mkdirSync('tests/artifacts',{recursive:true});await section('overview');await p.screenshot({path:`tests/artifacts/hotfix-admin-${width}-${light?'light':'dark'}.png`});
  }
  await p.setViewportSize({width:390,height:844});await section('vat');await root().locator('[name=periodType]').selectOption('quarter');assert.equal(await root().locator('[name=periodValue]').evaluate(e=>e.tagName),'SELECT');await root().locator('[name=quarterYear]').fill('2026');await root().locator('[name=periodValue]').selectOption('2026-Q3');await root().locator('[data-acc-action=period-filter]').click();
  for(const type of ['vat','all','sales','expenses']){await section(type==='vat'?'vat':'reports');const wait=p.waitForEvent('download');await root().locator(`[data-acc-action=report-${type}]`).click();const dl=await wait;await dl.saveAs(`tests/artifacts/hotfix-report-${type}.pdf`);assert.equal(fs.readFileSync(`tests/artifacts/hotfix-report-${type}.pdf`).subarray(0,5).toString(),'%PDF-');}
  await section('bank');const f=root().locator('[data-acc-form=account]'),cashName='Synthetic Kas '+Date.now();await f.locator('[name=name]').fill(cashName);await f.locator('[name=type]').selectOption('cash');await f.locator('[name=opening_date]').fill('2026-09-01');await f.locator('[name=opening_amount]').fill('0');await f.locator('[type=submit]').click();await p.waitForFunction(name=>FMZAccounting.snapshot.records.some(r=>r.kind==='account'&&r.data.name===name&&r.data.opening_cents===0),cashName);
  const account=await p.evaluate(name=>FMZAccounting.snapshot.records.find(r=>r.kind==='account'&&r.data.name===name),cashName);await root().locator(`[data-acc-action=account-visibility][data-id="${account.id}"]`).click();await p.waitForFunction(id=>FMZAccounting.snapshot.records.find(r=>r.id===id).data.hidden===true,account.id);await root().locator(`[data-acc-action=account-visibility][data-id="${account.id}"]`).click();await p.waitForFunction(id=>FMZAccounting.snapshot.records.find(r=>r.id===id).data.hidden===false,account.id);
  await p.evaluate(async()=>{await FMZAccounting.command('settings',{data:{date:'2026-09-01',confirmed:true,businessName:'Synthetic FitMetZorge',address:'Teststraat 1',postalCity:'1000 AA Test',vatNumber:'NL000000000B00',kvk_registered:false,vat_status:'standard',vat_method:'invoice',vat_period:'quarter',vat_basis_points:2100}});await FMZAccounting.refresh();state.ui.selectedClientId='a';client().profile.package='pt-progressie';await saveStateToCloud();});
  await section('sales');await root().locator('[data-acc-action=new-package]').click();await p.locator('.acc-dialog [data-acc-action=choose-invoice]').click();const inv=p.locator('#invoiceDraftForm');await inv.locator('[name=customerAddress]').fill('Teststraat 2, 1000 AA Test');await inv.locator('[name=discountMode]').selectOption('percent');await inv.locator('[name=discountPercent]').fill('10');await p.locator('[data-pdf-preview] canvas').first().waitFor({timeout:30000});assert.match(await inv.locator('.invoice-total').innerText(),/342,00/);
  // Keyboard-sized visual viewport keeps native fields and the close/save actions reachable.
  await p.setViewportSize({width:390,height:420});await inv.locator('[name=unitPrice]').focus();assert.equal(await inv.locator('[name=unitPrice]').evaluate(e=>document.activeElement===e),true);await p.locator('.acc-dialog [data-acc-action=close]').scrollIntoViewIfNeeded();assert.equal(await p.locator('.acc-dialog [data-acc-action=close]').isVisible(),true);await p.setViewportSize({width:390,height:844});
  await inv.locator('[data-acc-action=invoice-line-add]').click();let extra=inv.locator('[data-invoice-line]');await extra.locator('[data-line-field=description]').fill('Synthetic extra dienst');await extra.locator('[data-line-field=unitPrice]').fill('20');await p.waitForFunction(()=>document.querySelector('[data-invoice-message]').textContent==='Concept opgeslagen');assert.match(await inv.locator('.invoice-total').innerText(),/360,00/);
  const wait=p.waitForEvent('download');await inv.locator('[data-acc-action=invoice-save]').click();await (await wait).saveAs('tests/artifacts/hotfix-owner-invoice.pdf');await p.locator('.acc-dialog [data-acc-action=close]').click();let issued=await p.evaluate(()=>FMZAccounting.snapshot.records.filter(r=>r.kind==='invoice'&&r.status==='posted').at(-1));
  await root().locator(`[data-acc-action=invoice-open][data-id="${issued.id}"]`).click();await p.locator('.acc-dialog canvas').first().waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'tests/artifacts/hotfix-real-pdf-preview-mobile.png'});await p.locator('.acc-dialog [data-acc-action=close]').click();
  await root().locator(`[data-acc-action=invoice-cancel][data-id="${issued.id}"]`).click();const cancel=p.locator('[data-acc-form=invoice-cancel]');await cancel.locator('[name=reason]').fill('Synthetic testfactuur onbedoeld gemaakt');await cancel.locator('[name=unpaid_unsent_confirmed]').check();await cancel.locator('[type=submit]').click();await p.waitForFunction(id=>FMZAccounting.snapshot.records.some(r=>r.id===id&&r.data.cancellation_id),issued.id);await root().locator('[name=salesStatus]').selectOption('cancelled');assert.match(await root().innerText(),/Geannuleerd/);assert.equal(await p.evaluate(()=>FMZAccountingModel.project(FMZAccounting.snapshot).revenue),revenueBefore);
  await root().locator('[data-acc-action=new-package]').click();await p.locator('.acc-dialog [data-acc-action=choose-invoice]').click();await p.locator('#invoiceDraftForm [name=description]').fill('Synthetic delete');await p.waitForFunction(()=>document.querySelector('[data-invoice-message]').textContent==='Concept opgeslagen');const deletedID=await p.locator('#invoiceDraftForm [data-acc-action=draft-delete]').getAttribute('data-id');p.once('dialog',d=>d.accept());await p.locator('#invoiceDraftForm [data-acc-action=draft-delete]').click();await p.waitForFunction(id=>!FMZAccounting.snapshot.records.some(r=>r.id===id),deletedID);assert.deepEqual(errors,[]);
 }catch(e){console.log(await p.evaluate(()=>window.lastControlHit));await p.screenshot({path:'tests/artifacts/hotfix-control-failure.png'});throw e;}finally{await browser.close();await preview?.close();}
});
