// Explicitly authorized production release verification. Credentials stay outside Git.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const dir=process.env.FMZ_BACKUP_DIR||'C:/Users/Fitme/.codex/backups/appfmz-20260908';
const base='https://hgoygcviutmynaihcvpd.supabase.co';
const keys=JSON.parse(fs.readFileSync(path.join(dir,'api-keys.json'),'utf8').replace(/^\uFEFF/,''));
const service=keys.find(k=>k.name==='service_role').api_key,anon=keys.find(k=>k.name==='anon').api_key;
const manifestPath=path.join(dir,'synthetic-accounts.json');
async function request(url,method='GET',body,key=service){const r=await fetch(base+url,{method,signal:AbortSignal.timeout(20000),headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',Prefer:'return=representation'},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw Error(method+' '+url.split('?')[0]+' status '+r.status+' code '+(data.code||data.error_code||''));return data;}
function save(m){fs.writeFileSync(manifestPath,JSON.stringify(m,null,2));}
async function setup(){
 if(fs.existsSync(manifestPath)){const previous=JSON.parse(fs.readFileSync(manifestPath));assert(Object.values(previous.accounts).every(a=>a.deleted),'Existing active manifest: cleanup first');fs.copyFileSync(manifestPath,path.join(dir,previous.marker+'-cleaned.json'));}
 const m={marker:'fmz-release-'+crypto.randomBytes(6).toString('hex'),accounts:{},createdAt:new Date().toISOString()};save(m);
 for(const role of ['trainer','a','b']){const email=m.marker+'-'+role+'@example.test',password=crypto.randomBytes(24).toString('base64url')+'Aa1!';const u=await request('/auth/v1/admin/users','POST',{email,password,email_confirm:true,user_metadata:{fmz_release:m.marker}});m.accounts[role]={id:u.id,email,password};save(m);}
 const t=m.accounts.trainer;await request('/rest/v1/profiles','POST',{id:t.id,role:'trainer',name:'Synthetic release trainer',email:t.email});
 for(const role of ['a','b']){const a=m.accounts[role];await request('/rest/v1/profiles','POST',{id:a.id,role:'client',name:'Synthetic '+role,email:a.email,trainer_id:t.id,client_id:role});}
 const client=id=>({id,name:'Synthetic '+id,email:m.accounts[id].email,goal:'Release verification',goals:{kcalTraining:2500,kcalRest:2000},profile:{privateAdminNote:'PRIVATE ADMIN'},coachNotesByWeek:{secret:'PRIVATE NOTE'},trainingPlan:[{id:'ex1',day:'Dinsdag',exercise:'Squat',sets:3,published:true,logsByWeek:{}},{id:'draft',exercise:'PRIVATE DRAFT',published:false}],nutritionPlan:[{id:'meal1',meal:'Lunch',published:true,logsByWeek:{}}],foodLog:[],stepsByWeek:{},dailyWeightByWeek:{},wellbeingByWeek:{},sleepByWeek:{},waterByWeek:{},trainingAttendanceByWeek:{},appointments:[]});
 await request('/rest/v1/coach_workspaces','POST',{trainer_id:t.id,state:{clients:[client('a'),client('b')],trainerFinance:{secret:'PRIVATE FINANCE'},ui:{}}});console.log('Created 3 isolated synthetic accounts and 1 workspace; no invitation mail.');
}
async function cleanup(){const m=JSON.parse(fs.readFileSync(manifestPath));assert(m.marker.startsWith('fmz-release-'));for(const role of ['a','b','trainer']){const a=m.accounts[role];if(!a||a.deleted)continue;assert(a.email===m.marker+'-'+role+'@example.test');const u=await request('/auth/v1/admin/users/'+a.id);assert(u.email===a.email&&u.user_metadata.fmz_release===m.marker);await request('/auth/v1/admin/users/'+a.id,'DELETE');a.deleted=true;save(m);}console.log('Deleted only the 3 manifest-owned synthetic auth accounts.');}
async function api(){
 const m=JSON.parse(fs.readFileSync(manifestPath));const sessions=[];
 async function call(url,token,body,extra={}){const r=await fetch(base+url,{method:body?'POST':'GET',signal:AbortSignal.timeout(20000),headers:{apikey:anon,Authorization:'Bearer '+token,'Content-Type':'application/json',...extra},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};}
 try{
 for(const role of ['trainer','a']){const {email,password}=m.accounts[role];sessions.push(await request('/auth/v1/token?grant_type=password','POST',{email,password},anon));}
 const body={clientId:'a',email:m.accounts.a.email,name:'Synthetic a'};
 assert.equal((await call('/functions/v1/invite-client',anon,body)).status,401);
 assert.equal((await call('/functions/v1/invite-client',sessions[1].access_token,body)).status,403);
 const existing=await call('/functions/v1/invite-client',sessions[0].access_token,body);assert.equal(existing.status,200);assert.equal(existing.data.alreadyRegistered,true);
 const privateSchema=await call('/rest/v1/profiles?select=id',sessions[1].access_token,null,{'Accept-Profile':'fmz_private'});assert.equal(privateSchema.status,406);assert.equal(privateSchema.data.code,'PGRST106');
 const refreshed=await request('/auth/v1/token?grant_type=refresh_token','POST',{refresh_token:sessions[1].refresh_token},anon);sessions[1]=refreshed;assert(refreshed.access_token);const read=await call('/rest/v1/rpc/fmz_read_workspace',refreshed.access_token,{});assert.equal(read.status,200);assert.equal(read.data.state.clients.length,1);
 const changes=[{client_id:'a',path:['waterByWeek','2099-01-05'],before_exists:read.data.state.clients[0].waterByWeek['2099-01-05']!==undefined,before:read.data.state.clients[0].waterByWeek['2099-01-05']??null,after_exists:true,after:[{value:String(Date.now())}]}];assert.equal((await call('/rest/v1/rpc/fmz_save_changes',refreshed.access_token,{changes})).status,200);console.log('API first save completed');const conflict=await call('/rest/v1/rpc/fmz_save_changes',refreshed.access_token,{changes});console.log('API stale save status',conflict.status);assert.equal(conflict.data.code,'PT409');
 const result={at:new Date().toISOString(),edgeVersion:6,jwtRejectedAnon:true,memberRejected:true,registeredSyntheticReturnedWithoutMail:true,privateSchemaNotExposed:true,realTokenRefresh:true};fs.writeFileSync(path.join(dir,'live-api-results.json'),JSON.stringify(result,null,2));console.log('PASS Edge JWT and trainer authorization; existing account returns without mail; private schema not exposed; refreshed real token reads own workspace.');
 }finally{for(const s of sessions)await fetch(base+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:anon,Authorization:'Bearer '+s.access_token}});}
}
async function run(){
 const {chromium}=require('playwright'),m=JSON.parse(fs.readFileSync(manifestPath));
 const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
 const url=process.env.FMZ_RELEASE_URL||'https://appfmz.nl/release-validation-d989c5b-7c29.html';
 const results=[],errors=[];let active;
 const watchdog=setTimeout(()=>{console.error('Test watchdog: last completed '+results.at(-1));browser.close();},150000);
 function passed(name){results.push(name);console.log('PASS '+name);fs.writeFileSync(path.join(dir,'live-test-results.json'),JSON.stringify({at:new Date().toISOString(),url,results,errors},null,2));}
 async function page(){const ctx=await browser.newContext({viewport:{width:1400,height:950}});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));if(process.env.FMZ_CONFLICT_ONLY)p.on('response',r=>{if(r.url().includes('/rpc/'))console.log('RPC HTTP',r.status())});await p.route('**/functions/v1/invite-client',r=>r.abort());await p.goto(url);active=p;return p;}
 async function login(p,role){await p.evaluate(async()=>{await supabaseClient.auth.getSession()});const a=m.accounts[role];await p.locator('#loginForm select[name=role]').selectOption(role==='trainer'?'trainer':'client');await p.locator('#loginForm input[name=email]').fill(a.email);await p.locator('#loginForm input[name=password]').fill(a.password);await p.locator('#loginForm button[type=submit]').click();await p.waitForFunction(()=>document.body.classList.contains('logged-in'));}
 async function logoutPage(p){await p.evaluate(()=>{window.releaseLogoutComplete=false;const original=logout;logout=function(...args){const r=original(...args);window.releaseLogoutComplete=true;logout=original;return r;}});await p.locator('#logoutButton').click();await p.waitForFunction(()=>window.releaseLogoutComplete);}
 try{
 const a=await page();await login(a,'a');passed('real GoTrue login and PostgREST workspace read');
 const projection=await a.evaluate(async()=>{const r=await supabaseClient.rpc('fmz_read_workspace');return r.data.state;});assert.equal(projection.clients.length,1);assert.equal(projection.clients[0].id,'a');assert(!JSON.stringify(projection).includes('PRIVATE'));passed('member projection excludes other clients, drafts and private administration');
 await a.evaluate(()=>{state.ui.trackingWeekStart='2026-09-07';state.ui.trainingDay='Dinsdag';state.ui.trackerDayIndex=1;renderAll();showView('training')});
 await a.locator('[data-training-log="0:actualWeight"]').fill('72.5');await a.locator('[data-save-training-day="1"]').click();await a.waitForFunction(()=>document.querySelector('[data-save-feedback="training-1"]')?.textContent==='Opgeslagen');
 await a.evaluate(()=>{showView('nutrition')});await a.locator('[data-food-note="2026-09-08:lunch"]').fill('Synthetic release lunch');await a.locator('[data-food-status="2026-09-08:lunch"]').selectOption('Anders gegeten');await a.locator('[data-save-food-log="2026-09-08:lunch"]').click();await a.waitForFunction(()=>document.querySelector('[data-save-feedback="food-2026-09-08-lunch"]')?.textContent==='Opgeslagen');
 await a.evaluate(()=>{showView('trackers');renderTrackersOverview()});await a.locator('#trackers [data-step-index="1"]').fill('13000');await a.locator('#trackers [data-save-steps-day="1"]').click();await a.waitForFunction(()=>document.querySelector('#trackers [data-save-feedback="steps-1"]')?.textContent==='Opgeslagen');await a.locator('#trackers [data-sleep="1:hours"]').selectOption('8');await a.locator('#trackers [data-save-sleep-day="1"]').click();await a.waitForFunction(()=>document.querySelector('#trackers [data-save-feedback="sleep-1"]')?.textContent==='Opgeslagen');passed('training, nutrition, steps and sleep saved via real production RPC');
 async function verify(p){const c=await p.evaluate(()=>client());assert.equal(c.trainingPlan[0].logsByWeek['2026-09-07'].actualWeight,'72.5');assert(JSON.stringify(c.foodLog).includes('Synthetic release lunch'));assert.equal(String(c.stepsByWeek['2026-09-07'][1].value),'13000');assert.equal(String(c.sleepByWeek['2026-09-07'][1].hours),'8');}
 await a.reload();await a.waitForFunction(()=>document.body.classList.contains('logged-in'));await verify(a);await logoutPage(a);await login(a,'a');await verify(a);passed('all saved values survive refresh and logout/login');
 const t=await page();await login(t,'trainer');await t.evaluate(()=>{state.ui.selectedClientId='a';renderAll()});await verify(t);
 await a.evaluate(async()=>{client().stepsByWeek['2026-09-07'][1].value='14000';const r=await saveStateToCloud();if(!r.ok)throw Error('save failed')});await t.locator('#refreshWorkspace').click();await t.waitForFunction(()=>state.clients.find(c=>c.id==='a').stepsByWeek['2026-09-07'][1].value==='14000');passed('separate trainer session receives client values after refresh');
 const b=await page();await login(b,'b');assert.equal(await b.evaluate(()=>client().id),'b');const denies=await b.evaluate(async()=>({raw:(await supabaseClient.from('coach_workspaces').select('*')).error?.code,role:(await supabaseClient.from('profiles').update({role:'trainer'}).eq('id',onlineProfile.id)).error?.code,other:(await supabaseClient.rpc('fmz_save_changes',{changes:[{client_id:'a',path:['foodLog'],before_exists:true,before:[],after_exists:true,after:[]}]})).error?.code}));assert(denies.raw&&denies.role&&denies.other);passed('other customer denied raw workspace, role escalation and foreign client writes');
 console.log('START second-device conflict');const a2=await page();console.log('Second device loaded');await login(a2,'a');console.log('Second device authenticated');await a.evaluate(async()=>{client().trainingPlan[0].logsByWeek['2026-09-07'].actualWeight='73';await saveStateToCloud()});console.log('First device saved');assert.equal(await a2.evaluate(async()=>{client().trainingPlan[0].logsByWeek['2026-09-07'].actualWeight='80';return (await saveStateToCloud()).ok}),false);assert.match(await a2.locator('#syncStatus').innerText(),/Conflict/);assert.equal(await a2.evaluate(()=>client().trainingPlan[0].logsByWeek['2026-09-07'].actualWeight),'80');passed('real stale-write conflict retains input without false success');
 await a.route('**/rest/v1/rpc/fmz_save_changes',r=>r.abort());assert.equal(await a.evaluate(async()=>{client().trainingPlan[0].logsByWeek['2026-09-07'].actualWeight='74';return (await saveStateToCloud()).ok}),false);assert.equal(await a.evaluate(()=>client().trainingPlan[0].logsByWeek['2026-09-07'].actualWeight),'74');assert.notEqual(await a.locator('#syncStatus').innerText(),'Online opgeslagen');await a.unroute('**/rest/v1/rpc/fmz_save_changes');passed('injected network failure retains input without false success');
 await a.evaluate(async()=>{await saveStateToCloud()});await logoutPage(a);await login(a,'b');assert.equal(await a.evaluate(()=>client().id),'b');assert.equal(await a.evaluate(()=>state.clients.length),1);assert(!(await a.locator('body').innerText()).includes('Synthetic release lunch'));passed('account switch clears prior customer private state');
 // Revoke only this browser's real synthetic session, preserving its token to test server denial.
 await b.evaluate(async()=>{const {data}=await supabaseClient.auth.getSession();await fetch(SUPABASE_URL+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,Authorization:'Bearer '+data.session.access_token}});client().foodLog.push({date:'2026-09-08',meal:'lunch',note:'expired session'});await saveStateToCloud();});assert.equal(await b.evaluate(()=>state.clients.length),0);assert.equal(await b.evaluate(()=>state.ui.loggedIn),false);passed('revoked real session locks browser and clears private state');
 active=t;await t.evaluate(()=>{state.ui.selectedClientId='a';state.ui.trainingDay='Dinsdag';renderAll();showView('training')});for(const width of [1400,390]){await t.setViewportSize({width,height:width===390?844:950});const actual=await t.locator('.training-exercise-card .exercise-photo').first().evaluate(e=>e.getBoundingClientRect().width);assert(actual>=96&&actual<=120);await t.screenshot({path:path.join(dir,'live-trainer-'+width+'.png'),fullPage:width!==390});}passed('trainer exercise images compact at desktop and mobile widths');assert.deepEqual(errors,[]);passed('no uncaught browser errors');
 }catch(e){fs.writeFileSync(path.join(dir,'live-test-failure.txt'),String(e.stack));if(active)await active.screenshot({path:path.join(dir,'live-failure.png')}).catch(()=>{});throw e;}finally{clearTimeout(watchdog);await browser.close();}
}
({setup,cleanup,api,test:run}[process.argv[2]]||(()=>{throw Error('Use setup, test, api or cleanup')}))().catch(e=>{console.error(e.message);process.exitCode=1});
