const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),{PDFDocument}=require('pdf-lib'),{chromium}=require('playwright'),{start}=require('./preview.cjs'),C=require('../tutorial/content.js'),M=require('../tutorial/model.js');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
test('handbook and generated parser match reviewed course content and A4 PDF format',async()=>{const manifest=require('../tutorial/handbook-manifest.json');assert.equal(manifest.version,C.version);assert.equal(manifest.checked,C.checked);for(const [file,expected] of Object.entries(manifest.sourceHashes))assert.equal(hash(fs.readFileSync(file)),expected);const bytes=fs.readFileSync(manifest.pdf);assert.equal(hash(bytes),manifest.pdfSHA256);assert.equal(bytes.subarray(0,5).toString(),'%PDF-');const pdf=await PDFDocument.load(bytes);assert(pdf.getPageCount()>27);for(const p of pdf.getPages()){assert(Math.abs(p.getWidth()-595.28)<.1);assert(Math.abs(p.getHeight()-841.89)<.1);}for(const v of require('../tutorial/vendor/manifest.json')){assert.equal(hash(fs.readFileSync(v.input,'utf8').replace(/\r\n/g,'\n')),v.sha256);assert.equal(hash(fs.readFileSync(v.output,'utf8').replace(/\r\n/g,'\n')),v.outputSha256);}});
test('manual download, failed PDF retry and unavailable local progress keep isolation',{timeout:120000},async()=>{const server=await start(0),browser=await chromium.launch({channel:'msedge',headless:true}),p=await browser.newPage({acceptDownloads:true});try{
 await p.addInitScript(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='fmz-course-progress-v1')throw new DOMException('Disabled','QuotaExceededError');return original.call(this,k,v);};});await p.goto(server.url+'/tutorial.html');await p.locator('iframe').contentFrame().locator('[data-action=manual]').waitFor();let f=p.frames().find(f=>f.url().includes('course.html'));
 const event=p.waitForEvent('download');await f.locator('[data-action=manual]').click();const d=await event;assert.equal(await d.failure(),null);const bytes=fs.readFileSync(await d.path());assert.equal(hash(bytes),require('../tutorial/handbook-manifest.json').pdfSHA256);assert.equal(d.suggestedFilename(),'APPFMZ-boekhouden-voor-beginners.pdf');
 const response=await p.request.get(server.url+'/output/pdf/APPFMZ-boekhouden-voor-beginners.pdf');assert.match(response.headers()['content-type'],/application\/pdf/);
 await f.locator('[data-action=topics]').first().click();await f.locator('[data-lesson="8"]').click();await f.locator('#progressNotice').filter({hasText:'kon niet lokaal'}).waitFor();
 for(const field of M.plans[8][0].fields){const e=f.locator(`[name="${field.key}"]`);if(field.type==='select')await e.selectOption(field.answer);else await e.fill(field.answer);}
 await f.evaluate(()=>{window.originalPDF=FMZDocuments.pdf;FMZDocuments.pdf=async()=>{throw Error('synthetische downloadfout');};});await f.locator('[data-action=preview]').click();await f.locator('#practiceFeedback').filter({hasText:'synthetische downloadfout'}).waitFor();assert.equal(await f.locator('[name=amount]').inputValue(),'380,00');assert.equal(await f.locator('[name=discount]').inputValue(),'30,00');
 await f.evaluate(()=>FMZDocuments.pdf=window.originalPDF);await f.locator('[data-action=preview]').click();await f.locator('.pdf-dialog canvas').waitFor();await f.locator('[data-action=viewer-close]').click();await f.locator('[data-action=check-practice]').click();assert.match(await f.locator('#practice').innerText(),/Oefening doorlopen/);
 await f.locator('[data-action=home]').click();assert.match(await f.locator('#progressNotice').innerText(),/kon niet lokaal/);assert.deepEqual(server.calls,[]);assert.equal(server.blobs.size,0);
 }finally{await browser.close();await server.close();}});
