const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),{chromium}=require('playwright'),{start}=require('./preview.cjs'),M=require('../tutorial/model.js'),C=require('../tutorial/content.js');
const dir='tests/artifacts/tutorial';fs.mkdirSync(dir,{recursive:true});
async function snapshot(db){const tables=(await db.query("select schemaname,tablename from pg_tables where schemaname in ('public','fmz_private','fmz_accounting','auth','storage') order by 1,2")).rows,result={};for(const t of tables){const name=t.schemaname+'.'+t.tablename,rows=(await db.query(`select to_jsonb(t)::text row from "${t.schemaname}"."${t.tablename}" t order by 1`)).rows;result[name]=crypto.createHash('sha256').update(JSON.stringify(rows)).digest('hex');}return result;}
async function openLesson(f,id){await f.locator('[data-action=topics]').first().click();await f.locator(`[data-lesson="${id}"]`).click();}
test('owner help and opaque exercises cannot mutate financial, member, auth, Storage or audit state',{timeout:180000},async()=>{const server=await start(0),browser=await chromium.launch({channel:'msedge',headless:true}),p=await browser.newPage();try{
 await p.route('**/*',r=>r.request().url().startsWith(server.url)?r.continue():r.abort());await p.goto(server.url);await p.locator('#loginForm input[name=email]').fill('trainer@example.test');await p.locator('#loginForm input[name=password]').fill('test');await p.locator('#loginForm button[type=submit]').click();await p.waitForFunction(()=>FMZAccounting.ready);await p.evaluate(()=>showView('administration'));await p.locator('#administration [data-acc-action=tutorial]').waitFor();
 const before=await snapshot(server.database.db),callsBefore=server.calls.length;
 for(const [i,id] of Object.keys(C.help).entries()){await p.setViewportSize([{width:320,height:700},{width:390,height:844},{width:768,height:1024},{width:1400,height:1000}][i%4]);const nav=p.locator('#administration .acc-navigation');if(await nav.getAttribute('open')===null)await nav.locator('summary').click();await p.locator(`#administration [data-acc-page=${id}]`).click();await p.locator('#administration [data-acc-action=tutorial-help]').click();await p.locator('.fmz-course-help h2').waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'owner help fits viewport');if(id==='bank')await p.screenshot({path:dir+'/administration-help-mobile.png'});assert.match(await p.locator('.fmz-course-help').innerText(),/Voorbeeld:/);assert.equal(await p.locator('.fmz-course-help a').count(),C.help[id].refs.length);await p.locator('.fmz-course-help button').last().click();}
 await p.locator('#administration [data-acc-action=tutorial]').click();await p.locator('iframe').contentFrame().locator('[data-action=start]').waitFor();const f=p.frames().find(f=>f.url().includes('course.html'));await f.locator('[data-action=start]').waitFor();assert.equal(await p.locator('iframe').getAttribute('sandbox'),'allow-scripts allow-downloads');
 const blocked=await f.evaluate(async()=>{const r={};for(const [k,fn] of Object.entries({parent:()=>parent.document.body.innerHTML,storage:()=>localStorage.length,cookies:()=>document.cookie,accounting:()=>FMZAccounting.command('invoice_issue',{}),parentCommand:()=>parent.FMZAccounting.command('invoice_issue',{})})){try{fn();r[k]=false}catch{r[k]=true}}
  try{await fetch('/__test__/rpc',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account:'trainer',name:'fmz_accounting_command',params:{action:'invoice_issue',payload:{},request_id:'forbidden'}})});r.fetch=false}catch{r.fetch=true}
  try{await fetch('/storage/v1/object/fmz-finance/forbidden.pdf',{method:'POST',body:'forbidden'});r.upload=false}catch{r.upload=true}
  try{navigator.sendBeacon('/__test__/rpc','forbidden');r.beacon=true}catch{r.beacon=true}
  const nonce=location.hash.slice(1);for(const type of ['command','upload','invoice','email','navigate'])parent.postMessage({channel:'fmz-course-v1',nonce,type,action:'invoice_issue',url:'https://example.test',payload:{amount:999}},'*');
  parent.postMessage({channel:'fmz-course-v1',nonce,type:'progress',progress:{current:5,last:999,completed:[1,1,999,'secret'],tasks:['week-0','private-secret'],financial:{secret:'SHOULD_NOT_PERSIST'}}},'*');return r;});assert(Object.values(blocked).every(Boolean));
 const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('fmz-course-progress-v1')));assert(!JSON.stringify(saved).includes('secret'));assert.deepEqual(saved.completed,[1]);assert.deepEqual(saved.tasks,['week-0']);
 await openLesson(f,16);await f.locator('#csvFile').setInputFiles({name:'real-like.csv',mimeType:'text/csv',buffer:Buffer.from('PRIVATE FINANCIAL VALUES')});assert.match(await f.locator('#csvStatus').innerText(),/niet het vaste oefenbestand/);assert.equal(await f.locator('#csvFile').inputValue(),'');await f.locator('#csvFile').setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from(M.csv)});await f.locator('#csvStatus').filter({hasText:'Exact het vaste'}).waitFor();

 await p.locator('.fmz-course-host>header button').click();assert.equal(await p.locator('iframe').count(),0);assert.deepEqual(await snapshot(server.database.db),before);assert.equal(server.calls.length,callsBefore);assert.equal(server.blobs.size,0);
 await p.locator('#administration [data-acc-action=tutorial]').click();await p.locator('iframe').waitFor();await p.evaluate(()=>FMZAccounting.lock());assert.equal(await p.locator('iframe').count(),0,'account lock destroys the practice context');
 fs.writeFileSync(dir+'/isolation.json',JSON.stringify({blocked,allSyntheticTablesIdentical:true,tables:Object.keys(before),callsDuringHelpAndPractice:0,storageUploads:0,realNumbers:0,emails:0,externalCosts:0},null,2));
 }finally{await browser.close();await server.close();}});
test('resume, retry, reset, keyboard, mobile themes and all main routes remain usable',{timeout:180000},async()=>{const server=await start(0),browser=await chromium.launch({channel:'msedge',headless:true}),p=await browser.newPage();try{
 await p.goto(server.url+'/tutorial.html');let f=p.frames().find(f=>f.url().includes('course.html'));await f.locator('[data-action=start]').waitFor();
 const screenshots=[];for(const [width,height] of [[320,700],[390,844],[768,1024],[1400,1000]])for(const theme of ['light','dark']){await p.setViewportSize({width,height});await f.evaluate(theme=>document.body.dataset.theme=theme,theme);for(const route of ['home','topics','glossary','tasks']){await f.locator(`[data-action=${route}]`).first().click();assert(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width} ${theme} ${route}`);if(width===390||width===1400){const name=`${route}-${width}-${theme}.png`;await p.screenshot({path:dir+'/'+name});screenshots.push(name);}}await openLesson(f,8);await f.locator('[data-action=to-exercise]').click();assert(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),JSON.stringify(await f.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,bad:[...document.querySelectorAll('*')].filter(e=>e.scrollWidth>e.clientWidth+2).map(e=>({tag:e.tagName,cls:e.className,width:e.clientWidth,scroll:e.scrollWidth,text:e.textContent.slice(0,40)})).slice(0,12)}))));await f.locator('[name=description]').fill('Tijdelijke synthetische invoer');await f.locator('[name=amount]').fill('38,');await f.locator('[name=amount]').focus();const prior=await f.locator('[name=amount]').evaluate(e=>({start:e.selectionStart,value:e.value}));await f.locator('[name=amount]').press('0');assert.equal(await f.locator('[name=amount]').inputValue(),'38,0');assert(await f.locator('[name=amount]').evaluate(e=>document.activeElement===e));assert.equal(prior.value,'38,');if(width===390){const name=`exercise-${width}-${theme}.png`;await p.screenshot({path:dir+'/'+name});screenshots.push(name);}}
 await openLesson(f,5);await f.locator('[name=category]').selectOption('privéstorting');await f.locator('[data-action=check-practice]').click();await f.locator('[name=q0][value="1"]').check();await f.locator('[name=q1][value="0"]').check();await f.locator('[data-action=check-quiz]').click();assert.match(await f.locator('#lessonComplete').innerText(),/afgerond/);await f.locator('[data-action=next]').click();await f.locator('[data-action=previous]').click();assert.match(await f.locator('h1').innerText(),/Privéstorting/);
 await f.locator('[data-action=retry]').last().click();assert.equal(await f.locator('[name=category]').inputValue(),'');await f.locator('[data-action=close]').click();await p.locator('[onclick]').click();await p.locator('iframe').contentFrame().locator('[data-action=resume]').waitFor();f=p.frames().find(f=>f.url().includes('course.html'));await f.locator('[data-action=resume]').waitFor();await f.locator('[data-action=resume]').click();assert.match(await f.locator('h1').innerText(),/Privéstorting/);assert.equal(await f.locator('[name=category]').inputValue(),'');
 await f.locator('[data-action=glossary]').click();await f.locator('#termSearch').fill('privéstorting');assert(await f.locator('.definition').count()>0);await f.locator('#termSearch').fill('zzzzgeenbegrip');assert.match(await f.locator('#terms').innerText(),/Geen begrip/);
 await f.locator('[data-action=home]').click();await f.locator('[data-action=reset]').click();await f.locator('[data-action=confirm-reset]').click();assert.equal((await p.evaluate(()=>JSON.parse(localStorage.getItem('fmz-course-progress-v1')))).completed.length,0);assert.deepEqual(server.calls,[]);
 fs.writeFileSync(dir+'/responsive.json',JSON.stringify({viewports:4,themes:2,routes:['home','topics','glossary','tasks','exercise'],horizontalOverflow:false,screenshots},null,2));
 }finally{await browser.close();await server.close();}});
